### ISSUE TITLE
ERROR: Source emitted more than one item.  AND:  Add the batch "AddGroupMember" function.

### ISSUE THREAD

**Issue by zhjphp** [turms-im/turms#1000]
I need to add a lot of member when create the gourp, Currently only one user can be added the group at a time, so i need repeat excute "AddGroupMember" api, but the service response error: 

`{"code":1200,"reason":"Source emitted more than one item","timestamp":"2022-08-25T09:13:56.870+00:00"}`

I had also tried every request with a 10 second interval, it is still have this error, I don't know why this error occurs.

Is it possible to consider adding the batch "AddGroupMember" function ?

**Comment by JamesChenX** [comment]
Did you call `AddGroupMember` via admin HTTP or client API?

**Comment by zhjphp** [comment]
> Did you call `AddGroupMember` via admin HTTP or client API? And please provide the parameters with which you called the API so that I can reproduce it.

I use admin HTTP API.
This my code and request data when i batch excute "addUser" ( not add group user ):

![github_error](https://user-images.githubusercontent.com/1875486/186806651-d0a0dfab-7bd5-4784-a910-a17919258594.png)

The error does not appear every request, but it will definitely appear within 30-50 requests.

**Comment by zhjphp** [comment]
> Thanks for reporting.
> 
> 1. The error `Source emitted more than one item` has been fixed, and you can pull the latest code to try it.
> 2. For batch insert for admin HTTP, I have created a new ticket [Support batch insert for admin HTTP #1002](https://github.com/turms-im/turms/issues/1002) to trace, and the feature may be delivered in 3 months.

Thank you, Is the  the error caused by "single()" function receiving multiple elements ?

**Comment by JamesChenX** [comment]
In the commit https://github.com/turms-im/turms/commit/e7346a57801e003d3a47039a87346871c4ceb94c, `request.receive()` returns a flux, and should not come with `.singleOrEmpty()` or it will throw the error `Source emitted more than one item` because flux may emit multiple elements.

**Comment by zhjphp** [comment]
> In the commit [e7346a5](https://github.com/turms-im/turms/commit/e7346a57801e003d3a47039a87346871c4ceb94c), `request.receive()` returns a flux, and should not come with `.singleOrEmpty()` or it will throw the error `Source emitted more than one item` because flux may emit multiple elements.

I updated the fix, but another error occurred:
Error:
{"code":1102,"reason":"Illegal request body: Unexpected end-of-input in field name\n at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 185]","timestamp":"2022-08-31T09:03:38.886+00:00"}

Same as previous error with request data and target API, and the roles same too (The error does not appear every request, but it will definitely appear within 30-50 requests.).

**Comment by JamesChenX** [comment]
@zhjphp I use the following code to send 10_000 CreateUser requests to turms-service, and all of them are successful.
And `Unexpected end-of-input in field name` seems you pass an illegal JSON in the request body.

![image](https://user-images.githubusercontent.com/44962329/187670744-ccc46f11-f8e6-4567-a289-21d6be786e9f.png)

**Comment by zhjphp** [comment]
@JamesChenX 

I sure it is not json request body problem, i tried it with turms-admin and my code to add user, it has same error, the key problem is that the same request json body sometimes succeeds and sometimes fails.

![error-1](https://user-images.githubusercontent.com/1875486/187822417-8afb1ac6-4024-413c-ab8a-d7f855f2073f.png)

It is fails.

![ok-1](https://user-images.githubusercontent.com/1875486/187822507-31ee1161-57a3-429f-af0f-ec118f962a81.png)

The same request , it is succeed.

These errors have the same characteristics: [ it has very long chinese text ]

------------------------------------------------------

This is request json body:

{
    "id":11116,
    "password":123456,
    "name":"测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容",
    "intro":"测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容测试内容",
    "permissionGroupId":1,
    "profileAccess":"ALL",
    "registrationDate":"2022-09-01T02:19:34.468Z",
    "isActive":true
}

**Comment by JamesChenX** [comment]
@zhjphp Fixed. Thanks for reporting.

**Comment by zhjphp** [comment]
> @zhjphp Fixed. Thanks for reporting.

Thanks alot, I tested it, no problem.
