### ISSUE TITLE
About JS-Client automatic logout

### ISSUE THREAD

**Issue by zhjphp** [turms-im/turms#1005]
When js-client login, and after a while, js-client show logout, can not sending message.

If i want keep stay online, do i need to listen `driver.addOnDisconnectedListener` ? Then after to excute `userService.login(...)` ?

**Comment by JamesChenX** [comment]
If you don't set the heartbeat timeout parameters on both the client side and server side, the client will send heartbeat requests to the server to keep alive and should not log out automatically. 

---

> If i want keep stay online, do i need to listen driver.addOnDisconnectedListener ? Then after to excute userService.login(...) ?

No because of the reason above.
