### ISSUE TITLE
messageService.queryMessages issues

### ISSUE THREAD

**Issue by train860** [turms-im/turms#1007]
messageService.queryMessages always fetch all messages, not the fromIds

**Comment by JamesChenX** [comment]
Please provide all parameters that you used.

**Comment by train860** [comment]
Here is my code:
`const handleFetchMessages=(data:any)=>{
  console.log('fetch messages from',targetId.value);
  client.messageService.queryMessages({ fromIds: [targetId.value],size:10 }).then((res:any) => {
        const _list: Message[] = (res.data as any[]).map((item: any) =>parseMessage(item));
        messageState.list = data.options.reset?_list:[...messageState.list, ..._list];
        console.log('messages:',res);
      }).finally(()=>{
        //messageLoaded.value = true;
      });
}`

and the result for fromIds=[2] and fromIds=[3], not only same, but also wrong, fromIds=[3] should not contain the message of senderId=2

![WeChat9e4b8bf9855c917729dd50b1aad06750](https://user-images.githubusercontent.com/6874537/188532774-8bf38e11-def3-4d10-91ff-080fd771bafa.png)
![WeChat8e0216c733a604e1b62f58b143a9ca63](https://user-images.githubusercontent.com/6874537/188532823-b1cc96b0-714b-4be6-bdf6-848c6355c1b4.png)

**Comment by JamesChenX** [comment]
Your client request is illegal and should be rejected by the server in the latest code.
Please pull the latest code and try again.
