### ISSUE TITLE
Error creating bean with name 'adminApiRateLimitingManager'

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1010]
turms-service 在本地启动报错，启动不了
main s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adminApiRateLimitingManager' defined in file [D:\workspace\code\turms\turms-service\target\classes\im\turms\service\access\admin\throttle\AdminApiRateLimitingManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [im.turms.service.access.admin.throttle.AdminApiRateLimitingManager]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'node' defined in class path resource [im/turms/server/common/infra/cluster/ClusterConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [im.turms.server.common.infra.cluster.node.Node]: Factory method 'node' threw exception; nested exception is java.lang.IllegalStateException: Failed to create the collection for the class: im.turms.server.common.infra.cluster.service.config.entity.property.SharedClusterProperties
启动环境dev
public SharedConfigService(TurmsMongoProperties properties) {
        try {
            mongoClient = TurmsMongoClient.of(properties)
                    .block(Duration.ofMinutes(1));
        } catch (Exception e) {
            throw new IllegalStateException("Failed to create the shared config service", e);
        }
        List<Class<?>> classes = List.of(SharedClusterProperties.class, Leader.class, Member.class);
        mongoClient.registerEntitiesByClasses(classes);
        for (Class<?> entityClass : classes) {
            try {
                mongoClient.createCollection(entityClass).block(Duration.ofMinutes(1));
            } catch (Exception e) {
                throw new IllegalStateException("Failed to create the collection for the class: " + entityClass.getName(), e);
            }
        }
        try {
            mongoClient.ensureIndexesAndShard(classes).block(Duration.ofMinutes(1));
        } catch (Exception e) {
            throw new IllegalStateException("Failed to ensure the indexes are created for the classes: " + classes.stream()
                    .map(Class::getName).toList(), e);
        }
    }
![image](https://user-images.githubusercontent.com/8073980/190293107-b473eadf-3c1c-4ef2-b07c-587f62c01193.png)
感觉是重复创建引起的问题
![image](https://user-images.githubusercontent.com/8073980/190293348-cdabbf06-63fe-463e-ba0e-29184a1845a6.png)
这两个地方不抛异常的话，可以正常启动，麻烦帮看下是什么问题哈

**Comment by itmagus** [comment]
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/turms-im/turms.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "develop"]
	remote = origin
	merge = refs/heads/develop
.git的配置文件，代码是最新的
mongodb的版本
镜像：mongo:4.2.1

**Comment by JamesChenX** [comment]
I just tried mongo4.2.1 without any problem, and you can check:
1. Ensure you connect turms servers to mongos instead of mongodb
2. Drop all collections and run turms-service to ensure your collection schema isn't outdated.

**Comment by itmagus** [comment]
好的，感谢指导，我现在是直接连接到mongodb的，我装个mongo集群试下

**Comment by itmagus** [comment]
换成mongodb分片集群，并给账号授予对应的权限后，启动正常，我mongo用的6.x也没的问题。感谢 @JamesChenX

**Comment by JamesChenX** [comment]
Glad to hear of your success. Have a good day.
