### ISSUE TITLE
adminApiAddress

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1011]
turms-admin会通过服务发现的接口返回adminApiAddress的地址，默认是服务所在的内网地址，如果需求通过外网或网关让turms-admin可以访问，是需要在turms-service或turms-gateway中去配置adminApiAddress的地址吗？
如果是需要怎么配置呢，感觉在文档中没有详细说明，还是我没找到？
![image](https://user-images.githubusercontent.com/8073980/190883254-85ab11fd-020b-49b2-9212-cd62a6d842db.png)

**Comment by JamesChenX** [comment]
The related properties are:
`turms.gateway/service.admin-api.address.advertise-strategy=advertise_address`
`turms.gateway/service.admin-api.address.advertise-host=`

If you want to access the admin APIs of `turms-service` or `turms-gateway` in public, you just need to provide public IPs or hosts for users to access (Just a reminder, you can configure the security group to limit the IPs that can access the IPs).
1. So if you want to configure the admin address to use the public IP, you can configure `turms.gateway/service.admin-ap
i.address.advertise-strategy=public_address`.
2. If you want to use custom host/IP, you can configure:
`turms.gateway/service.admin-api.address.advertise-strategy=advertise_address`
`turms.gateway/service.admin-api.address.advertise-host=<your_custom_ip_or_host>`

**Comment by itmagus** [comment]
好的，感谢解答
