### ISSUE TITLE
queryFriends is null

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1019]
请问下是什么原因，查不到好友数据呢？
turms_client_dart
client.userService.queryFriends();
Response{timestamp: 2022-09-30 14:29:05.891, requestId: 4165419321, code: 1001, data: null}
admin的API可以查的到
![image](https://user-images.githubusercontent.com/8073980/193206397-4f250898-5d1e-4366-ac9f-b793e6d1f2b9.png)

**Comment by JamesChenX** [comment]
I have pushed a commit to enhance the requests of querying relationships to support querying relationships in different groups by a request.
If you don't pass any param to `queryFriends`, you are querying all friends of a user.
You can pull the latest code in the `develop` branch to have a try.

**Comment by itmagus** [comment]
看queryFriends调用的是
queryRelationships(
          isBlocked: false,
          groupIndexes: groupIndexes,
          lastUpdatedDate: lastUpdatedDate);
只要传了isBlocked不管是true还是false都查不到数据
不知道是不是我添加好友的过程有问题咯
