### ISSUE TITLE
Failed to run SpringBoot Application directly: git.properties must exist in production

### ISSUE THREAD

**Issue by MeetAlpha** [turms-im/turms#1027]
I failed to run the gateway and service on Windows. Here are the logs. I have installed git-commit-id-maven-plugin in pom.xml. Thanks for troubleshooting my problem.
```
Error creating bean with name 'adminApiRateLimitingManager' defined in file 
nested exception is .........
............
nested exception is java.lang.IllegalStateException: git.properties must exist in production
```

**Comment by JamesChenX** [comment]
1. Set `spring.profiles.active` to `dev`.
![image](https://user-images.githubusercontent.com/44962329/194088166-8be085c6-39b9-4d4d-9d6d-1e4eadb79632.png)
2. Or run `mvn compile` in the root dir of turms project e.g.`C:\projects\turms> mvn compile` to generate the `git.properties` file.

**Comment by MeetAlpha** [comment]
Thanks.  It works for me.
