### ISSUE TITLE
Store the order of the answers to the group membership question

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#1032]

**Comment by DevPJ9** [comment]
Hello, @JamesChenX I would like to contribute. Can you please provide some more info on the task?

**Comment by JamesChenX** [comment]
Hi, @DevPJ9 , I'm glad you want to contribute.
This ticket needs some small changes in turms-client-js/kotlin/swift/dart, and turms-service, so it requires a full-stack developer with a MacOS to implement the feature. And if you are still interested in it. I can write more implementation details for you.

**Comment by DevPJ9** [comment]
Thanks for your reply @JamesChenX. I am sorry but I don't have macOS so I will focus on the other task. :)
