### ISSUE TITLE
Support limiting the content length of user profile

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#1036]

**Comment by DevPJ9** [comment]
Hello, @JamesChenX I would like to contribute. Can you please provide some more info on the task?

**Comment by JamesChenX** [comment]
Hi, @DevPJ9, I'm glad you want to contribute.
The motivation of this ticket is to limit the content length of the user profile including the fields of `name`, `intro`, and `profilePicture` in `im.turms.server.common.domain.user.po.User` so that users cannot set a huge string.

To do so:
1. You can add three properties like `nameLengthLimit` (20 by default), `introLengthLimit`  (100 by default) and `profilePictureLengthLimit`  (100 by default) in `im.turms.server.common.infra.property.env.service.business.user.UserProperties`
2. Then, apply these properties like the implementation of `im.turms.server.common.infra.property.env.service.business.user.FriendRequestProperties#contentLimit`.
3. Finally, you need to update the JSON files in the methods to pass tests: `unit.im.turms.server.common.infra.property.TurmsPropertiesConvertorTests#mergeMetadataWithPropertyValue`, `unit.im.turms.server.common.infra.property.TurmsPropertiesInspectorTests#metadata`, and `unit.im.turms.server.common.infra.property.TurmsPropertiesInspectorTests#onlyMutableMetadata`.

And feel free to ask if you encounter any problems.

**Comment by DevPJ9** [comment]
Thanks for the description @JamesChenX. I will ping you If I get stuck. :)

**Comment by DevPJ9** [comment]
Hello, @JamesChenX I have updated the fields in UserProperties files, but I am unable to find the JSON files.

**Comment by JamesChenX** [comment]
Hi @DevPJ9 ,
You can find the JSON files in this way: 
![image](https://user-images.githubusercontent.com/44962329/196010030-94f95689-1f1d-4283-b2e7-81173129cddf.png)

And you can get the latest JSON schema by setting a breakpoint in the method mentioned as the following image shows, and copying the `json` variable value to the JSON files mentioned above respectively:
![image](https://user-images.githubusercontent.com/44962329/196010038-a91ed44b-b81e-44c3-9e7c-83084936f1e4.png)

**Comment by DevPJ9** [comment]
Thanks @JamesChenX. I have finished the task and raised a PR: #1045 please check and let me know if there are any changes needed. :)
