### ISSUE TITLE
About querying messages sent by itself.

### ISSUE THREAD

**Issue by IT-Pianist** [turms-im/turms#1039]
In findMessages, enableConversationId must ensure that senderIds and targetIds are not empty, but when senderIds and targetIds are not empty, only the query with CONVERSATION_ID condition is added. Therefore, it is impossible to query the messages sent by itself.

**Comment by JamesChenX** [comment]
Querying messages sent by oneself isn't supported currently. I will adapt the workflow for the feature this weekend and write docs for it.

**Comment by JamesChenX** [comment]
@IT-Pianist The feature has been delivered, and you can use the feature via the config `turms.service.message.use-conversation-id=true`.
And you can query the messages (including the messages sent by oneself) in private conversations by `turmsClient.messageService.queryMessages({areGroupMessages: false, fromIds: [10,11,12]})`, for example.
