### ISSUE TITLE
addRelationship

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1043]
请问一下通过admin api初始用户关系的正确方式是什么
通过post /users/relationships
参数
{"ownerId":1126159152876331008,"relatedUserId":1,"blockDate":null,"establishmentDate":"2022-10-15T13:21:22.759Z"}
返回
{"code":2500,"reason":"Cannot add a not related user to a relationship group","timestamp":"2022-10-15T13:30:37.840+00:00"}
数据库
{
    "_id" : {
        "rid" : NumberLong(1),
        "oid" : NumberLong(1126159152876331008)
    },
    "ed" : ISODate("2022-10-15T13:21:22.759+0000")
}
admin ui
![image](https://user-images.githubusercontent.com/8073980/195989406-c7cd774f-f3ed-44b5-acc5-36e972a451a8.png)
关系组
![image](https://user-images.githubusercontent.com/8073980/195989521-7d3303d7-4d3b-4ba9-b0e6-85f12a88a00a.png)

**Comment by JamesChenX** [comment]
Thanks for reporting. It seems a bug, and I will fix it today and add tests for it.

**Comment by itmagus** [comment]
好的

**Comment by JamesChenX** [comment]
Fixed.
