### ISSUE TITLE
messageListener senderId 0

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1059]
// Listen to inbound messages
    client.messageService.addMessageListener((message, _) => Log.info(
        'onMessage: Receive a message from other users or server: $message'));

![image](https://user-images.githubusercontent.com/8073980/197381499-17a944f7-dea8-4f84-a85d-62ec566ee5b0.png)
![image](https://user-images.githubusercontent.com/8073980/199135693-a21ea800-fa53-420a-9c3a-dcc7d068fe93.png)

**Comment by itmagus** [comment]
@JamesChenX 这个现象确认了吗？

**Comment by JamesChenX** [comment]
I am busy currently and will check it tomorrow.

**Comment by JamesChenX** [comment]
I don't figure out the relationship between the two screenshots.
The first screenshot shows the message with the ID `3756264089890934784`, and the second screenshot shows the message with the ID `6809704287067242496`.
So, what is the problem?

**Comment by itmagus** [comment]
不好意思哈，我重新截了图
