### ISSUE TITLE
turms-plugin-minio

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1060]
按文档在本地跑，还是通过admin上传插件都报
Failed to load the plugin class im.turms.plugin.impl.MinioStorageServiceProvider
![image](https://user-images.githubusercontent.com/8073980/197403167-e9ae9e29-811e-46e6-a82e-d24a95fcc74d.png)

是因为是im.turms.的包名通过getParent().loadClass(name)应该是加载不到的？
请问turms-plugin-minio要怎么部署？

**Comment by JamesChenX** [comment]
@itmagus I will give a big update on `turms-plugin-minio` and write a doc on it today or tommorrow, so don't try to use it currently.
And I will @at you once the updated is released.

**Comment by itmagus** [comment]
好的

**Comment by JamesChenX** [comment]
@itmagus The new storage implementation has been released on the branch `develop` and `master`.
You can use it currently, or wait for the docs that will be published later.

**Comment by itmagus** [comment]
@JamesChenX 请问下turms-plugin-minio插件的文档发布了吗

**Comment by itmagus** [comment]
Error creating bean with name 'pluginManager': Requested bean is currently in creation: Is there an unresolvable circular reference?
![image](https://user-images.githubusercontent.com/8073980/200770074-e9dba5dc-9744-4585-a4b9-ec168893e39b.png)
@JamesChenX 按文档说明操作，跑不起来哈

**Comment by JamesChenX** [comment]
> @JamesChenX 请问下turms-plugin-minio插件的文档发布了吗

Done. https://turms-im.github.io/docs/for-developers/storage.html

**Comment by itmagus** [comment]
> > 按文档说明操作，跑不起来哈
> 
> Thanks for reporting. It has been fixed ([e054c37](https://github.com/turms-im/turms/commit/e054c37d7aad343b1604be9e0039e3bbe6d0ddce)), and you can try it in the `develop` branch.
> 
> > 请问下turms-plugin-minio插件的文档发布了吗
> 
> It will be published tonight or tomorrow.

谢谢，更新代码后正常启动
