### ISSUE TITLE
dest/bin only have windows bash not linux or mac bash

### ISSUE THREAD

**Issue by forxfoo** [turms-im/turms#107]

**Comment by JamesChenX** [comment]
The script for Linux will be delivered this week or next week because I am busy with turms-admin right now. #12
I will @ you when I finish the job.

**Comment by JamesChenX** [comment]
I have deployed a turms cluster successfully in Linux via turms.sh in dist/bin.

@forxfoo You can download the newest package with turms.sh at https://github.com/turms-im/turms/releases/tag/turms-0.9.0-SNAPSHOT.20191128.

And I will write a tutorial about deployment later.
For short, You may need to the path of hazelcast.config to your real path in application.yaml
