### ISSUE TITLE
storageService.uploadMessageAttachment(messageId, mediaType, data)

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1080]
请问下storageService.uploadMessageAttachment(messageId, mediaType, data)
与
sendMessage(bool isGroupMessage, Int64 targetId,
      {DateTime? deliveryDate,
      String? text,
      List<Uint8List>? records,
      int? burnAfter,
      Int64? preMessageId})
应该怎么配合使用，是先调用sendMessage，获取messageId后再调用uploadMessageAttachment？

**Comment by itmagus** [comment]
还是说storageService.uploadMessageAttachment(messageId, mediaType, data)
中的中messageId,可以是任一的随机数，上传附件成功后，
再调用sendMessage，通过自定义的消息结构，建立附件和消息的关联关系？

**Comment by JamesChenX** [comment]
Thanks for sharing the use cases.
After research, I will make it easier to use (To put it simply, upload the attachments first, and then send the message including the attachment IDs) while supporting new storage features recently, and I will @ you once I deliver these features.

**Comment by itmagus** [comment]
@JamesChenX 请问下存储重构，时间上的规划是怎么样的

**Comment by JamesChenX** [comment]
@itmagus I am very busy recently, so cannot take too much time on these features for attachments on the weekend this week.
But I promise to deliver the features (code+docs) this weekend when I am not that busy.

In one word, you can use the feature on 12/05 latest.

**Comment by itmagus** [comment]
好的，感谢您的付出和持续输出

**Comment by itmagus** [comment]
@JamesChenX 好了记得说一下哦

**Comment by JamesChenX** [comment]
@itmagus Sorry for the lateness. The code has been pushed onto `develop` and `master`.
In short, you can call `uploadMessageAttachmentInPrivateConversation` and `uploadMessageAttachmentInGroupConversation` on the client side to upload attachments currently.

**Comment by itmagus** [comment]
好的，谢谢，我测试一下
