### ISSUE TITLE
SocketException (SocketException: Failed host lookup: 'xxxx.com' (OS Error: No address associated with hostname, errno = 7))

### ISSUE THREAD

**Issue by shengbiliPaul** [turms-im/turms#1081]
After executing  await client.userService.login(Int64(1), password: '123'); Wrong times. This problem occurs on both Android and iOS。

**Comment by JamesChenX** [comment]
From the error `(SocketException: Failed host lookup: 'xxxx.com' (OS Error: No address associated with hostname, errno = 7)`, it seems a DNS problem that has nothing to do with turms clients.

You can try the solutions mentioned in this post: https://stackoverflow.com/questions/5829779/unable-to-resolve-host-insert-url-here-no-address-associated-with-hostname
