### ISSUE TITLE
OpenAPI docs cannot be opened

### ISSUE THREAD

**Issue by Mihoks** [turms-im/turms#1096]
At first I thought it was said in the document that the port of the production environment was closed
1、in  service-common/META-INF/services/org.slf4j.spi.SLF4JServiceProvider configuration error do not print log
change into ：im.turms.server.common.infra.logging.slf4j.Slf4jServiceProvider
2、error:  javax.xml.bind.annotation does not exist，because javax.xml.bind was removed after jdk8 , 

add in the pom file
`<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
`
Try to open the document address：
插件相关API接口
OpenAPI地址：http://playground.turms.im:8510/openapi/ui#/plugin-controller
<img width="1782" alt="1" src="https://user-images.githubusercontent.com/17864038/205246090-e75c9ebc-5960-44a5-b588-35b2f259e2dd.png">
<img width="1502" alt="2" src="https://user-images.githubusercontent.com/17864038/205246125-26dc8158-0251-41af-b697-16d0295cf4ad.png">

**Comment by JamesChenX** [comment]
Thanks for reporting.
The bug has been fixed in both `develop` and `master` branches, and you can pull it if you need.

**Comment by Mihoks** [comment]
> Thanks for reporting.
> The bug has been fixed in both `develop` and `master` branches, and you can pull it if you need.

Wow, thank you. It's so fast.
