### ISSUE TITLE
The type jdk.internal.vm.annotation.Contended is not accessibleJava(16778666)

### ISSUE THREAD

**Issue by l-7-l** [turms-im/turms#1113]
filepath: [turms-server-common\src\main\java\im\turms\server\common\infra\collection\SpscGrowableLongRingBuffer.java](https://github.com/turms-im/turms/blob/9149d1f773da14ead0e564fa3ce0dac7b2d46364/turms-server-common/src/main/java/im/turms/server/common/infra/collection/SpscGrowableLongRingBuffer.java#L21)

i am not used java, it seems not allowed. [see here](https://stackoverflow.com/a/72675144/7433364)

**Comment by JamesChenX** [comment]
The compiler argument `--add-exports=java.base/jdk.internal.vm.annotation=ALL-UNNAMED` has been added in the `pom.xml` of `turms-server-common`, so the error should not occur when compiling if you are using maven 3.x + JDK 17 correctly.

Please check your env, and ensure you are using maven 3.x, JDK17, and load the `pom.xml` correctly in IDE (if you are using an IDE, you can try to clear the cache), and try again.
