### ISSUE TITLE
[Swagger] Failed to load API definition.

### ISSUE THREAD

**Issue by l-7-l** [turms-im/turms#1118]
address: http://localhost:8510/openapi/ui

```
Errors

 
Fetch error
NetworkError when attempting to fetch resource. http://172.19.0.8:8510/openapi/docs
Fetch error
Possible cross-origin (CORS) issue? The URL origin (http://172.19.0.8:8510) does not match the page (http://localhost:8510). Check the server returns the correct 'Access-Control-Allow-*' headers.
Fetch error
NetworkError when attempting to fetch resource. http://172.19.0.8:8510/openapi/docs
Fetch error
Possible cross-origin (CORS) issue? The URL origin (http://172.19.0.8:8510) does not match the page (http://localhost:8510). Check the server returns the correct 'Access-Control-Allow-*' headers.
```

**Comment by JamesChenX** [comment]
**ALL** turms HTTP responses have the following headers:
* `Access-Control-Allow-Origin: *`
* `Access-Control-Allow-Methods: *`
* `Access-Control-Allow-Headers: *`

So CORS should not occur if a browser recognizes `*`.
1. Were you using any proxy that may remove the HTTP response headers? (You can check whether the browser gets the above HTTP response headers)
2. Which browser did you use? So I can do some research on it.

**Comment by l-7-l** [comment]
@JamesChenX 抱歉回复的晚了. 之前在Win11上跑的， 我切换到 linux之后可以了. 再次感谢兄
