### ISSUE TITLE
使用SPM导入 turms-client-swift 总是报这个错误

### ISSUE THREAD

**Issue by wushuangys** [turms-im/turms#1119]
没有生成framework，请问这个要怎么处理?

**Comment by wushuangys** [comment]
<img width="1096" alt="pic1" src="https://user-images.githubusercontent.com/24885821/211478006-412c2e3b-a04e-461a-9fc6-eb4ba2665f16.png">
<img width="1025" alt="pic2" src="https://user-images.githubusercontent.com/24885821/211478013-7f4f10c5-76f4-4118-98bc-002571898333.png">

**Comment by JamesChenX** [comment]
Thanks for reporting.
I have commented out the development dependencies of turms-client-swift, and you can use the latest code in the `develop` branch, and it will pass.

**Comment by wushuangys** [comment]
感谢，已经可以使用了
