### ISSUE TITLE
请问在ide启动turms-gateway如何能将日志打印在控制台呢？

### ISSUE THREAD

**Issue by yunan01** [turms-im/turms#1129]

**Comment by yunan01** [comment]
edit application.yaml , update turms.logging.console.enabled=true  ; or update the active profiles of the ide to "dev"

**Comment by JamesChenX** [comment]
For development purposes, just set `spring.profiles.active` to `dev` to use the settings in `application-dev.yaml` which uses settings used for development purposes.

![1675936293656](https://user-images.githubusercontent.com/44962329/217778510-99bebb47-1aa2-4c4c-bc92-f43783d925be.png)
