### ISSUE TITLE
Add an official plugin to support `RasaHQ/rasa`

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#1131]

**Comment by itmagus** [comment]
作者什么时候搞在这插件哈，我也需要

**Comment by JamesChenX** [comment]
@itmagus I have researched it, and it's easy to write the plugin but need to adapt some code of Turms server to support it, so it needs some time to design.

I am not sure when to deliver the feature, but I can spend 1~2 hours per day designing and writing code because I am busy and need to review my project experience + recite 八股文 + practice algorithms😅 recently to find a new job. So it will take some time for the plugin (maybe less than a month? I am not sure honestly)

And if you are interested in writing the plugin, you can have a try.

**Comment by itmagus** [comment]
好的，我现这一两个星期的工作进展应该就会到这里了，我可以尝试一下

**Comment by itmagus** [comment]
@JamesChenX 你调整完服务端的代码后，可以通知我哈

**Comment by JamesChenX** [comment]
@itmagus The design and implementation are easier than I expected, so I have written the plugin without testing.
And the PR https://github.com/turms-im/turms/pull/1137 is just a draft, meaning that some workflow of the plugin may need a redesign and I will polish the code later.

If you are interested in it, you can check the PR to know whether the features of the plugin meet your requirements, and if you need more features, you can require them before I will the plugin, so the development process will be faster.

**Comment by JamesChenX** [comment]
Done.
Doc: https://turms-im.github.io/docs/for-developers/chatbot.html
