### ISSUE TITLE
can not open http://localhost:6510/

### ISSUE THREAD

**Issue by l-7-l** [turms-im/turms#1134]
git clone --depth 1 https://github.com/turms-im/turms.git
cd turms
docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
docker compose -f docker-compose.standalone.yml up --force-recreate

firefox console: Uncaught ReferenceError: process is not defined

**Comment by JamesChenX** [comment]
Fixed. Thanks for reporting.
