### ISSUE TITLE
链接文档中的 Playground，登录时后台报错。

### ISSUE THREAD

**Issue by lbhfuture** [turms-im/turms#1136]
1. 使用 turms-client-js 中的 Demo 登录报错，链接地址为 ws://playground.turms.im:10510，报错信息为
<img width="424" alt="image" src="https://user-images.githubusercontent.com/8817547/220262979-ae153252-589c-41d4-b30f-2d2b145a8bef.png">
2. 使用 playground admin 中的 terminal 也是包同样的错误
<img width="611" alt="image" src="https://user-images.githubusercontent.com/8817547/220263189-3ca339be-4500-47f0-b374-2aa839485180.png">

**Comment by JamesChenX** [comment]
Fixed. Thanks for reporting.
