### ISSUE TITLE
Support integrating plugins into servers in `docker-compose.standalone.yml` for better deployment experience

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#1138]

**Comment by itmagus** [comment]
是的可以直接，把要使用的插件打包到镜像中，会更方便

**Comment by JamesChenX** [comment]
@itmagus I will work on this once I solve other recent and important issues, so this feature may be supported in 2~5 weeks.
Related issues: #1165 #1166

**Comment by JamesChenX** [comment]
@itmagus The feature has been delivered.
You can read the commit to know how to configure it: https://github.com/turms-im/turms/commit/45b8ad8be18e27793d6fc98fddf985b3e3da1a8d
