### ISSUE TITLE
How can a client know it is mentioned in group conversations before the client gets the messages that mention them?

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1143]
The @ message after the user goes offline assumes that on the 100th message, 20 messages are obtained from each page without knowing that @ messages exist. Are there any good ideas to make the client aware of @ messages

**Comment by JamesChenX** [comment]
This is a good question.

**Currently, if the client doesn't fetch the messages that mention(@)  them, he/she **CANNOT** know they are mentioned by someone in a group conversation.**

**It's reasonable to support this feature, but I don't have enough time for it recently, and the feature isn't a high priority honestly.**

## Implementation Draft
To implement such a feature, a feasible workflow is:
1. The client sends a message with information about who are mentioned.
2. turms-service saves the mention information in Redis with the following data:

| Key (Mentioned User ID)  | Field (Group ID) | Value (Message IDs) |
| ------------------------ | ---------------- | ------------------- |
| m123456<br />(m+user ID) | 789456123        | 123456789,456789    |

btw:
   * The data needs to be removed when a user is removed
   * The data should have a configurable TTL, e.g. 7 days.
   * Some designs may use MongoDB for persistence, but I think Redis is good enough for our cases and more efficient.
   * Some designs may use a notification inbox, and save the mention information as a `mention notification`, but for our cases, the above data structure is good enough.

3. When a user fetches messages in group conversations, turms-service can return corresponding mention information for them before they got the messages.
4. And the UI can provide a mention notification. When a user clicks the mention notification, the UI can navigate/jump to the specific message.

**Comment by LaZy1162999568** [comment]
Well, my understanding is that (@) messages require higher timeliness. Store (@) messages within 7 days and give full notification when fetching the latest contact list. Maybe this is a better solution, thank you.

**Comment by JamesChenX** [comment]
I think the `notification inbox` is what you want.

You remind me to support `persistent notifications` (including not only @mention notifications, but also a lot of other notifications that users can configure), and it's a high-priority feature.
And I have created a ticket for related features: https://github.com/turms-im/turms/issues/1144

I will start supporting the related features once I deliver another important feature (providing a basic push notification system). But I am busy recently, so it may be delivered in 2~3 months.
