### ISSUE TITLE
For the specified history message obtained by the client, there are cases where the message does not need to be rendered

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1153]
For example: 
1) When a message is logically deleted, all 20 of the messages paged by the client are already deleted. 
2) For message recall deletion, I think it would be relatively friendly to insert recall and delete directives into the message flow, similar to in-session notification messages, which are only retrieved when needed. 

For the client, however, each pull should specify at least a number of valid render messages. Of course, the server can query the database multiple times to satisfy this condition, but I think this is stupid. Does the author have any other good advice for me? Thank you

In addition, come on, turms will be a big fire in the future. I have gained a lot in turms. Thank you

**Comment by JamesChenX** [comment]
> In addition, come on, turms will be a big fire in the future. I have gained a lot in turms. Thank you

Thank you for your encouragement, and it's lucky for the community to have people like you to make Turms and its community better.
I want to develop turms full-time so that Turms can move on far faster, but I also need to work and I can take only a part of my time to develop turms, so that's a little pity.

---

For your question, I have written a doc to answer them, and you can take a look: https://turms-im.github.io/docs/for-developers/status-aware.html#%E6%B6%88%E6%81%AF%E6%8E%A5%E6%94%B6%E3%80%81%E6%B6%88%E6%81%AF%E6%9B%B4%E6%96%B0%E4%B8%8E%E6%B6%88%E6%81%AF%E6%92%A4%E5%9B%9E
And you can add comments if you have more questions.

**Comment by LaZy1162999568** [comment]
Of course, I have read the content in the document you mentioned, and the implementation of the process of message withdrawal as a special message is the same as I imagined, but there is a historical message pull problem:
1. Suppose the client withdraws 20 messages in a row
2. Assume that the number of client pages is 20
3. At this time, when the server executes the query, it will query 20 withdrawal notifications. The messages obtained by the client cannot be used for page rendering, but each time the client should be able to obtain the effective rendering when roaming offline messages. information.

**Comment by LaZy1162999568** [comment]
Of course, I have read the content in the document you mentioned, and the implementation of the process of message withdrawal as a special message is the same as I imagined, but there is a historical message pull problem:
1. Suppose the client withdraws 20 messages in a row
2. Assume that the number of client pages is 20
3. At this time, when the server executes the query, it will query 20 withdrawal notifications. The messages obtained by the client cannot be used for page rendering, but each time the client should be able to obtain the effective rendering when roaming offline messages. information.

**Comment by LaZy1162999568** [comment]
当然，我看过您提到的文档中的内容，对于消息撤回的流程实现当做一条特殊的消息和我设想的一样，但是这之间存在一个历史消息拉取问题:
1.假设客户端连续撤回了20条消息
2.假设客户端分页数量为20条
3.此时服务端执行查询会查询出20条撤回通知，客户端获取到的消息不能用于页面渲染，但是客户端每次应该在漫游离线消息时都应该能获取到能用于有效渲染的消息。
