### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by wushuangys** [turms-im/turms#1161]
1. The "ENV" variable is not set. Defaulting to a blank string
2. services.rasa.volumes must be a list

<img width="570" alt="截屏2023-03-07 11 05 19" src="https://user-images.githubusercontent.com/24885821/223310247-01f45a93-e131-4811-be1a-10e709ed1f25.png">

**Comment by JamesChenX** [comment]
Fixed. Thanks for reporting.
You can pull the images again to have a try.
