### ISSUE TITLE
minio plugin mongo

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1190]
![image](https://user-images.githubusercontent.com/8073980/226531916-261805bb-c690-4fdf-b337-59f18a738c01.png)
minio中要连接mongo，在哪里配置哈

**Comment by itmagus** [comment]
turms-plugin:
  minio:
    mongo:xxxx
加了一个mongo的配置，不报错了

**Comment by JamesChenX** [comment]
@itmagus I just wrote a doc on how to configure plugin settings, please take a look: https://github.com/turms-im/turms/commit/d46367c72d14d1ff3d34a6a5cf1b95c53de51b37
