### ISSUE TITLE
有些消息不想在服务器持久化，应该怎么使用

### ISSUE THREAD

**Issue by itmagus** [turms-im/turms#1197]
请问一下，比如像rasa的一些消息，不想在服务器端存储,在客户端存就可以了，应该怎么正确的使用API?

**Comment by JamesChenX** [comment]
If you only want to disable persisting rasa messages/responses to clients in MongoDB, I can add a new property to support this feature this week.

**Comment by itmagus** [comment]
好的，首先确实有您说的关于rasa的需求
另外想问一下，在传统的IM应用场景中，是否支持，根据发送消息的参数，可以选择是否存MongoDB呢？

**Comment by JamesChenX** [comment]
If you need to decide whether to store messages according to other data, and the use case you mentioned is considered common, it's accepted and I can add related properties to support.
But if the use case is not common, maybe you need to modify the code and build your own Docker images.

So how do you want to decide whether to persist messages?

**Comment by JamesChenX** [comment]
If you need to decide whether to store messages according to other data, and the use case you mentioned is considered common, it's accepted and I can add related properties to support.
But if the use case is not common, maybe you need to modify the code and build your own Docker images.

So how do you want to decide whether to persist messages?

**Comment by itmagus** [comment]
在发送消息的接口里增加参数，来决定是否，在服务器端存储本条消息？

**Comment by JamesChenX** [comment]
> 在发送消息的接口里增加参数，来决定是否，在服务器端存储本条消息？

It's okay if you want to write a plugin that calls the method and decides whether to persist messages.
And I can add a method parameter for you this week.

**Comment by itmagus** [comment]
好的，感谢

**Comment by JamesChenX** [comment]
I have added a new property `turms-plugin.rasa.instances[?].response.persist` for plugin users to decide whether to persist rasa responses.
You can check the commit for details: https://github.com/turms-im/turms/commit/f9a4c81c77538fb1abfe573b344f53f14412b2bc

Feel free to ask if you have any questions.
