### ISSUE TITLE
"im.turms.server.common.storage.redis.sharding.ConsistentHashingShardingAlgorithm"did not consider redis  expansion

### ISSUE THREAD

**Issue by xuchangbclz** [turms-im/turms#1199]
This is the client implementation,redis cannot guarantee that the node will fall on the same node after adding the node。Excuse me, is my understanding wrong?

**Comment by JamesChenX** [comment]
Your understanding is half right. Turms support a fixed number of Redis nodes or clusters, meaning:
* If you use Redis clusters, it's fine to add new nodes, but you cannot add a new cluster as the following diagram shows.
* If you don't use Redis clusters, but let turms servers connect to Redis nodes directly, it's correct that you should not add new nodes.

![image](https://user-images.githubusercontent.com/44962329/231666836-6e6629cd-9472-4a34-960c-657435ed248f.png)

**Comment by xuchangbclz** [comment]
If you use Redis clusters,in fact, the consistent hash algorithm does not work. The node to which the key is assigned is determined by the hash slot of the redis cluster

**Comment by JamesChenX** [comment]
> If you use Redis clusters,in fact, the consistent hash algorithm does not work. The node to which the key is assigned is determined by the hash slot of the redis cluster

Your understanding is wrong because they are two different things.
Turms uses the consistent hash algorithm to choose the Redis servers that users choose, and it's can be a master instead of a data node.
