### ISSUE TITLE
java.lang.IllegalArgumentException: The end date must not be before the start date

### ISSUE THREAD

**Issue by bad-pear** [turms-im/turms#1207]
hello, i just use docker-compose run this  in local windows.. this bug show me  "java.lang.IllegalArgumentException: The end date must not be before the start date" on idea terminal . not change config, just use docker-compose commond run. i show u  the detail exception:

turms-turms-service-1   | 2023-04-25 01:14:09.049 ERROR S egwdrvmk 4367011825460729077 turms-node-connection-client-io-4-1     i.t.s.a.s.d.ServiceRequestDispatcher : Caught an internal server error while handling the request: Client
Request[userId=108, deviceType=DESKTOP, clientIp=[127, 0, 0, 1], requestId=6497452130610282850, turmsRequest={request_id:1609238205128061704,query_message_attachment_infos_request:{user_ids:'*',group_ids:'*',creation_date_start:104,
creation_date_end:101,in_private_conversation:true,are_shared_by_me:false}}]
turms-turms-service-1   | java.lang.IllegalArgumentException: The end date must not be before the start date
turms-turms-service-1   |       at im.turms.server.common.infra.time.DateRange.<init>(DateRange.java:35)
turms-turms-service-1   |       at im.turms.server.common.infra.time.DateRange.of(DateRange.java:42)
turms-turms-gateway-1   | 2023-04-25 01:14:09.053  INFO G tafahprc 4367011825460729077 turms-node-connection-server-worker-4-1 : 1520441137|108|DESKTOP|1|127.0.0.1|6497452130610282850|QUERY_MESSAGE_ATTACHMENT_INFOS_REQUEST|26|2023-0
4-25 01:14:09.048|1200||68|5
turms-turms-service-1   |       at im.turms.service.domain.storage.access.servicerequest.controller.StorageServiceController.lambda$handleQueryMessageAttachmentInfosRequest$7(StorageServiceController.java:188)
turms-turms-service-1   |       at im.turms.service.access.servicerequest.dispatcher.ServiceRequestDispatcher.lambda$dispatch0$3(ServiceRequestDispatcher.java:299)
turms-turms-service-1   |       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
turms-turms-service-1   |       at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
turms-turms-service-1   |       at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
turms-turms-service-1   |       at reactor.core.publisher.Operators.complete(Operators.java:137)
turms-turms-service-1   |       at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
turms-turms-service-1   |       at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
turms-turms-service-1   |       at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)
turms-turms-gateway-1   | 2023-04-25 01:14:09.054  INFO G tafahprc 6576444488566942576 turms-node-connection-server-worker-4-1 : 716038566|107|DESKTOP|1|127.0.0.1|3014870034847501834|QUERY_MESSAGE_ATTACHMENT_INFOS_REQUEST|31|2023-04
-25 01:14:09.048|6000||76|5
turms-turms-service-1   |       at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
turms-turms-service-1   |       at reactor.core.publisher.Mono.subscribe(Mono.java:4429)
turms-turms-service-1   |       at reactor.core.publisher.Mono.subscribeWith(Mono.java:4510)
turms-turms-service-1   |       at reactor.core.publisher.Mono.subscribe(Mono.java:4272)
turms-turms-service-1   |       at im.turms.server.common.infra.cluster.service.rpc.RpcService$1.onRequestReceived(RpcService.java:220)
turms-turms-service-1   |       at im.turms.server.common.infra.cluster.service.rpc.RpcService$1.onDataReceived(RpcService.java:135)
turms-turms-service-1   |       at im.turms.server.common.infra.cluster.service.connection.ConnectionService.lambda$onMemberConnectionAdded$14(ConnectionService.java:488)
turms-turms-service-1   |       at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
turms-turms-service-1   |       at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:379)
turms-turms-service-1   |       at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
turms-turms-service-1   |       at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
turms-turms-service-1   |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
turms-turms-service-1   |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
turms-turms-service-1   |       at reactor.netty.channel.AbstractChannelMetricsHandler.channelRead(AbstractChannelMetricsHandler.java:126)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
turms-turms-service-1   |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
turms-turms-service-1   |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
turms-turms-service-1   |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
turms-turms-service-1   |       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
turms-turms-service-1   |       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
turms-turms-service-1   |       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
turms-turms-service-1   |       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
turms-turms-service-1   |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
turms-turms-service-1   |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
turms-turms-service-1   |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
turms-turms-service-1   |       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
turms-turms-service-1   |       at java.lang.Thread.run(unknown)
turms-turms-service-1   | 

i use the docker-compose commond was  $env:ENV="dev";docker compose -f docker-compose.standalone.yml up --force-recreate
this commond in project docker-compose.standalone.yml

**Comment by JamesChenX** [comment]
As the log `at im.turms.service.domain.storage.access.servicerequest.controller.StorageServiceController.lambda$handleQueryMessageAttachmentInfosRequest$7(StorageServiceController.java:188)` shows, a client passes wrong `creationDateStart` and `creationDateEnd` values.

If you are not passing these values, it's the fake clients generated by turms-gateway sending these random requests for testing purposes. 
These fake clients are enabled if you run with the `dev` profile, and you can disable them by setting `turms.gateway.fake.enabled` to `false`.

btw, It's understandable that you may think it's a bug, I will add a doc to mention this later. Thanks for reporting.
