### ISSUE TITLE
client.messageService.addMessageListener did not work as expect

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1220]
when I run dart demo and js demo, I can not see `client.messageService.addMessageListener` this function has any message callback, some thing wrong with my server deployment? I was deploy with docker-compose as you mention the quick way.

When register the listener

```
  client.messageService.addMessageListener(message => {
        appendContainer(container, `Message: Receive a message from other users or server: ${beautify(message)}`);
    });
```
expected result was when receive a message, Message: Receive a message.... will print on screen, but there is not, instead:
`message ${res.data} has been sent` is printed, so it sent successed.
<img width="915" alt="image" src="https://user-images.githubusercontent.com/54241621/236852334-941b78e1-4477-47ae-ada4-ed92fa217f25.png">

there is not any Receive a message log printed
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/54241621/236851308-fe82f76d-fa64-427f-8c10-8af0d53899a8.png">

**Comment by JamesChenX** [comment]
Thanks for reporting.
The bug has been fixed in both `develop` and `master` branches, and you can pull the latest code or the latest docker image to have a try.
