### ISSUE TITLE
confuse about friend request and user relationship

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1232]
as my understand add friend step may look like this:
1: user A send friend request to user B
2: user B reply friend request to A with accept
3: A and B now be related

below is a api call test
first when A user call   `client.userService.sendFriendRequest(b_friend_id, "add me");`
admin page show correct result
<img width="1329" alt="image" src="https://github.com/turms-im/turms/assets/54241621/e8bb9118-1665-4983-b226-7a2390f7f3af">

then when B user call  ` client.userService.replyFriendRequest(userFriendRequest.id, ResponseAction.ACCEPT, reason: "ok");`
 
error show
`597911459:2500:Cannot add a non-related user to a relationship group:null:null`

by solved this error, I can first create relation,

A user  call  `client.userService.createRelationship(b_user_id, false)`
and
B user  call  `client.userService.createRelationship(a_user_id, false)`

then  `client.userService.replyFriendRequest(userFriendRequest.id, ResponseAction.ACCEPT, reason: "ok");`

and yes, ACCEPT status can be set and  shows in admin page, but

here is problem:

When called these two createRelationship function,  A and B user are already  related and can be query out by 
call `client.userService.queryFriends()`, but at curently,  friend request are still pending, B user  don't need to call `client.userService.replyFriendRequest(userFriendRequest.id, ResponseAction.ACCEPT, reason: "ok")` to allow this action, B user became friend of A. 
expected result is: B should not be A's friend untill B  replyFriendRequest with  ACCEPT.

is it my understanding correct with createRelationship and friendRequest service?

**Comment by JamesChenX** [comment]
Thanks for reporting.
The bug has been fixed in both `develop` and `master` branches, and you can pull the latest code or docker images to have a try.
