### ISSUE TITLE
how to query groups created by user?

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1235]
scenario:
User A create some  group by call 

`client.groupService.createGroup("group name 1")`
`client.groupService.createGroup("group name 2")`
`client.groupService.createGroup("group name 2")`
these group haven't send or receive any message

User A login on a new device, need 's to pull groups
User A how to know what group created by himself?

**Comment by JamesChenX** [comment]
Dart code reference:
``` Dart
final groupInfos = await this.queryJoinedGroupInfos();
final myUserId = Int64(1);
final myOwnedGroups = groupInfos.data?.groups.where((group) => group.ownerId == myUserId);
```

But I will add some filters for `queryJoinedGroupInfos` later so that we can filter the result on the server side.
