### ISSUE TITLE
 admin page "group invitation" shows error invite id

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1236]
invite id is same as group id

<img width="1395" alt="image" src="https://github.com/turms-im/turms/assets/54241621/76b6f18c-9727-415b-96ad-fca2d656e432">

**Comment by JamesChenX** [comment]
I cannot reproduce the bug as the following image shows.
Please provide the steps to reproduce it.
![image](https://github.com/turms-im/turms/assets/44962329/ffe0a0c7-c93d-44ec-813a-9812f534e0a5)

**Comment by JamesChenX** [comment]
I cannot reproduce the bug and it works as expected as the following image shows.
Please provide the steps to reproduce it.

![image](https://github.com/turms-im/turms/assets/44962329/27c6c9e8-6043-42d9-9c35-eabedab17548)

**Comment by weishirongzhen** [comment]
I create this invitetion through dart client, not directly in admin page.
dart client call 
` client.groupService.createInvitation(groupId, inviteeId, content)`
The specific parameters are：
` client.groupService.createInvitation(5692890045645160448.toInt64(), 881.toInt64(), "invite 881");`
<img width="1400" alt="image" src="https://github.com/turms-im/turms/assets/54241621/8a69a148-e6f7-49b1-821a-11102d8b6101">

**Comment by JamesChenX** [comment]
Fixed. Thanks for reporting.
And you can pull the latest code or pull the latest docker to have a try.
