### ISSUE TITLE
can u reconsider building a WeChat group again?

### ISSUE THREAD

**Issue by bad-pear** [turms-im/turms#1245]
dalao:
         reactor is complex, and i read reactor code was difficult
         can u create a wx group for bro chat this project or chat others like padding on work

**Comment by JamesChenX** [comment]
Sorry, I have no plan to create any chat group for Turms, but you can create one and invite others if you want.
And feel free to ask if you can encounter problems with Turms after you took time to try to figure it out but can't.

Though reactor-core may seem difficult at first, you will find it easy after playing it for about 1~2 weeks.
And you can play/learn reactor-core by reading https://projectreactor.io/docs/core/release/reference/
After you take days on it, you can come back to read Turms code, and it's easy honestly, and the difficult things are always business requirements analysis.
