### ISSUE TITLE
remote debug

### ISSUE THREAD

**Issue by zuiqiangxiang** [turms-im/turms#1246]
Can you ask how to debug docker compose remotely through idea

**Comment by zuiqiangxiang** [comment]
I can't debug successfully

**Comment by JamesChenX** [comment]
You can read the doc: https://www.jetbrains.com/help/idea/run-and-debug-a-spring-boot-application-using-docker-compose.html#debug_app, the debug steps for Turms should be the same.

**Comment by zuiqiangxiang** [comment]
thanks let me try

**Comment by zuiqiangxiang** [comment]
thanks it's ok
