### ISSUE TITLE
Problem with users getting empty userSession when disconnecting websocket connection

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1251]
![image](https://github.com/turms-im/turms/assets/38731460/3441d277-13c7-44fd-b62d-bb5c810f3c50)
![1687849959905](https://github.com/turms-im/turms/assets/38731460/5ac88307-f7df-4614-b3e6-7485a56f25c9)

请教下 我觉得按道理来说时不会为空的才对。

**Comment by LaZy1162999568** [comment]
当用户成功登录后会设置usersession， 然后客户端断开连接。

**Comment by JamesChenX** [comment]
Your code seems to have been updated for months, and you better pull the latest code first.

`sessionWrapper.getUserSession()` will return null if the connection is closed or the user is already logged out.

![image](https://github.com/turms-im/turms/assets/44962329/716315f7-66ac-4828-9cc7-8299447609fb)
