### ISSUE TITLE
RpcException: 2:1201

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1254]
When starting the program using IDE or launching it with a jar file in Linux. Sometimes, the client encounters an exception while calling client.userService.login. The log is as follows：
```
Unhandled exception:
4105536280:1201:2:1201:null:null
```
turms-gateway's log：
```
2023-06-30 07:16:47.299 ERROR G ndfuuvbj 7269237358860818880 turms-gateway-tcp-worker-24-1      i.t.g.a.c.c.ClientRequestDispatcher : Failed to handle the service request: SimpleTurmsRequest[requestId=4105536280, type=QUERY_MESSAGES_REQUEST, createSessionRequest=null]
im.turms.server.common.infra.cluster.service.rpc.exception.RpcException: 2:1201
```
After restarting the turms-service and turms-gateway once or multiple times, it functions normally.

**Comment by zy2203** [comment]
And me change shutdown method like this
```
@RequiredPermission(AdminPermission.SHUTDOWN)
@PutMapping
public HttpHandlerResult<Void> shutdown() {
	context.close();
	return HttpHandlerResult.OK;
}
```
then execute Command `curl -H "Authorization:Basic dHVybXM6dHVybXM=" -X PUT http://localhost:8510/shutdown` before `kill -9 ThreadId`.
this Exception whill be fix.

**Comment by JamesChenX** [comment]
1201 means `SERVER_UNAVAILABLE`.

The server will responsed with the error status code when `im.turms.server.common.infra.healthcheck.ServerStatusManager#isActive` returns false, and it will return true when:
```java
public boolean isActive() {
    return !context.isClosing() && node.isActive() && healthCheckManager.isHealthy();
}
```
So you better check whether your CPU and memory usage is healthy.

**Comment by zy2203** [comment]
U can try starting at IED, After service and gateway runing (maybe need restart a few times), run turms-client-dart/emample.dart, will reproduce this.

**Comment by zy2203** [comment]
U try starting service and gateway in IDE (maybe need restart a few times), the run turms-client-dart/example.dart, will reproduce this problem.

**Comment by zy2203** [comment]
Sometimes login with playground.turms.im also has this problem
![图片](https://github.com/turms-im/turms/assets/54758962/ebd4d981-1f20-484b-b508-0ea91b0f58b6)

**Comment by Wujerry** [comment]
same problem

**Comment by zy2203** [comment]
I observe the logs, sometimes program startup does not trigger related listener.
![图片](https://github.com/turms-im/turms/assets/54758962/05d6083c-925e-426e-911e-710477089277)

**Comment by zy2203** [comment]
I observe the logs, sometimes program startup does not trigger related listener.
If has this log, will be right. if not have, the client login has exception 1201.
![图片](https://github.com/turms-im/turms/assets/54758962/05d6083c-925e-426e-911e-710477089277)

**Comment by JamesChenX** [comment]
@zy2203 Thanks for your information.
`2` is the code of `im.turms.server.common.infra.cluster.service.rpc.RpcErrorCode#MEMBER_NOT_FOUND`, the direct reason is just turms-gateway wants to send a request to turms-service to handle, but turms-gateway cannot find any turms-service in MongoDB (it's also used as a service registry) for the request, so it throws the code `2`.

But I review Turms code, and tried several times last few weeks, but Turms cluster works fine even if a server register and unregister back and forth, so I will dive into this problem when I am done with `turms-client-cpp` that I promise others to publish in August.

**Comment by zy2203** [comment]
@JamesChenX 
I update the code, it's working at now. This bug is fixed.

**Comment by water2060** [comment]
最新版仍旧有这个问题
![image](https://github.com/turms-im/turms/assets/76037438/a89ccbc8-46aa-4162-8de5-8de09e8ef937)
![image](https://github.com/turms-im/turms/assets/76037438/93524b15-2f2f-4678-8804-e4b30c5f2c9b)
![image](https://github.com/turms-im/turms/assets/76037438/599d2c06-6b57-4d25-8518-2216c90623e3)
启动没问题，但是提示rpc连接不上
