### ISSUE TITLE
Log Chinese display garbled code

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1258]
![图片](https://github.com/turms-im/turms/assets/54758962/101486bd-c112-47a5-b54f-f1298475c53c)

When i change code in `TurmsTemplateLayout.appendMessage`, `StringUtil.getBytes(message)` change to `StringUtil.getUtf8Bytes(message)`, It's working.
![图片](https://github.com/turms-im/turms/assets/54758962/4aae564f-7f22-4194-969b-961bfee5c943)

**Comment by JamesChenX** [comment]
It's designed in this way on purpose.

Reasons:

![image](https://github.com/turms-im/turms/assets/44962329/e1e46395-e6d5-4304-bed5-f5d8971de456)

![image](https://github.com/turms-im/turms/assets/44962329/ae62776a-ac1e-4617-bddb-a05d5c5bcbc8)
****

But Turms will support logging non-ASCII characters (e.g. Chinese) to log params in client requests for better observability in the future when we replace all `String` values with `Utf8String` values, e.g. from `String mystr` to `Utf8String mystr`.

**Comment by zy2203** [comment]
Ok, Thanks for your answer
