### ISSUE TITLE
关于redis的使用问题

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1263]
代码的配置文件中对redisTemplate自动配置进行了剔除
![image](https://github.com/turms-im/turms/assets/22829954/a08bfdee-617f-4409-a519-79284c7be01b)

1.想问一下如果我想使用redisTemplate，那么我把自动配置恢复如下，那么有什么影响？
![image](https://github.com/turms-im/turms/assets/22829954/53454d56-80e0-4c49-97c2-4dcd1e02795e)

2.r如果有影响 我需要如何进行处理？

**Comment by JamesChenX** [comment]
Turms servers implement the Redis client based on Lettuce and don't use `RedisTemplate`, which means if you remove these configurations, nothing should happen to Turms servers.

> 想问一下如果我想使用redisTemplate

You should never use `redisTemplate` for Turms servers.
