### ISSUE TITLE
logout(disconnect: false) causes error

### ISSUE THREAD

**Issue by huluwa-dev** [turms-im/turms#1271]
Hi,

Thank you for this great library.
I am currently using this lib in my project, but I met an issue.

I am using client.userService.logout function to log out, I used logou() without parameters before, it was all good.
I tried **logout(disconnect: false)** today, it produced an error, and the **error code is 301**, I would appreciate if you can help me to fix this issue. Thank you.

**Comment by JamesChenX** [comment]
Thank you for sharing your appreciation of my work.

301 means `CLIENT_SESSION_HAS_BEEN_CLOSED` (The client session has been closed when the client sends a request), and you can just ignore the error code (301) when disconnecting.

**Comment by huluwa-dev** [comment]
Thank you for the information. I will ignore this error.

But if this is normal, then it is a little wired that it prodocues error.
Typically, code should not cause error with normal use.
