### ISSUE TITLE
issue about userService.sendFriendRequest response when target declined

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1273]
Step:
1. user A send sendFriendRequest to user B.
2. user B reply with Declined.
3. user A send sendFriendRequest to user B again.  code show :2601, A friend request has already existed.

expected: I think when B  reply with Declined at second step. third step can change current request status to PENDING or else B user will not receive A's request again, user A has no chance to add B.

**Comment by JamesChenX** [comment]
Setting `turms.service.user.friend-request.allow-send-request-after-declined-or-ignored-or-expired` to `true` in turms-service should work.
