### ISSUE TITLE
请教一下Java如何调用Kotlin客户端的suspend函数？

### ISSUE THREAD

**Issue by TyCoding** [turms-im/turms#1278]
看到项目中只有基于Kotlin的Client，但Java中貌似不能直接调用 Kotlin 的 suspend 函数

**Comment by JamesChenX** [comment]
We have no plan to support Java to use `turms-client-kotlin` for two reasons:
1. Java is a really terrible language to write UI components, and Java on Android is fragmentary and has terrible support for async programming.
2. Kotlin (just like Dart, and Swift) is the modern language for most UI-based applications.

So the suggestion here is: Please use Kotlin for your new applications.

**Comment by TyCoding** [comment]
谢谢您的回答，但实际中我们的Java系统确实需要连接IM Server端接收或者推送消息，请问您一下，有比较优雅的写法吗？还是说我的Java系统必须重新实现一遍ImClient？

**Comment by JamesChenX** [comment]
If you have to use Java for your client application, I can add a Java client SDK for you.
So what platforms do you need to support? (Android, Desktop, etc), and if you need to support Android, I will set the min supported Android SDK to 24 (Android 7.0) because it supports `CompletableFuture` without introducing other libs.

**Comment by ychost** [comment]
可以通过 Mono 与 Kotline 的 Suspend 桥接

```java
/**
 * Mono 和 协程桥接，方便 Java 调用，建议用这个，这个可见兼容上下文
 */
class MonoContinuation<T>(private val sink: MonoSink<T>) : Continuation<T> {

    companion object {
        /**
         * 直接调用协程函数
         */
        @JvmStatic
        fun <T> invoke(suspendFunc: Function<Continuation<T>, *>): Mono<T> {
            try {
                return ReactiveContext.createMono x@{ sink ->
                    val cont = MonoContinuation(sink)
                    val result = suspendFunc.apply(cont)
                    // 协程未完成
                    if (result?.toString()?.uppercase()?.equals("COROUTINE_SUSPENDED") == true) {
                        return@x
                    }
                    // 协程已经完成了，那么直接返回
                    if (result is Throwable) {
                        sink.error(result)
                    } else {
                        sink.success(result as T)
                    }
                }
            } catch (e: Throwable) {
                return Mono.error(e)
            }
        }
    }

    // 可自定义与 Mono 传递的上下文
    override val context: CoroutineContext
        get() = Dispatchers.IO 

    override fun resumeWith(result: Result<T>) {
        if (result.isSuccess) {
            sink.success(result.getOrNull())
        } else {
            sink.error(result.exceptionOrNull() ?: RuntimeException("call suspend failed"))
        }
    }
}
```
