### ISSUE TITLE
后期会考虑出app客户端吗

### ISSUE THREAD

**Issue by hongsebianhua** [turms-im/turms#1279]

**Comment by JamesChenX** [comment]
Simple answer: No, and it's the space left for the community, but we will support XMPP in the future, so you can use any UI-based XMPP clients to use with Turms servers.

Detailed answer:
* Chinese: https://turms-im.github.io/docs/zh-CN/#%E5%85%B3%E4%BA%8E%E5%B8%A6%E5%85%B7%E4%BD%93%E4%B8%9A%E5%8A%A1%E5%AE%9E%E7%8E%B0%E7%9A%84demo
* English: https://turms-im.github.io/docs/#demo-with-specific-business-implementation
