### ISSUE TITLE
Multi-terminal login SessionCloseStatus code not inconsistent

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1284]
If I login an account with DeviceType.IOS on A device , then login in same account on B device also DeviceType.IOS, try multi-times, A device will receive sessionCloseStatus code's looks like randomly with connectionClosed = 300 or  disconnectedByOtherDevice = 501, I think  it better be consistent with disconnectedByOtherDevice = 501

**Comment by JamesChenX** [comment]
I have added a new property `closeTimeoutMillis` (120 seconds) to wait for clients to receive data and close sessions when time outs.
You can pull the latest code or images to have a try.
