### ISSUE TITLE
question about configuration priority

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1290]
<img width="686" alt="image" src="https://github.com/turms-im/turms/assets/54241621/5e10877a-9386-4ff4-8d9d-f53bf82137b4">

according my test, global config priority is higher than local config. but there will be some issue
ex:  if I start my server at first time and add this config like:
`turms.gateway.client-api.rate-limiting.capacity=300`  is set. this config willl write to mongodb, and be global.

when I change config to 
`turms.gateway.client-api.rate-limiting.capacity=200`  
the mongodb will keep  
`turms.gateway.client-api.rate-limiting.capacity=300`,
so, is it the only way to change capacity from 300 to 200 is modify it by directly change mongodb's value?

**Comment by JamesChenX** [comment]
> when I change config to `turms.gateway.client-api.rate-limiting.capacity=200` the mongodb will keep `turms.gateway.client-api.rate-limiting.capacity=300`, so, is it the only way to change capacity from 300 to 200 is modify it by directly change mongodb's value?

This is why they are called global properties, and they are designed to behave in this way on purpose.
And you can call `PUT cluster/settings` to update global properties: `im.turms.service.domain.cluster.access.admin.controller.SettingController#updateClusterSettings`.
