### ISSUE TITLE
关于获取用户ip的问题

### ISSUE THREAD

**Issue by LaZy1162999568** [turms-im/turms#1295]
现在的部署环境一般都是基于docker中nginx转发 或者通过cdn转发，这样就导致获取到的用户ip 就是docker的ip或者是cdn的ip 不能获取到用户的真实ip。

**Comment by JamesChenX** [comment]
This proposal is very good.
I will update the code and write a doc to support turms-gateway to get real client IP for TCP (using proxy protocol) and WebSocket (using HTTP headers) Turms clients next month.

**Comment by JamesChenX** [comment]
Supported.
For WebSocket clients, set `turms.gateway.websocket.remote-address-source.http-header-mode=optional` in turms-gateway.
For TCP clients, set `turms.gateway.tcp.remote-address-source.proxy-protocol-mode=optional` in turms-gateway.

**Comment by zy2203** [comment]
@JamesChenX 
我更新了代码，然后试过很多方案，但得到的IP都是127.0.0.1。然后通过debug和打印日志发现，在执行`HAProxyMessageReader.channelRead()`之前，就执行了下图获取`remoteAddress`。不知道是不是这个原因。
![图片](https://github.com/turms-im/turms/assets/54758962/110a18d6-3674-4606-b855-3c6770365dec)

在`HAProxyMessageReader.channelRead()`方法里，是能获取到正确IP的，如下图。
![图片](https://github.com/turms-im/turms/assets/54758962/b5f52393-3dfe-4cdf-9a97-f51d7541835b)

**Comment by JamesChenX** [comment]
@zy2203 Thanks for reporting. The bug has been fixed in the latest turms-gateway docker images and code, and you can pull them to have a try.
