### ISSUE TITLE
update admin role has error

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1301]
WriteError{code=121, message='Document failed validation'

![图片](https://github.com/turms-im/turms/assets/54758962/1c80bb23-2a55-4694-8d72-cb26cc04a2c7)
![图片](https://github.com/turms-im/turms/assets/54758962/98381255-037e-4f66-952e-52fafaa5d1f4)
![图片](https://github.com/turms-im/turms/assets/54758962/b9f030a4-7174-45cc-b02f-edc3ffea5bd5)

**Comment by JamesChenX** [comment]
Thanks for reporting. The bug has been fixed on both `develop` and `master` branches, and you can pull the latest docker images to have a try.
