### ISSUE TITLE
use-sequence-id-for-XXX-conversation casue send message error Could not get a long value from the invalid response

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1302]
when config
```
use-sequence-id-for-group-conversation: true
use-sequence-id-for-private-conversation: true
```
send message will cause "code 201 Could not get a long value from the invalid response"
<img width="1035" alt="image" src="https://github.com/turms-im/turms/assets/54241621/a542be0d-7c20-4fd9-a0d6-9b92ffac7b7a">
<img width="836" alt="image" src="https://github.com/turms-im/turms/assets/54241621/67719f9a-8938-40f8-893e-74d6a944b7b0">

**Comment by JamesChenX** [comment]
You need to ensure the local property `turms.service.redis.sequence-id.uri-list[0]=redis://<ip>:<port>` has been set when you run turms-service servers and try again.

I will add a warning log later to tell developers that they may forget to set the Redis server settings if they set `use-sequence-id-xxx` to `true`.

**Comment by weishirongzhen** [comment]
after add property to mongo
<img width="722" alt="image" src="https://github.com/turms-im/turms/assets/54241621/d0c8f317-4875-49e8-b4c0-df8f1f7dbaac">
and restart service, try send message , still same error

**Comment by weishirongzhen** [comment]
when I debug, I found redisClientManager is always null

<img width="1068" alt="image" src="https://github.com/turms-im/turms/assets/54241621/af4291ee-f60a-4490-b668-8b88d78af35b">

**Comment by weishirongzhen** [comment]
issue solved, after delete all old data, and re-deploy server
