### ISSUE TITLE
why get useSequenceIdForxxxxConversation config  from diff config way

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1303]
In im.turms.service.storage.redis.RedisConfig.java  useSequenceIdForxxxxConversation from localProperties
<img width="902" alt="image" src="https://github.com/turms-im/turms/assets/54241621/0bb395a2-2596-4b1e-b127-b2c08c28ee46">
In im.turms.service.domain.message.service.MessageService.java  useSequenceIdForxxxxConversation from globalProperties
<img width="1084" alt="image" src="https://github.com/turms-im/turms/assets/54241621/ef739a5b-bbdf-4cb4-a69a-7d8c17705d09">

**Comment by JamesChenX** [comment]
We prefer to design business-related properties to be mutable and global while server properties (e.g. RPC port) to be immutable and local based on the common use cases.
But some immutable properties can be mutable in the future, it's just a balance between development cost and user requirements.
