### ISSUE TITLE
访问6510端口，页面空白

### ISSUE THREAD

**Issue by xs-abscd** [turms-im/turms#1306]
按照docker方式安装本地turms集群，执行docker compose -f docker-compose.standalone.yml up --force-recreate后，运行效果与docker状态如下：
![image](https://github.com/turms-im/turms/assets/42344319/f52a846e-1fa8-471c-94bd-33acf4f158be)

![image](https://github.com/turms-im/turms/assets/42344319/3ebeb6b8-3ba7-451b-81c6-6c492ec9e07b)

浏览器访问空白：
![image](https://github.com/turms-im/turms/assets/42344319/349d12be-dcff-4ad8-8d61-5a2e59b64824)

**Comment by JamesChenX** [comment]
http://playground.turms.im:6510/ always runs with the latest `turms-admin` docker image, and it works fine on Chrome and Firefox, and your dockers are healthy so you can use the above browsers to have a try.
