### ISSUE TITLE
用turms-client-dart登录时,怎么捕捉密码错误

### ISSUE THREAD

**Issue by reubencharles842** [turms-im/turms#1308]
我现在的代码是这样的
 final value =
        await client.userService.login(Int64(1), password: "1234");
 logger.d('value.code= ${value.code}');
当密码错误时会提示
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 3471902968:2011:The user's login information does not match:null:null
不会打印value.code

**Comment by JamesChenX** [comment]
Yes. We design clients (all clients work the same way) behavior differently for request success cases and failure cases to avoid our users misusing failure cases as success cases.

In your use case, you can use the following code to catch:
```dart
try {
    final successResponse = await client.userService.login(Int64(1), password: "1234");
    logger.d('success response code: ${successResponse.code}');
}  on ResponseException catch (e) {
    logger.d('failure response code: ${e.code}');
}  on Exception catch (e) {
    logger.d('unexpected error: $e');
}
```
