### ISSUE TITLE
flutter 调用queryFriends时报错

### ISSUE THREAD

**Issue by reubencharles842** [turms-im/turms#1311]
调用client.userService .queryFriends()时
返回错误
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: null:300:null:null:null

**Comment by reubencharles1007** [comment]
已经确保登录了,其他的接口也可以调用.
现在又返回Unhandled Exception: 3170965071:1201:3:1201:null:null

**Comment by JamesChenX** [comment]
Ensure you have set up both turms-gateway and turms-service in the same cluster, or you will get the error.
