### ISSUE TITLE
Turms Admin  更新用户信息失败

### ISSUE THREAD

**Issue by reubencharles1007** [turms-im/turms#1314]
<img width="1475" alt="image" src="https://github.com/turms-im/turms/assets/144759313/ef51dd2c-6a16-4368-a215-324276b632d2">

**Comment by JamesChenX** [comment]
Thanks for reporting.
Solutions:
1. You can just remove your input value in the `User ID` field so that it won't try to update the user ID, and it should work.
2. Or you can pull the latest docker image for `turms-admin` or code, and they should work.
