### ISSUE TITLE
updateGroupMemberInfo not working (Some group type properties don't work)

### ISSUE THREAD

**Issue by zy2203** [turms-im/turms#1322]
The group type setting like this. But the group member still can not update name in GroupMember.
![图片](https://github.com/turms-im/turms/assets/54758962/b1903a2e-3220-4a29-b633-aaca7a6d19a9)

**Comment by JamesChenX** [comment]
Thanks for reporting.
We will fix related bugs in 2 days and will notify you when we publish bug fixes.
