### ISSUE TITLE
Use latest code deploy server meet error

### ISSUE THREAD

**Issue by hustlemickey** [turms-im/turms#1353]
I'm fellow build doc, build success, and prepare redis, mongo, minio done.
when I exec run.sh -f

```
[0.805s][info][jfr,startup] Recording 1 scheduled to start in 1 m.
[0.805s][info][jfr,startup]
[0.805s][info][jfr,startup] Use jcmd 203655 JFR.dump name=1 to copy recording data to file.
VM settings:
    Max. Heap Size (Estimated): 2.49G
    Using VM: OpenJDK 64-Bit Server VM

Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher

```
turms-service directory
<img width="807" alt="image" src="https://github.com/turms-im/turms/assets/24805329/7a3abf37-df03-478b-a545-d661f03851a0">

**Comment by JamesChenX** [comment]
Hi @hustlemickey, did you build the `turms-service` with the `artifact-fat-jar` maven profile? If not, please build the jar with the `artifact-fat-jar` profile, and run `run.sh -f` again to have a try.

Command example: `mvn clean package -am -B -DskipUTs -DskipITs -P artifact-fat-jar -pl turms-service`

## Background
Turms servers are built as **thin jars** that contain no dependencies, so if you run `run.sh -f` (`-f` means `run as a fat jar`) with these thin jars, The `Could not find or load main class org.springframework.boot.loader.JarLauncher` error will occur.

**Comment by hustlemickey** [comment]
yes, I build with 
`mvn clean package -am -B -DskipUTs -DskipITs -P artifact-fat-jar -pl turms-gateway --no-transfer-progress`
and 
`mvn clean package -am -B -DskipUTs -DskipITs -P artifact-fat-jar -pl turms-service --no-transfer-progress`

still same error

**Comment by hustlemickey** [comment]
turms-service out put jar is 60M, is it correct size with fat jar?
<img width="504" alt="image" src="https://github.com/turms-im/turms/assets/24805329/1e2d3582-ef5b-4a2c-aa79-98dea4d49b2e">

**Comment by JamesChenX** [comment]
Yes. the jar ends with `-exec.jar` is the fat jar that you should run to run with `run.sh -f`.

**Comment by hustlemickey** [comment]
but still error, any possible reason?
<img width="761" alt="image" src="https://github.com/turms-im/turms/assets/24805329/ffb66b08-6c9d-4ea6-9e1e-e067bdfcc4cb">

**Comment by hustlemickey** [comment]
I found the reason in run.sh


` MAIN_CLASS="org.springframework.boot.loader.JarLauncher"
`

should be 

`MAIN_CLASS="org.springframework.boot.loader.launch.JarLauncher"
`

**Comment by JamesChenX** [comment]
Thanks for pointing it out. I will update it later after full testing.

btw, you can use the code under the `master` branch to build and run for stability. The `develop` branch is used for development purposes, so it is not as stable as `master`.

**Comment by hustlemickey** [comment]
thanks
