### ISSUE TITLE
unknown ip address show in admin api

### ISSUE THREAD

**Issue by hustlemickey** [turms-im/turms#1354]
when open admin page, check dashboard, admin api looks like random, it should be same as server ip: 192.168.31.207
<img width="1616" alt="image" src="https://github.com/turms-im/turms/assets/24805329/8d6d12b6-c3c2-4b88-8bca-8b30c95f8aa5">

**Comment by JamesChenX** [comment]
The feature is `IP Advertising`. In simple words, you can specify the strategy and host for IP advertising.
e.g.
![image](https://github.com/turms-im/turms/assets/44962329/c468d492-4b8d-4b24-9846-72437cd57815)
