### ISSUE TITLE
New verison of minio cause upload from client 403

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1359]
using new version of minio_20231209181751， when client upload image will cause [403] s3.PostPolicyBucket in minio trace, roll back to minio_20230718174940 everything is ok.

**Comment by JamesChenX** [comment]
We updated the lifecycle hooks recently (methods like `start()` and `stop`) to support more advanced features.
Solutions:
* You can upgrade turms servers to the latest images so that you can use the latest Minio plugin.
* Or you can keep using the old turms servers while using the old minio plugin.

btw, no breaking changes for other things, so upgrading anything should be easy.

**Comment by weishirongzhen** [comment]
Build latest code and tested on newest version minio_20231220010002.0.0_amd64.deb still 403

**Comment by JamesChenX** [comment]
I run some tests with the last Turms servers, turms-minio-plugin, and the real minio servers:
* `minio/minio:RELEASE.2023-12-23T07-19-11Z` (The latest version of minio currently): Tests failed. Rerun twice, but all failed.
* `minio/minio:RELEASE.2023-12-20T01-00-02Z` (The version you encountered 403): Tests failed. Rerun twice, but all failed.
* `minio/minio:RELEASE.2023-12-14T18-51-57Z` (The version we used in the docker compose file): Tests passed.
* `minio/minio:RELEASE.2023-07-18T17-49-40Z` (The version you work fine with): Tests passed.

So if you want to upgrade your minio server, you can upgrade to `minio/minio:RELEASE.2023-12-14T18-51-57Z` which passed all tests and is safe to use.
I am busy with other potential bugs and features, and no effort to dive into why turms-minio-plugin doesn't work for the lastest minio currently.

---

btw, the server dependencies used in the docker compose file are all tested, meaning these versions are stable/safe to use with. So if you prefer stability, you can use the version mentioned in docker compose file, or just keep using old versions (We won't introduce usage breaking changes of MongoDB, Redis, MinIO etc).

**Comment by JamesChenX** [comment]
After testing, Turms is safe to run with the latest image `minio/minio:RELEASE.2024-03-21T23-13-43Z`, which is the default version in `docker-compose.standalone.yml`, you can upgrade if you want.
