### ISSUE TITLE
update typing status only work in privateconversaiton

### ISSUE THREAD

**Issue by hustlemickey** [turms-im/turms#1363]
When called `conversationService.updatePrivateConversationTypingStatus`, target user can receive a notification
but  when `conversationService.updateGroupConversationTypingStatus` called no notification receive on target device

**Comment by JamesChenX** [comment]
Hi @hustlemickey, thanks for reporting.
The bug has been fixed on both `develop` and `master` branches, and you can pull the latest image that contains the bugfix to run.
