### ISSUE TITLE
How to remove related user  from relationGroup but keep private relationship?

### ISSUE THREAD

**Issue by hustlemickey** [turms-im/turms#1365]
I created a relationshipGroup name "Family" and assume relatedGroup id or index is 123456, then

I can move user in relation group by call `moveRelatedUserToGroup(userAId,123456)`,
now userAId in relationGroup 123456, but how to remove this user from 123456 relationGroup?

if i call `deleteRelationship(userAid,deleteGroupIndex:123456)`, it will not only remove user from relationGroup but also remove private relationship with userA, I just want remove userA from relationGroup, but not entire relationship

**Comment by JamesChenX** [comment]
Turms servers ignore some request params, and I will take time to fix it tomorrow, will @ you once done.

**Comment by hustlemickey** [comment]
works!
