### ISSUE TITLE
TurmsService start fail

### ISSUE THREAD

**Issue by kf53916** [turms-im/turms#1366]
MongoCollectionInitializer init  error
![Uploading 截屏2023-12-30 17.33.17.png…]()

**Comment by JamesChenX** [comment]
Hi @kf53916 , your screenshot image URL is broken.
Please post a new image or just post the text logs.

**Comment by kf53916** [comment]
Description:

Parameter 1 of constructor in im.turms.service.storage.mongo.MongoCollectionInitializer required a single bean, but 5 were found:
	- adminMongoClient: defined by method 'adminMongoClient' in class path resource [im/turms/service/storage/mongo/MongoConfig.class]
	- userMongoClient: defined by method 'userMongoClient' in class path resource [im/turms/service/storage/mongo/MongoConfig.class]
	- groupMongoClient: defined by method 'groupMongoClient' in class path resource [im/turms/service/storage/mongo/MongoConfig.class]
	- conversationMongoClient: defined by method 'conversationMongoClient' in class path resource [im/turms/service/storage/mongo/MongoConfig.class]
	- messageMongoClient: defined by method 'messageMongoClient' in class path resource [im/turms/service/storage/mongo/MongoConfig.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Comment by JamesChenX** [comment]
We had many system tests passing without encountering this problem for years, and the code in `MongoCollectionInitializer` is fine.

So it seems that you have changed the code of Turms servers or the version of dependencies, you can roll back your changes, or fix them in your local version.

**Comment by kf53916** [comment]
After pulling the code again, it can start normally. Thank you！
Is there a communication group?

**Comment by JamesChenX** [comment]
There is no chat group for Turms, and we prefer GitHub issues because it can track all kinds of discussions and help others.

Feel free to ask questions if you don't find an answer for your questions in Turms documentation, and I check Turms issues almost every day.

**Comment by kf53916** [comment]
OK，Thank you！

**Comment by kf53916** [comment]
Some ports in the code are hard coded?

**Comment by kf53916** [comment]
How to set different message types when sending messages, such as text messages, image messages, voice messages, etc

**Comment by JamesChenX** [comment]
@kf53916 Please open a new issue if you have different questions.
And please be patient to take the time to read and search in Turms documentation. If you don't find an answer in Turms documentation, you can open a new issue to ask.

For you question,
English: https://turms-im.github.io/docs/server/module/identity-access-management.html
Chinese: https://turms-im.github.io/docs/zh-CN/server/module/identity-access-management.html
