### ISSUE TITLE
about ldap

### ISSUE THREAD

**Issue by 907080752** [turms-im/turms#1371]
你好，请问turms可以怎么与现有ldap做集成

**Comment by JamesChenX** [comment]
Hi @907080752, I will add the feature of LDAP for user authentication and authorization and related documentation this week.
Once I am done, I will @you.

**Comment by JamesChenX** [comment]
Done.
Doc for LDAP-based authentication: 
English: https://turms-im.github.io/docs/server/module/identity-access-management.html#_5-ldap-based-authentication
Chinese: https://turms-im.github.io/docs/zh-CN/server/module/identity-access-management.html#_5-%E5%9F%BA%E4%BA%8Eldap%E8%AE%A4%E8%AF%81
