### ISSUE TITLE
admin login error

### ISSUE THREAD

**Issue by Piscen** [turms-im/turms#1374]
刚搭建了一个测试后台，刚开始的时候管理后台能正常登录，过了一段时间之后登录就出现401错误了。重启服务之后又正常了，过了一段时间又报错了，想知道这个是有啥机制，登录也需要鉴权么，还是有啥地方需要配置的

**Comment by Piscen** [comment]
登录失败: (401, 1300) Unauthenticated

**Comment by JamesChenX** [comment]
> 想知道这个是有啥机制

In simple words, turms servers just compare the password passed from the HTTP request with the one on MongoDB, if they match, the request is authenticated. If not, unauthenticated.

Admin authentication code: 
1. `im.turms.server.common.access.admin.web.HttpRequestAuthenticator#authenticate`
2. `im.turms.server.common.domain.admin.service.BaseAdminService#authenticate`

> 登录也需要鉴权么

In fact, there is no dedicated admin API for `login`.
The login logic on the login dialog in `turms-admin` just sends a head HTTP request to `/admins` to check if the account and password match, so no something like JWT, or session ID will be generated.

> 过了一段时间之后登录就出现401错误了。重启服务之后又正常了，过了一段时间又报错了

I never encountered this problem, and the authentication code should be fine after code review.
And you can upgrade your servers to the latest images or code, and try again.
If you still encounter the problem, you can set some breakpoints in the methods mentioned above to check why your request are unauthenticated.

**Comment by Piscen** [comment]
断点了一下BaseAdminService#authenticate，正常登录的时候accountToAdmin是有管理员账号数据的，失败的时候这个accountToAdmin空了，看代码是去查了一下账号又添加到这个map里了，但是adminRepository.findById(account)返回的依旧是空，这个是啥意思，数据库被自动清空了？
   public Mono<Admin> queryAdmin(@NotNull String account) {
        try {
            Validator.notNull(account, "account");
        } catch (ResponseException e) {
            return Mono.error(e);
        }
        AdminInfo adminInfo = accountToAdmin.get(account);
        if (adminInfo == null) {
            return adminRepository.findById(account)
                    .doOnNext(admin -> accountToAdmin.put(account, new AdminInfo(admin, null)));
        }
        return Mono.just(adminInfo.getAdmin());
    }

**Comment by JamesChenX** [comment]
If `adminRepository.findById(account)` returns a Mono that emits nothing (e.g. `Mono.empty()`), it means there is no such admin account matching the `account` parameter as `_id` in MongoDB. In other words, the admin doesn't exist.

Turms servers do NOT delete admin accounts automatically unless you set `turms.service.fake.clear-all-collections-before-faking` to `true`, then turms-service will drop all data in MongoDB **when the server starts up every time**.
The property is only set to true by default to reset mock data when you running the servers in the `test` profile.

You can check if it is true by searching `Start dropping databases` in your logs when the server is starting but has not started.

**Comment by Piscen** [comment]
clear-all-collections-before-faking这个设置确实为true，不过这个是每次重启才会奇效吧，我现在是服务启动之后放着不动，过个把小时就登录报错了。测试用的阿里云抢占式实例，这个有关系么

**Comment by JamesChenX** [comment]
You can run turms servers in the `prod` or `dev` profile so that your data won't be removed by servers automatically. The `test` profile with the true `clear-all-collections-before-faking` is used to run tests (e.g. integration tests, system tests) and will remove collections every time for testing.

> 测试用的阿里云抢占式实例，这个有关系么

Alicloud Spot/Preemptive instances will remove data whenever the instance stops, so it may related to the problem, and it depends on how you deploy turms servers and MongoDB.

**Comment by Piscen** [comment]
感谢解答，问题已解决。应该是服务器环境问题，手动建了一台实例之后可以正常跑了。
