### ISSUE TITLE
How to accpet/refuse group invitation, when receive a group invitation

### ISSUE THREAD

**Issue by weishirongzhen** [turms-im/turms#1377]
group config set below
<img width="1723" alt="image" src="https://github.com/turms-im/turms/assets/54241621/fdbb8fd4-8045-45cb-8776-5b64a6bc2401">
group owner send a invitation by call `createInvitation()` and send to a user1, user1 can call  `queryInvitations` to get this invitation, how user1 can accept or refuse this invitation?
can't find api to call 

and same issue about joinRequest, if a group Join Strategy is JOIN_REQUEST, when user1 send JOIN_REQUEST, how group owner or manager can approve user's JOIN_REQUEST?

**Comment by JamesChenX** [comment]
Working on this. I will @you once the code and doc are done.

**Comment by JamesChenX** [comment]
Hi @weishirongzhen, a big update has been committed. You can use `groupService.replyJoinRequest` or `groupService.replyInvitation` to accept/deny them.
For API details, I have written thousands of lines of comments for client service API, you can pull the latest code of turms clients to have a look.

---
**IMPORTANT**: If you want to use the latest Turms servers or Turms clients (just use the latest code in the `develop` or `master` branch, or images), you need to use the latest Turms servers, clients, and plugins consistently. In other words, it will make you trouble if you use the latest Turms servers, but use old Turms clients.
