### ISSUE TITLE
where is  proto file for all project?

### ISSUE THREAD

**Issue by zhaieryuan** [turms-im/turms#1397]
请问trums工程内定义消息的proto文件在哪儿呀？急需！！！

**Comment by JamesChenX** [comment]
https://github.com/turms-im/proto

**Comment by zhaieryuan** [comment]
Thank you very much for your reply.

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/24/2024 17:54 |
| To | turms-im/turms ***@***.***> |
| Cc | zhaieryuan ***@***.***>,
Author ***@***.***> |
| Subject | Re: [turms-im/turms] where is proto file for all project? (Issue #1397) |

https://github.com/turms-im/proto
