### ISSUE TITLE
detailed tutorial

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1400]
1.Can you provide a detailed tutorial on building a Tums im cluster? It's the most perfect kind
2."docker compose -f docker-compose.standalone.yml --profile monitoring up"："Mini" and "rasa" were not started,How to run it
3.How to build a "mongo" cluster with multiple nodes using "turns im"

**Comment by JamesChenX** [comment]
Please read:
English: https://turms-im.github.io/docs/server/deployment/getting-started.html
Chinese: https://turms-im.github.io/docs/zh-CN/server/deployment/getting-started.html
