### ISSUE TITLE
queryFriendRequests mapping error problem

### ISSUE THREAD

**Issue by darkSystemCode** [turms-im/turms#1405]
1. JS端请求queryFriendRequests 接口获取好友请求数据，但是服务器端映射到了DELETE_RELATIONSHIP_REQUEST，这是我配置的问题还是系统bug？
![image](https://github.com/turms-im/turms/assets/50562636/a78b2436-3350-45ab-9048-cb2d5d862823)
![image](https://github.com/turms-im/turms/assets/50562636/d6c838cc-88f1-4530-aeef-a68e508ade26)
最后的数值是205，刚好对应上枚举DELETE_RELATIONSHIP_REQUEST
@JamesChenX

**Comment by JamesChenX** [comment]
Please upgrade both your servers and clients to the latest version, and it will work.

**Comment by darkSystemCode** [comment]
pull master分支服务端和客户端是最新的？

**Comment by darkSystemCode** [comment]
已checkout develop分支，问题依然存在
