### ISSUE TITLE
DictionaryParser#parseExtendedWord as the turms document can npe

### ISSUE THREAD

**Issue by zhaieryuan** [turms-im/turms#1408]
![image](https://github.com/turms-im/turms/assets/127175435/cfbc1345-d025-4365-8ff9-d72a77e76ecc)

上述所有列中，除了word列必须存在之外，其他所有列都可以不存在.

![image](https://github.com/turms-im/turms/assets/127175435/fd8fc99a-083e-4302-a3d8-1db8e756c448)

this line code need fix

**Comment by zhaieryuan** [comment]
![image](https://github.com/turms-im/turms/assets/127175435/750536d8-0047-4d64-9520-196e1d4abf6f)

and also the document for examle is wrong ！！

**Comment by zhaieryuan** [comment]
![image](https://github.com/turms-im/turms/assets/127175435/ebc4a472-30a4-4f13-be2a-4630e8e3f74d)

**Comment by JamesChenX** [comment]
The code is quite simple, and no NPE will occur.

![image](https://github.com/turms-im/turms/assets/44962329/857b93d7-5ef2-4191-a8d8-d5f59a347e1e)
