### ISSUE TITLE
Required array length 2147483639 + 9 is too large

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1411]
In the "test" module of code execution, "Docker Compose" cannot be started, and the following exception is prompted. The Windows system I am using, Docker Composite version v2.19.1, Docker version 24.0.2, build cb74dfc

How to solve this problem and execute the test code smoothly?

![image](https://github.com/turms-im/turms/assets/76037438/ab81f436-0857-4a20-a4ae-6cafad3e6e5e)

![image](https://github.com/turms-im/turms/assets/76037438/205fbbf0-783e-4e73-9291-26701d5b4011)

[描述.txt](https://github.com/turms-im/turms/files/14521077/default.txt)

**Comment by water2060** [comment]
All other codes and configurations were pulled from GitHub without any changes made

**Comment by JamesChenX** [comment]
You can the commands used in the following GitHub Actions to run your tests to check if they can work (We have used these commands to run tests for years):
1. https://github.com/turms-im/turms/blob/develop/.github/workflows/test-turms-gateway.yml
2. https://github.com/turms-im/turms/blob/develop/.github/workflows/test-turms-service.yml

---

Regarding your question, I haven't encountered the problem you mentioned.
As the logs said `This archive contains unclosed entries`, you can set breakpoints according to the stack traces to check which archive is corrupted and try to correct it. If you can debug, everything should be easy to fix.
