### ISSUE TITLE
production environment

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1415]
How to configure domain names and certificates when deploying the Tums im project in a formal environment? Do I need to use nginx reverse proxy? I'm used to using the testing environment and don't know how to handle it. Seeking answers

**Comment by JamesChenX** [comment]
In simple words, deploying Turms servers is the same as deploying any other WebSocket and TCP servers (e.g. NginX, Tomcat, NodeJS server, etc), so there are many ways to deploy, and it's really up to you.

You can read the following docs:
English:
1. https://turms-im.github.io/docs/design/architecture.html#the-general-process-of-client-accessing-server
2. https://turms-im.github.io/docs/server/deployment/getting-started.html#build-and-start

Chinese:
1. https://turms-im.github.io/docs/zh-CN/design/architecture.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AE%BF%E9%97%AE%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E4%B8%80%E8%88%AC%E6%B5%81%E7%A8%8B
2. https://turms-im.github.io/docs/zh-CN/server/deployment/getting-started.html#build-and-start

Once you understand them, you can deploy the cluster as you want.
---


> How to configure domain names and certificates when deploying the Tums im project in a formal environment? Do I need to use nginx reverse proxy?

Please read the docs mentioned above.
By the way, if you want to configure certificates on turms-gateway, you can configure the following SSL properties:
![image](https://github.com/turms-im/turms/assets/44962329/d9df8979-e067-4d33-842b-3e83bb7d1ee8)
