### ISSUE TITLE
Query messages The records[] field error decode !!

### ISSUE THREAD

**Issue by zhaieryuan** [turms-im/turms#1419]
我这里按照作者调整后的，释放 byteBuffer ,问题仍然没有生效，这里仅记录一下。

![image](https://github.com/turms-im/turms/assets/127175435/dafa7f8c-ab25-4844-ae76-253370f8035e)

![image](https://github.com/turms-im/turms/assets/127175435/985f8387-14ca-4831-bc85-8187cffdda4d)

**Comment by zhanchen18** [comment]
你的问题解决了吗?我这边跟你一样的问题

**Comment by JamesChenX** [comment]
@zhanchen18 Thanks for reporting. I haved published a bugfix for one cause that can lead to this problem.
You can pull the latest docker images for servers for the fix.

If the problem still occurs, please share all log files so that I can pinpoint it.

**Comment by zhaieryuan** [comment]
👏👏

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/01/2025 20:36 |
| To | turms-im/turms ***@***.***> |
| Cc | eryuan ***@***.***>,
State ***@***.***> |
| Subject | Re: [turms-im/turms] Query messages The records[] field error decode !! (Issue #1419) |

@zhanchen18 Thanks for reporting. I haved published a bugfix for one cause that can lead to this problem.
You can pull the latest docker images for servers for the fix.

If the problem still occurs, please share all log files so that I can pinpoint it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

JamesChenX left a comment (turms-im/turms#1419)

@zhanchen18 Thanks for reporting. I haved published a bugfix for one cause that can lead to this problem.
You can pull the latest docker images for servers for the fix.

If the problem still occurs, please share all log files so that I can pinpoint it.
