### ISSUE TITLE
prod.yaml

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1421]
The yaml file under the resources section of "turns service" only has:
Application.yaml
Application demo.yaml
Application dev.yaml
Application test.yaml

1. What does "prod" configured in application.yaml mean? Do I need to create an application prod. yaml file myself?
2. "Docker composite - f Docker composite. standalone. yml -- profile storage up - d" did not write a configuration similar to "EVN=dev". What is the default configuration for starting? What if I write "EVN=prod" but there is no application prod. yaml in the default image?

**Comment by lamazhenyuan** [comment]
maybe application.yaml=application_prod.yaml

**Comment by JamesChenX** [comment]
Please read the doc:
English: https://turms-im.github.io/docs/server/deployment/config.html#configuration-categories
Chinese: https://turms-im.github.io/docs/zh-CN/server/deployment/config.html#%E9%85%8D%E7%BD%AE%E5%88%86%E7%B1%BB
