### ISSUE TITLE
ppocr_keys_v1.txt Download address invalid

### ISSUE THREAD

**Issue by q843492358** [turms-im/turms#1443]
https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/dygraph/ppocr/utils/ppocr_keys_v1.txt 404 Not Found

This address downloads the same file? 
https://github.com/PaddlePaddle/PaddleOCR/blob/main/ppocr/utils/ppocr_keys_v1.txt

somebody help me.

**Comment by JamesChenX** [comment]
Thanks for reporting.
I have updated the URL to `https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/v2.7.5/ppocr/utils/ppocr_keys_v1.txt`. You can pull the latest code from the `develop` or `master` branch to have a try.
