### ISSUE TITLE
How does the client end the current session history message?

### ISSUE THREAD

**Issue by changehu** [turms-im/turms#1446]
Now two friends chat, the client end through `thequeryMessage` call, where the parameter fromIds is [`user AId`, `user BId`], can only query all the chat history of `user AId (current login user)`, and can not query A and B chat history according to the conditions, is the need for server level implementation of this function?

**Comment by JamesChenX** [comment]
By default, a user can only find the messages sent by the other in a private conversation.
If you want a user can find all messages sent by themselves and the other in a private conversation, you need to set `turms.service.message.use-conversation-id=true` for `turms-service`.

For details:
English: https://turms-im.github.io/docs/feature/message.html#precautions-when-querying-session-messages
Chinese: https://turms-im.github.io/docs/zh-CN/feature/message.html#%E6%9F%A5%E8%AF%A2%E4%BC%9A%E8%AF%9D%E6%B6%88%E6%81%AF%E6%97%B6%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
