### ISSUE TITLE
message search filter

### ISSUE THREAD

**Issue by PENGYANG13122010305** [turms-im/turms#1449]
The Reference ID exists when the message is created, but it does not exist in the filtering condition of the message list. If I want to establish the relationship between the message id in the business and message in the turms, should I establish the relationship through this Id? You can use the Reference ID to query and operate messages in follow-up service queries

**Comment by JamesChenX** [comment]
If I understand correctly, the term `Reference` you mentioned refers to `Quote Message`？
If so, you can implement these features by saving the quoted message IDs in the text or records in `Message`s, and it's totally up to the developers. For example, some developers display videos, music, etc based on the Markdown text.

The `im.turms.service.domain.message.po.Message#referenceId` field stores the relationship between the source message and the new message. For example, if you copy a message based on an existing message, the `reference ID` of the new message is the ID of the existing message.
So the `reference ID` in Turms isn't what you want.

> You can use the Reference ID to query and operate messages in follow-up service queries

What are your business requirements that need to find messages based on quoted messages?
If your use cases are reasonable, I can support the feature in one month when I am not that busy.

**Comment by PENGYANG13122010305** [comment]
Oh, I see. What I wanted was for the reference ID to be used as a key to associate with the business object, so that the object in the business can be associated with the message in the turms. So combined with the specific business of the message query or other operations, now it seems that I understand wrong. So how do I connect message to objects in my development business? Now I want to associate a user form when sending group messages at the service management side, and realize the associated query of messages through this form id. Is there any idea to realize it?

**Comment by JamesChenX** [comment]
If you want to make a relationship between the messages generated by Turms and any data in your system:
1. You can create a message first no matter via `messageService.sendMessage` on the client side, or sending an admin HTTP request to `POST /messages`, and you will get the message ID
2. Then you can store the message ID with the ID of your data in your database, and it's up to you how to design and implement the workflow.
