### ISSUE TITLE
master分支代码插入数据好像有点儿问题

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1465]
<img width="783" alt="image" src="https://github.com/turms-im/turms/assets/22829954/7b4ab0a9-986b-46f2-9871-6b8de345d610">
groupMember表，以前老数据插入uid在前，gid在后，现在新数据插入gid在前，uid在后，后面执行根据key查询数据，新数据可以查询出来，老数据查询不出来了
写入的时候，如何不改变写入时key的bson的顺序？

**Comment by JamesChenX** [comment]
## Background

This is an expected breaking change that happened in `im.turms.server.common.storage.mongo.entity.MongoEntityFactory#parse` in 2022-11, which ensures the document field order is in alphabetical order to ensure serializing document fields in a consistent order.

## Solution

It's quite easy to migrate data to follow the new schema.

Run the following aggregation:
```
db.orders.aggregate([
  // Stage 1: Change the order of fields in "_id"
  {
    $set:
    {
      "_id": {
        "gid": "$_id.uid",
        "uid": "$_id.gid"
    }
  },
  // Stage 2: Copy data to a new collection
  {
    $out:
    {
      db: 'turms_dev', // change to your database
      coll: 'groupMember_v2'
    }
  }
])
```
![image](https://github.com/turms-im/turms/assets/44962329/9dbd81fb-a4cc-4acf-937b-89a33c79364e)

And then drop your `groupMember` collection, and rename `groupMember_v2` to `groupMember`.
When you start `turms-service`, it will create indexes for `groupMembers` automatically.


btw, Turms is stable currently, and only status codes will have breaking changes (e.g. names change).
