### ISSUE TITLE
自定义组件位置

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1466]
### 问题的背景：
我的turms-service的启动文件的配置如下：
[turms-server.md](https://github.com/turms-im/turms/files/15496108/turms-server.md)
我将redis、mongoDB、minio都装在与turms-service的另一台服务器。

### 我发现的问题是：
turms-service在minio插件在的情况下，需要在本地连接mongoDB。本地连接不上mongoDB会报错，导致minio初始化失败。
**初始化失败的提示如下：**
[失败.txt](https://github.com/turms-im/turms/files/15496165/default.txt)
在本地通过master分支最新的docker-compose.standalone.yml启动mongodb-config、mongodb-router、mongodb-shard、mongodb-setup后，就可以正常初始化minio。（_在本地启动的mongoDB的表甚至都不需要初始化_）
**初始化成功的提示如下：**
[成功.txt](https://github.com/turms-im/turms/files/15496235/default.txt)

**Comment by JamesChenX** [comment]
> turms-service在minio插件在的情况下，需要在本地连接mongoDB

turms-service always needs to connect to the MongoDB server no matter you use `turms-plugin-minio` or not.

> 本地连接不上mongoDB会报错，导致minio初始化失败

That is expected. If turms-service fails to connect to the MongoDB server, it should also fail `turms-plugin-minio`. The design principle is `fail fast`.

---
From the logs `Connection refused: getsockopt: localhost/[0:0:0:0:0:0:0:1]:27017`, turms-service failed to connect to the MongoDB server at `localhost/[0:0:0:0:0:0:0:1]:27017`.
Just configuring a connectable MongoDB address for turms-service. Turms servers have nothing special with networking.

**Comment by water2060** [comment]
1.不不不，你看一下[turms-server.md](https://github.com/turms-im/turms/files/15496108/turms-server.md)文件的配置，我是给配了mongoDB的地址的，并且可以连接成功的（IM聊天的功能都可以使用）。
2.在初始化minio之前，它会在本地用localhost去找mongoDB。我本地跑的turms-service，mongoDB在其它服务器，所以就报错了。我实在找不到哪里会去默认使用localhost去连接mongoDB的

**Comment by JamesChenX** [comment]
If you want to configure the MongoDB server for `turms-plugin-minio`, you need to add a setting like `turms-plugin.minio.mongo.uri=mongodb://your-host:your-port/your-db`, or it will connect to `mongodb://localhost:27017/turms` by default.

I will add this missing part in the docs later.
