### ISSUE TITLE
聊天室turms-service对外提供http接口如何设置超时时间？

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1472]
<img width="1188" alt="image" src="https://github.com/turms-im/turms/assets/22829954/984cde57-cc47-41f0-9532-56a088162389">
我这样进行设置没有效果呢

**Comment by wangqingchengsg** [comment]
对外提供的http接口，怀疑没有设置超时时间，导致系统的fd一直增加

**Comment by JamesChenX** [comment]
The latest server images and code on both `develop` and `master` now provide the following properties that you can use to configure timeouts:
* `turms.service.admin-api.http.request-read-timeout-millis`: The read timeout on the connection when it is waiting for an HTTP request to be fully read. Once the timeout is reached, the connection will be closed.
* `turms.service.admin-api.http.idle-timeout-millis`: The idle timeout on the connection when it is waiting for an HTTP request to come. Once the timeout is reached, the connection will be closed.
* `turms.service.admin-api.http.connect-read-timeout-millis`: The connect timeout.
