### ISSUE TITLE
业务交互

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1473]
在 turms-im 的 Issues 这里提了好多问题了，也感谢作者能够一一回复。
------------------------------------------------------------------------------------------
我当前的问题是：### 我的业务系统如何与IM系统更好的做交互。
我的业务系统上面有些需求，如获取当前账号有哪些好友、系统管理给用户发系统消息等操作。我找到了turms-admin的 api 接口文档，但是我没有找到
![image](https://github.com/turms-im/turms/assets/76037438/96d221fc-cb8b-4fbc-90a1-5648280c3d53)
这个具体的登录接口，获取到_authorization_的值，导致一直提示
![image](https://github.com/turms-im/turms/assets/76037438/40333d67-883c-4b34-87c4-853ba9e208f5)

**或者业务系统与IM应该怎么更好的做交互？希望作者能够指点一二**

**Comment by JamesChenX** [comment]
> 但是我没有找到这个具体的登录接口

Turms server doesn't have a login API in fact, so there is no something like a JWT token cookie, etc.
When you click the "Login" button in turms-admin, it just sends a `HEAD /admins` request to Turms servers, and the server will respond `OK` if the `Authorization` header of the HTTP request provides a correct username and password following the `Basic` authentication schema.
Then, turms-admin will provide all the following requests with the username and password.

> 业务系统与IM应该怎么更好的做交互

admin HTTP APIs are designed for developers' backend servers to call, so using these APIs should be enough.
If you need some new features, you can create new tickets.

**Comment by water2060** [comment]
我想问的本质是接口请求头上的
Authorization:Basic dHVybXM6dHVybXM=
的值怎么获取？因为确实没有什么登录接口，并且当 单击 turms-admin 中的“登录”按钮时，我看不到输入账号密码后，通过调用哪个接口获取到了Authorization的值，

**Comment by water2060** [comment]
从网页上获取到的Authorization：Basic dHVybXM6dHVybXM= 值，只要账号密码不变，这个值永远就不会变。也不会过期？

**Comment by JamesChenX** [comment]
> 接口请求头上的`Authorization:Basic dHVybXM6dHVybXM=`的值怎么获取？

Generated by `'Basic ' + base64(username + ":" + password)`. It is basic HTTP knowledge, and you can google it.

> 只要账号密码不变，这个值永远就不会变。也不会过期？

Yes.

**Comment by water2060** [comment]
我明白了
