### ISSUE TITLE
turms-service的进程 fd一直增加，一天就到了4万，socket大量未关闭  目前同时在线人数最多2000

### ISSUE THREAD

**Issue by wangqingchengsg** [turms-im/turms#1474]
<img width="766" alt="image" src="https://github.com/turms-im/turms/assets/22829954/96a86f53-a43a-43c2-bf73-93b554fe880a">

1.turms-servic对外提供了几个http接口，并且这些http接口的流量较大

**Comment by JamesChenX** [comment]
Duplicate: https://github.com/turms-im/turms/issues/1474
