### ISSUE TITLE
Question：ack设计的问题

### ISSUE THREAD

**Issue by markity** [turms-im/turms#1482]
文档中 设计-》状态感知-》消息确认机制中 提到了 “Turms的消息确认机制并不需要Turms服务端的参与”。

如果某个会话的最后一条消息推送丢失了，后续很长时间此群没有发送新消息（也就无法让客户端检查到gap触发拉取），这个时候是否很长时间都没法让客户端展示最后一条消息？

**Comment by JamesChenX** [comment]
> 如果某个会话的最后一条消息推送丢失了

1. If it happens because the nodes cannot connect to each other. In this case, many functions may be in trouble, not just "cannot receive new messages".
2. If the servers work fine, and you know how TCP works, you can know the answer.
