### ISSUE TITLE
怎么拓展业务信息，如群组标签等等

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1488]
你好，有个问题想请教一下，如果我的应用中需要用户、群、会话这些对象有一些拓展属性。
是我单独存储再用userId、GroupId、conversationId关联吗？有没有一个extra字段来存储相关信息？
我通过queryUserProfiles获得用户基本信息后还需要请求业务应用接口补全拓展信息？

**Comment by JamesChenX** [comment]
> 如果我的应用中需要用户、群、会话这些对象有一些拓展属性。

Could you list the **exact** "extra" properties you need?
I can add these properties in entities stored in MongoDB and pass them to clients for your cases if they are common.

If some properties you need are not common, please list your use cases for these properties so I can design a workflow for you.

> 有没有一个extra字段来存储相关信息？

No. We always try not to introduce something like `map<string, string> extra` to avoid users misusing them.

**Comment by lovemianhuatang** [comment]
用户
用户可以拥有多个标签比如：【同事、活跃、可爱】
用户可以有：邮箱、办公地点等属性

群组属性
标记：VIP、欠费、所属公司ID等

会话属性
在会话列表上显示这个会话的相关状态
私人会话：显示标签等
群组会话：显示相关的标记

不确定我是否描述明白

**Comment by lovemianhuatang** [comment]
> No. We always try not to introduce something like map<string, string> extra to avoid users misusing them.

如果有这3个对象有 map<string, string> extra 这个属性。
我就能在业务系统中通过SDK或者ADMIN API来设置用户、群组、会话的extra，
然后在SDK的用户、群组、会话 查询接口中获取到这些extra

**Comment by JamesChenX** [comment]
I see your point. These are reasonable business requirements, and I will support them once I finish refactoring the legacy admin APIs (I am working on this currently).
I will also add some properties for you to customize the extra properties (e.g. support restricting the field type, value validation, etc), and the feature will be delivered around 2024/07/14.

Once done, I will @ you, and comment with a brief tutorial on how to use these new properties.

**Comment by lovemianhuatang** [comment]
我正在寻找一个能够支持我们应用使用的IM项目。比起其他的IM项目，turms真是一个非常棒项目。
extra这个特性对我是否能选择使用turms来进行我们应用的二开很重要，希望能够尽快支持，非常感谢。

还有一个问题请教，请问ConversationSettings和UserSettings的作用是什么？我没有找到相关的文档说明

**Comment by JamesChenX** [comment]
> 我没有找到相关的文档说明

I usually write a doc for new features once they are finished, but the features are supported in servers, I haven't added the APIs in Turms clients to CRUD them so there is no doc for it currently.
I will add the client APIs for it when I finish the features you just requested, and the doc will come later after these APIs are delivered.

btw, if you see a feature in code, but cannot find a doc or client APIs for it, which usually means the feature isn't public for Turms users, you MAY or MAY not use these preview features.

> ConversationSettings和UserSettings的作用是什么

They are used for Turms clients to store arbitrary settings for conversations and users. For example, if you want to store the preferred language on the client side, you may store a `lang` field.

And you can customize turms-service to only allow clients to store specified settings, e.g.:
![image](https://github.com/turms-im/turms/assets/44962329/81b82cd2-3789-4ba3-ba04-278f0f7c5892)

btw, Turms stores `UserSettings` from `User` documents in MongoDB on purpose, which is an efficient storage design for most IM use cases.

**Comment by lovemianhuatang** [comment]
如果还有一个GroupSettings的话，似乎能够间接实现我上面的特性，当做extra来用，但这似乎不太符合turms设计。

比如：ConversationSettings增加burnAfter来支持某个会话的阅后即焚效果。
比如：ConversationSettings增加flags标记数组，VIP，关联的公司ID等，让这个会话支持自定义属性？

同时在ConversationService.queryPrivateConversations或者ConversationService.queryGroupConversations中返回这些会话的ConversationSettings。User和Group类似。

让Settings即做配置也做属性
