### ISSUE TITLE
recallMessage()没有更新旧消息的RECALL_DATE

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1492]
recallMessage()没有更新旧消息的RECALL_DATE

**Comment by JamesChenX** [comment]
Please read https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way first if you want people to help you.

**Comment by JamesChenX** [comment]
Thanks for reporting the bug.
I have fixed it in both the `develop` and `master` branches and pushed the latest images, and you can pull the latest code and images now.
