### ISSUE TITLE
关于private-conversation的sequenceId的疑问

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1496]
我开启了
use-sequence-id-for-group-conversation=true
use-sequence-id-for-private-conversation=true

在private-conversation中的sequenceId是targetId用户为key自增吗？
目前：
user1 -> user2;  sequenceId=1,2,3
user3 -> user2;  sequenceId=4,5,6

期望：
user1 -> user2;  sequenceId=1,2,3
user3 -> user2;  sequenceId=1,2,3

<img width="883" alt="image" src="https://github.com/turms-im/turms/assets/41498415/4aefd001-14b1-4721-87fb-5907e85bd678">

**Comment by JamesChenX** [comment]
Thanks for reporting. Your expectation is correct, and I will fix the bug this weekend.

**Comment by JamesChenX** [comment]
I have fixed it in both the `develop` and `master` branches and pushed the latest images, and you can pull the latest code and images now.
