### ISSUE TITLE
多端登录如何生效？

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1497]
turms.gateway.simultaneous-login.strategy: allow_one_device_of_each_device_type_online

```
Step 1：
client.userService.login({
        userId: 1,
        password: '123',
        deviceType: 'DESKTOP'
    });

Step 2：
client.userService.login({
        userId: 1,
        password: '123',
        deviceType: 'ANDROID'
    });
```

<img width="1427" alt="image" src="https://github.com/turms-im/turms/assets/41498415/45ee6d55-65c1-46d3-9de3-9be661dcb099">
<img width="831" alt="image" src="https://github.com/turms-im/turms/assets/41498415/d5e4cb0a-cf58-4ac2-a8c6-36c8f781bc62">
<img width="1129" alt="image" src="https://github.com/turms-im/turms/assets/41498415/9859a4ad-3fee-463d-8c48-bfb989bda1a0">

请问多端登录怎么生效？

**Comment by JamesChenX** [comment]
Turms servers have both global properties and local properties (for details, read the doc), and `turms.gateway.simultaneous-login.strategy` is a global mutable property, which means turms-gateway will use the value set in MongoDB, and you can update the property by:
1. You can just delete the `SharedClusterProperties` collection in MongoDB to delete global settings, and restart your turms-gateway, which will sync its local settings to create the default global settings if there are no global settings in MongoDB.
2. Or find the `SharedClusterProperties` in MongoDB, and update `turms.gateway.simultaneous-login.strategy` to an enum value that you want, and the running turms-gateway servers will detect the changes, and apply them to use different strategies.
3. Or you can call the admin API `PUT /cluster/settings` to update cluster settings, read the swagger doc for details.

**Comment by lovemianhuatang** [comment]
配置有效，多谢。
