### ISSUE TITLE
updateStatusIfPending 会设置responseDate字段的值到mongo吗？

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1501]
请问好友申请ACCEPT时，不设置responseDate吗？

<img width="1026" alt="image" src="https://github.com/turms-im/turms/assets/41498415/f1cbc74b-5e83-48dc-a646-36a4f4aa75df">

<img width="1049" alt="image" src="https://github.com/turms-im/turms/assets/41498415/6019c4f9-fd47-4af1-91b8-fe91bddbd1b6">

**Comment by JamesChenX** [comment]
Thanks for reporting the bug.
I have fixed it in both the `develop` and `master` branches and pushed the latest images, and you can pull the latest code and images now.
