### ISSUE TITLE
CollectionUtil.isImmutable(Iterable<?> iterable)  不可变判断

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1507]
在这些地方都会返回EmptyList, EmptySet, EmptyMap 实例，但这些实例是不可变的，所以会报异常。

<img width="1109" alt="image" src="https://github.com/turms-im/turms/assets/41498415/1a27a272-15e8-4dea-b899-6b783a356389">

可以通过增加IMMUTABLE_EMPTY_INSTANCE判断来修复
<img width="1290" alt="image" src="https://github.com/turms-im/turms/assets/41498415/e3666b52-75e8-4bfd-9f9c-11578b0cd58d">

**Comment by JamesChenX** [comment]
Thanks for reporting the bug.
I have fixed it in both the `develop` and `master` branches and pushed the latest images, and you can pull the latest code and images now.
