### ISSUE TITLE
更换设备对获取离线数据的影响

### ISSUE THREAD

**Issue by water2060** [turms-im/turms#1530]
https://github.com/turms-im/turms/issues/1512
https://github.com/turms-im/turms/issues/1515
大佬，这两篇 issue 我都看了，关于离线数据的问题，我还有个疑惑：
用户离线后，用新的设备登录。这时离线数据获取怎么办？ 如果获取全部的聊天记录，感觉对硬件的性能消耗大；如果只获取未读的消息，新设备里面没有聊天记录，不会出现消息 id 冲突，这个就很难判断获取哪些消息就够了

**Comment by JamesChenX** [comment]
Duplicate.
The answer is here: https://github.com/turms-im/turms/issues/1210
