### ISSUE TITLE
When it starts, nothing is output and it stops all of a sudden ？

### ISSUE THREAD

**Issue by WUZHUHE38** [turms-im/turms#1539]
/
![QQ截图20240729194354](https://github.com/user-attachments/assets/1361fe3a-2775-4139-91a2-2292300305c7)
IDEA 2024
windwos 10
JDK 21
maven 4.0.0
When starting up, the log stops without outputting anything.

**Comment by JamesChenX** [comment]
Set `turms.logging.console.enabled=true` to enable console logging.
