### ISSUE TITLE
CREATE_GROUP_JOIN_REQUEST_REQUEST 疑问

### ISSUE THREAD

**Issue by lovemianhuatang** [turms-im/turms#1542]
这里的三目运算是不是写反了?还是我理解错了？
<img width="885" alt="image" src="https://github.com/user-attachments/assets/f560a86b-9935-4b95-91d4-ca74e4e4ebf2">

**Comment by lovemianhuatang** [comment]
还有这里是否需要改为joinRequest.getRequesterId()？
<img width="821" alt="image" src="https://github.com/user-attachments/assets/44fbfba0-9ab2-4abe-8726-668fd563c4bc">

**Comment by JamesChenX** [comment]
Good catch! Thanks for pointing them out!
Could you please consider creating a pull request for this bug fix? Please feel free to reach out if you have any questions or need guidance.

> 还有这里是否需要改为joinRequest.getRequesterId()？

Yes.

**Comment by JamesChenX** [comment]
The bugfix has been merged into the `develop` and `master` branches, and the latest docker images contain the bugfix.
