### ISSUE TITLE
turms gateway cluster

### ISSUE THREAD

**Issue by zhaieryuan** [turms-im/turms#1550]
How does turms gateway cluster work? Has the author considered it？
1、目前gateway 只能在单节点负责处理 service
2、gateway 启动两个实例，在nginx映射域名的情况下，gateway 怎样选主，怎样做集群的容灾
3、gateway 集群模式下，链接中断，服务会话的session是否还可以保持？

请教一下老哥的涉及思路，不胜感谢。

**Comment by JamesChenX** [comment]
> How does turms gateway cluster work? 

You can read https://turms-im.github.io/docs/design/architecture.html#the-general-process-of-client-accessing-server for details.

> Has the author considered it？

Turms servers are designed to work in a cluster in the first place, and I think no other open-source IM solutions have the scalability comparable to Turms.

> 1、目前gateway 只能在单节点负责处理 service

You can deploy as many turms-gateway and turms-service servers as you want, and the turms-gateway server will choose any healthy turms-service to send requests to them to handle automatically.

> gateway 启动两个实例，在nginx映射域名的情况下，gateway 怎样选主

There is no need to choose a leader from turms-gateway servers. Like most web servers, they are stateless, and the client can choose any webserver to handle their requests, and there is no need to choose a leader.

If you use Nginx as the load balancer, you can reference the following Nginx config (Note that we should use Nginx to proxy on the TCP level, not the HTTP level):
```nginx
stream {
        # List of upstream turms-gateway WebSocket servers
        upstream stream_gateway_ws {
                hash $remote_addr consistent;

                # The addresses of turms-gateway WebSocket servers
                server 192.168.0.100:10510 fail_timeout=10s max_fails=20;
                server 192.168.0.101:10510 fail_timeout=10s max_fails=20;
        }

        # List of upstream turms-gateway TCP servers
        upstream stream_gateway_tcp {
                hash $remote_addr consistent;

                # The addresses of turms-gateway TCP servers
                server 192.168.0.100:11510 fail_timeout=10s max_fails=20;
                server 192.168.0.101:11510 fail_timeout=10s max_fails=20;
        }

        # For WebSocket connections to turms-gateway
        server {
                listen 10510; # the port to listen on this server
                proxy_pass stream_gateway_ws; # forward traffic to this upstream group
                proxy_timeout 3m;
                proxy_connect_timeout 15s;
        }

        # For TCP connections to turms-gateway
        server {
                listen 11510; # the port to listen on this server
                proxy_pass stream_gateway_tcp; # forward traffic to this upstream group
                proxy_timeout 3m;
                proxy_connect_timeout 15s;
        }
}
```

For Nginx health checks, you can read https://www.f5.com/company/blog/nginx/active-or-passive-health-checks-which-is-right-for-you for details.

> 怎样做集群的容灾

You can try to shut down any turms-gateway and turms-service servers forcedly or gracefully for testing, turms servers are smart. e.g., If a server is shut down gracefully, the server will clear all data related to it in Redis and MongoDB automatically on shutdown, so there is no dirty data. If a server is shut down forcedly, it doesn't have the chance to clear data in Redis and MongoDB, so there will be dirty data in Redis or MongoDB, but turms servers are smart, and will choose other healthy servers to handle requests, and clear dirty data stored in MongoDB and Redis automatically after a timeout.

So you just need to ensure to restart the server (if the machine crashes) and restart the turms-gateway/turms-service again (e.g. use `restart: unless-stopped` for services in the docker compose config), and everything should work fine.

For turms clients, you can reference the following to let the client log in again if the connection is closed for any reason:

```kotlin
turmsClient.userService.addOnOfflineListener { sessionCloseInfo ->
    if (setOf(
            # The session close reasons that you want the client to log in again if encounters.
            HEARTBEAT_TIMEOUT,
            LOGIN_TIMEOUT,
            SERVER_ERROR,
            SERVER_CLOSED,
            SERVER_UNAVAILABLE,
            CONNECTION_CLOSED,
            UNKNOWN_ERROR
        ).contains(sessionCloseInfo.closeStatus)
    ) {
        turmsClient.userService.login(...)
    }
}
```

> gateway 集群模式下，链接中断，服务会话的session是否还可以保持？

If a logged-in client loses the connection to the turms-gateway server, or fails to send the heartbeat requests in a specified time (2 minutes by default), the session will be considered `offline` by turms-gateway, and turms-gateway will close the established session.

To reconnect to the turms-gateway, you can reference the above code for clients.

**Comment by zhaieryuan** [comment]
Thank for your help。
