### ISSUE TITLE
求助：拉取镜像启动的时候提示7510端口被占用

### ISSUE THREAD

**Issue by SixGod9** [turms-im/turms#1551]
# Pull and run images
docker run -p 6510:6510 ghcr.io/turms-im/turms-admin
docker run -p 7510:7510 -p 8510:8510 ghcr.io/turms-im/turms-service
docker run --ulimit nofile=102400:102400 -p 7510:7510 -p 9510:9510 -p 10510:10510 -p 11510:11510 -p 12510:12510 ghcr.io/turms-im/turms-gateway

turms-service 这个命令里面，已经占用了7510端口。turms-gateway又执行一次占用7510端口。
启动turms-gateway镜像的时候，就会提示端口被占用。
如何解决呢？
-------------------------------------------------------

**Comment by JamesChenX** [comment]
Use:
```bash
docker run -p 6510:6510 ghcr.io/turms-im/turms-admin
docker run -p 7510:7510 -p 8510:8510 ghcr.io/turms-im/turms-service
docker run --ulimit nofile=102400:102400 -p 7610:7610 -p 9510:9510 -p 10510:10510 -p 11510:11510 ghcr.io/turms-im/turms-gateway
```

It is recommended to use `docker-compose.standalone.yml` like `docker compose -f docker-compose.standalone.yml up` as you can configure it conveniently in it.
