### ISSUE TITLE
Can I use string as the type of ID? Or use MongoDB's ObjectId as the type?

### ISSUE THREAD

**Issue by MrWangGang** [turms-im/turms#1559]
Can I use string as the type of ID? Or use MongoDB's ObjectId as the type?

**Comment by MrWangGang** [comment]
@JamesChenX

**Comment by JamesChenX** [comment]
We use `int64/long` as the ID type for less storage usage and better performance (e.g. query by IDs).
If you need a custom ID of any type, you can fork turms and add a new field like `customId` according to your requirements.

And it's a bad practice to use a meaningful ID, which will bring more and more problems as a project grows.
