### ISSUE TITLE
最新的项目有问题，配置缺失和不生效

### ISSUE THREAD

**Issue by 66pig** [turms-im/turms#1563]
想设置这个session.enable-authentication: false，但是项目中没有这个配置，如果增加上的话，gateway就无法启动。
另一个，我重新创建数据库，并设置好turms.service.message.use-conversation-id=true后启动项目，并无法查询到自己发送的消息

**Comment by zhanchen18** [comment]
> 设置好turms.service.message.use-conversation-id=true后启动项目，并无法查询到自己发送的消息

这个问题你解决了吗？
