### ISSUE TITLE
预计文档会什么时候完善？

### ISSUE THREAD

**Issue by supengxu** [turms-im/turms#157]
对项目感兴趣很久了，想研究项目，就是不知道文档时候完善

**Comment by JamesChenX** [comment]
主要是1月15号至2月底这段时间，会一直更新各类文档。
因为我这边一直计划是等turms-admin（为turms服务端定制的管理系统）发布了，就把主要精力花在写各类文档上，否则精力太散。而turms-admin已于今晚（1月4日）发布了，因此能安心写文档了。

如果你现在对turms的数据统计、业务模型、权限控制与集群配置比较感兴趣，可以直接拉去turms-admin（https://github.com/turms-im/turms-admin）仓库代码，用UI直观且快速地感受这些功能板块。
（特别补充：如果你希望turms服务端能自动生成简单的mock数据，则可以将在turms项目的src/main/java/im/turms/turms/compiler/CompilerOptions.java文件里，将：
public static final String env = "@env@";
改为：public static final String env = "DEV";
再次启动turms服务端时，它会在启动时，自动mock基础测试数据，以方便您在turms-admin中测试。

最后感谢你的关注。

**Comment by supengxu** [comment]
嗯嗯，现在大四学生，看你在知乎的 [文章](https://www.zhihu.com/question/32095220) 收获很大，如果有时间的话，也希望你到时候也可以更一下知乎的文章，或者开个专栏。

**Comment by JamesChenX** [comment]
我很早就退知乎，主要上面抖机灵的太多，干活太少了，文章的格局也都太受限了。
不过还是说一下我对个人技术栈进阶（主要是互联网应用方向的技术栈）的一点想法吧。正好很久没写东西了。

网上大部分的文章、课程与书籍都太流于表面了，搞得技术天花板很低，眼界太窄，不少行内人员以为学完这些东西就“全能”了（当然，按部就班的上班够用了）。
但如果自己对产品精益求精，就会发现很多实实在在的东西还是不会做，而且也在网上学不到。就以turms的“部署简易性”为例，turms初稿架构设计中有用到etcd、redis等组件，但在之后的架构稿中就把这些都移除掉了。为什么turms能判断出，能够在架构中去掉它俩（当然去不去掉，有利有弊），具体又是怎么做到的。就这方面设计能力，是从市面上所有的文章（除了我最早在知乎写的）与课程都是学不到的（不过能间接地学到）。

到底是拼
1. 根本驱动力是自身对技术的热爱与眼界。比如turms能移除redis的最直接原因就是 turms参考redis的虚拟槽设计，把这概念引入turms集群当中。这是网上直接学不到的。
2. 架构设计能力。非常推荐《一线架构师实践指南》这本书，通俗易懂，简单实用。就算不做架构设计，对提高眼界也很有帮助。
3. 从无到有、踏实做出一个真正项目的坚持。行内最不缺的就是PPT工程师，一个比一个能吹，但能做出东西的少之又少。只有自己真正实践过，才能知道自己的不足。

以上只是本人对个人互联网应用技术栈进阶的一点看法。共勉，加油。

**Comment by taoyonggang** [comment]
分布式一致性这部分应该用etcd的
