### ISSUE TITLE
why is in id, not in targetId

### ISSUE THREAD

**Issue by lineCode** [turms-im/turms#1576]
https://github.com/turms-im/turms/blob/c84a02567fd74c2e10bb7b19d2201f36d5170baa/turms-service/src/main/java/im/turms/service/domain/conversation/repository/ConversationSettingsRepository.java#L80

**Comment by JamesChenX** [comment]
Thanks for reporting this bug! The latest docker images and code of turms servers contain the bugfix, and you can pull them currently.
