### ISSUE TITLE
miss cond when dateRange is null

### ISSUE THREAD

**Issue by lineCode** [turms-im/turms#1579]
https://github.com/turms-im/turms/blob/c293fecedf66ffba4758f9de0f90160b3278ca7f/turms-service/src/main/java/im/turms/service/domain/group/repository/GroupRepository.java#L104

miss cond when dateRange is null, will count all groups

**Comment by JamesChenX** [comment]
Thanks for reporting this bug! The latest docker images and code of turms servers contain the bugfix, and you can pull them currently.
