### ISSUE TITLE
updateRelationshipGroup 

### ISSUE THREAD

**Issue by lineCode** [turms-im/turms#1586]
https://github.com/turms-im/turms/blob/ff69c24ccf7b3ddd02e30907870d6320c89cce19/turms-service/src/main/java/im/turms/service/domain/user/access/servicerequest/controller/UserRelationshipServiceController.java#L576

updateRelationshipGroup is not effect on this branch

**Comment by JamesChenX** [comment]
Thanks for reporting this bug! The latest docker images and code of turms servers contain the bugfix, and you can pull them currently.
