### ISSUE TITLE
Online status heartbeat renewal

### ISSUE THREAD

**Issue by wang-qijia** [turms-im/turms#1592]
"Thank you for contributing to this high-quality chat project. I encountered an issue during my review and would like to discuss it.

In the HeartbeatManager#updateOnlineUsersTtl method, the estimatedUserCountToRefreshPerInterval parameter does not seem to limit the Redis user count as expected. Is this a known issue in the current implementation, or is it intended behavior?"

**Comment by JamesChenX** [comment]
`estimatedUserCountToRefreshPerInterval` is used to estimate the size when processing (e.g. allocate memory buffers), and there is no need to limit the `estimatedUserCountToRefreshPerInterval` as even if you have 100_000 online users, the script can run `update_users_ttl.lua` in 1 second.
