### ISSUE TITLE
针对于Cassandra、MongoDb、Redis选型是如何考虑的？

### ISSUE THREAD

**Issue by supengxu** [turms-im/turms#194]
就IM的场景针对消息存储上，上面的三种数据库该如何选择？

**Comment by JamesChenX** [comment]
简单说说。
首先，Redis和其他两个数据库不是一个维度的。Redis可以用来做在线用户状态管理，这个我之前有在知乎聊过。只是turms追求部署简易性，自主实现了哈希虚拟槽算法，不需要再“大费周章”搞个redis集群做在线用户状态管理。
Cassandra作为列式数据库，相比mongo做查询确实有优势（turms有大量query操作都只是单列查询），而mongo得把整个record加载进内存，再project所需字段。但Cassandra不支持事务，因此基本直接判死刑。
mongo早期不支持事务，但后来支持了（这也是为什么我在知乎写不用mongo的原因，因为当时它不支持跨文档事务，我写完那文章几个月后，它就支持了）。
速度不行、内存不够就加集群，数据进行垂直/水平拆分，这些都是有很多成熟方案的了。但数据库不支持事务，并且还没有其他”看家本领“，怎么跟其他数据库玩。
而且benchmark这东西就跟买手机一样，同一价位的手机，别管各个厂家怎么吹，就都那个样。很多数据库的高性能表现是以数据安全性为代价的。大家都是现代数据库，设计不会落后到哪去，取舍问题罢了，因此这块其实没那么在意。
技术选型最怕看两篇文章就以偏概全，很多东西文章里是不会说的。还是靠多摸索。
