### ISSUE TITLE
Support switching database cluster between MongoDB and CockroachDB (via R2DBC)

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#239]
In fact, turms used CockroachDB as the database of turms servers at the stage of internal development, but CockroachDB is abandoned due to the JDBC driver (blocking calls) in Java.

Although R2DBC project is still experimental, it's worthwhile to take it with CockroachDB as an alternative database of turms servers in the future.

**Comment by awoods187** [comment]
Hi PM at Cockroach Labs here. What problems are you having with CockroachDB and the JDBC driver? We don't expect there to be any problems here so we'd love to know what problems you are running into.

**Comment by JamesChenX** [comment]
Thanks for your assistance and the good job Cockroach Labs has done, which makes my life much more easier compared to the traditional architecture for DB servers (relational database servers + middleware).

**Expected:** 
(This is not the reason we didn't use CockroachDB, but may help make the ecosystem of CockroachDB better and more appealing)
CockroachDB better have some examples or posts that demonstrate how to connect to CockroachDB servers via the non-blocking driver https://github.com/r2dbc/r2dbc-postgresql (which supported by Spring framework) and its functionality and stability for Java developers.

**Actual:**
we didn't use CockroachDB + JDBC because of JDBC has a worse performance and R2DBC is a good alternative but not mature enough to push us to integrate it with CockroachDB for now, and there is no a post demonstrating whether CockroachDB works well via R2DBC (but we will try to integrate them into this project with the developentment of R2DBC).

**Motivation:**
For this project, CockroachDB + JDBC driver is hard to accept.
Because this project always try to improve throughputs of user requests as more as possible, while JDBC is a blocking driver which makes the calls to DB blocking and reduces throughputs significantly (bucket effect), and that's why we don't adopt JDBC.

And, CockroachDB doesn't has its own driver (BTW MongoDB has its own non-blocking drivers, this's why we are using it now though its use cases, in fact, are not that suitable for this project as CockroachDB does) and supports the drivers for Postgres, but most of them are blocking drivers (backed by JDBC) and I know there are two existing projects (r2dbc-postgresql, vertx-sql-client) supporting non-blocking drivers for Java developers which can be used for CockroachDB, but R2DBC is not ready for production for now but grows fast (that's why I tagged this issue "experimental").

If CockroachDB has its own example for connecting DB via R2DBC, it is much appreciating and exciting for Java developers.
And I will try to integrate CockroachDB via R2DBC into this project later.

**Comment by awoods187** [comment]
@rafi curious what you think about the above?
