### ISSUE TITLE
Cache outbound messages

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#306]

**Comment by supengxu** [comment]
你好，请教下这里缓存出站消息的目的是啥啊。

**Comment by JamesChenX** [comment]
像是“消息发送人修改或撤回已发送的消息”、”消息接收人ACK刚收到的消息“这样的操作在一个消息刚被发送出去后是非常频繁的，而用户进行这些操作在服务端处需要进行权限判断，以免出现”用户A明明不是消息的接收人，却操作该消息“的情况。因此通过小量的本地内存（刚发出去的消息缓存），在进行上述权限判断的时候，只用从本地缓存中拉去消息数据进行比对权限，无需再CALL数据库去拉消息数据，以此减少大量的数据库调用操作，对性能的提升还是比较可观的。

当然后期还会继续优化下，像是缓存中的消息正文或是附带的二进制数据目前都无需用到，并且也比较占内存，之后可以去掉，减少不必要的内存占用。以及针对群组消息的缓存优化。一步步来。
