### ISSUE TITLE
请教quick start部署之后是怎么测试呢 

### ISSUE THREAD

**Issue by KevinHe666** [turms-im/turms#36]
请教quick start部署之后是怎么测试呢  文档又没有详细描述呢 还是只有服务端 客户端需要自己搭测试

**Comment by JamesChenX** [comment]
感谢反馈。
首先把Turms服务端换成20号发布的（就改了一个turms的jar包），因为这个版本会自动在启动时mock测试数据。https://github.com/turms-im/turms/releases/download/v0.8.0-beta.20191020/v0.8.0-beta.20191020.zip
然后可以去到https://github.com/turms-im/turms-client-js项目，并clone这个项目。下载完后，运行demo文件夹下的demo.html（保证它运行在web环境。以http(s)协议开头，而不是file协议。用intellij idea直接打开这demo.html的话，它默认就会运行在web环境），它就能自动登陆到Turms服务端，并执行创建新Group和拉取离线消息的操作。
这部分你可以通过F12，打开浏览器console来看。

在实际项目开发中，可以引入
https://github.com/turms-im/turms-client-js/blob/develop/dist/turms-client-min.js来调用所有的TurmsClient类下面的对象与方法（用法可以参考demo，使用起来真的很简单。而且turms-client-js.d.ts会给IDE代码提示）

当然，现在前端工程化，很少直接用<script></script>引用js，所以turms-client-js之后会作为前端的dependency发布到公共仓库，方便开发者调用。

P.S. 这个周日（27号）会给出turms-client-js的使用文档，感谢关注。

**Comment by KevinHe666** [comment]
谢谢 我去研究下
