### ISSUE TITLE
请问红包和转账功能什么时候会有呢

### ISSUE THREAD

**Issue by KevinHe666** [turms-im/turms#42]
请问大佬红包和转账功能会后续开发么

**Comment by JamesChenX** [comment]
（以下图片均来自：https://dev.yunxin.163.com/docs/product/IM即时通讯/SDK开发集成/Android开发集成/红包）
很具有功能设计启发性的一个问题。

首先，turms服务器/客户端不会添加红包或转账功能，当然不排除后期以plugin形式引入的可能。当然更大可能是开发者看了不引入的原因，就明白为什么这类操作，不必（也不应该）由Turms来做。
红包的实现和CDN引入实现很像，都是由：开发者的客户端（注意：这里说的客户端，不是Turms客户端，而就是您产品的客户端）向您的服务器请求“资源访问许可token”，如果客户端获得了这个许可，那客户端就拿着这个许可token去请求第三方服务商提供服务（如：红包服务器的提供商或是CDN服务的提供商）。**这些功能本身不需要Turms服务端的参与，就可以实现的。而且，也没必要让Turms参与其中**。

**您真正的需求可能是：如何配合第三方红包SDK，让用户发送“红包”，和其他用户接受“红包”**
首先，很多开发者很容易混淆两个过程。一是：真正的转账（真正的银行卡的钱发生了变动），二是**展示**金额转账（不仅是UI展示，也包括数据展示。实际真的银行卡钱有没有变动，不一定）。

如下图所示。调用第三方红包SDK（真正的金额转账）是开发者自己的事情，Turms不会干涉（也不应该干涉）。而其中的“发送自定义消息”（转账的**表现形式**），这一步骤本质就是用户或群组间传递Turms中的Message消息。而Message中有一个字段是text(String)，另一个字段是records(byte[])，Turms并没有限制其内容必须是什么。因此您完全可以用这两个字段传递任何内容，比如红包场景常见的，用text字段来传递红包数据结构的json数据。红包发送方和接收方就通过这个text，就可以进行双向互动。
希望您理解了“发红包”的本质，能明白Turms不计划做这类功能的原因。

![](http://yx-web.nos.netease.com/webdoc/im/android/send-rev-rp.png)

这类问题很有意思，感谢反馈。

**Comment by KevinHe666** [comment]
十分感谢 说的很详细 明白了 turms主要是im消息的 红包转账其实只是一种消息,具体内部操作调用第三方服务或者就自己开发拓展了
