### ISSUE TITLE
Failed to build turms-client-js on the master branch

### ISSUE THREAD

**Issue by yjz1004** [turms-im/turms#554]
under the turms-client-js folder of the master branch，execute the following command：

> cnpm install
> npm run build

build error，The details are as follows：

> turms-client-js@0.9.0-dev.20200212 build /Users/jz/Workspace/public/turms/turms-client-js
> npm run protoc && npm run webpack

> turms-client-js@0.9.0-dev.20200212 protoc /Users/jz/Workspace/public/turms/turms-client-js
> pbjs --no-create --no-verify --no-convert --no-delimited -t static-module -w commonjs -o ./src/model/proto-bundle.js ./src/proto/**/*.proto & pbts -o ./src/model/proto-bundle.d.ts ./src/model/proto-bundle.js

installing semver@^7.1.2
installing semver@^7.1.2
installing chalk@^4.0.0
installing jsdoc@^3.6.3
installing tmp@^0.1.0
installing uglify-js@^3.7.7
installing estraverse@^5.1.0
installing chalk@^4.0.0
installing jsdoc@^3.6.3
installing tmp@^0.1.0
installing uglify-js@^3.7.7
installing estraverse@^5.1.0
/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/cli/pbjs.js:245
            throw err;
            ^

Error: no such Type or Enum 'Int64Values' in Type .im.turms.proto.TurmsNotification.Data
    at Type.lookupTypeOrEnum (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/namespace.js:407:15)
    at Field.resolve (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/field.js:265:94)
    at Type.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/type.js:301:21)
    at Type.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/namespace.js:304:25)
    at Type.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/type.js:305:43)
    at Namespace.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/namespace.js:304:25)
    at Namespace.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/namespace.js:304:25)
    at Namespace.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/namespace.js:304:25)
    at Root.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/namespace.js:304:25)
    at Root.resolveAll (/Users/jz/Workspace/public/turms/turms-client-js/node_modules/_protobufjs@6.9.0@protobufjs/src/root.js:248:43)

> turms-client-js@0.9.0-dev.20200212 webpack /Users/jz/Workspace/public/turms/turms-client-js
> webpack --mode=production

Hash: 4de82cc9722541b8f434
Version: webpack 4.44.2
Time: 16462ms
Built at: 2020/12/02 下午2:38:43
 22 assets
Entrypoint turms-client = turms-client.js
Entrypoint turms-client-min = turms-client-min.js
  [0] ./src/util/request-util.ts 1.86 KiB {0} {1} [built]
  [1] ./src/util/notification-util.ts 4.15 KiB {0} {1} [built]
  [5] ./src/model/proto-bundle.js 712 KiB {0} {1} [built]
  [9] ./src/model/turms-status-code.ts 6.79 KiB {0} {1} [built]
 [10] ./src/util/constant-transformer.ts 3.86 KiB {0} {1} [built]
 [17] ./src/model/turms-business-exception.ts 1.52 KiB {0} {1} [built]
 [44] (webpack)/buildin/global.js 472 bytes {0} {1} [built]
[148] ./src/service/group-service.ts 13.7 KiB {0} {1} [built]
[149] ./src/service/storage-service.ts 7.66 KiB {0} {1} [built]
[150] ./src/service/notification-service.ts 833 bytes {0} {1} [built]
[151] ./src/util/input-file-reader.ts 2.5 KiB {0} {1} [built]
[152] ./src/driver/turms-driver.ts + 2 modules 17.3 KiB {0} {1} [built]
      | ./src/driver/turms-driver.ts 14.7 KiB [built]
      | ./src/util/timer.ts 1.27 KiB [built]
      | ./src/model/turms-close-status.ts 1.18 KiB [built]
[153] ./src/service/user-service.ts + 2 modules 14.8 KiB {0} {1} [built]
      | ./src/service/user-service.ts 14.1 KiB [built]
      | ./src/util/system-util.ts 241 bytes [built]
      | ./src/model/user-location.ts 402 bytes [built]
[154] ./src/service/message-service.ts + 1 modules 11.9 KiB {0} {1} [built]
      | ./src/service/message-service.ts 11.5 KiB [built]
      | ./src/model/message-addition.ts 246 bytes [built]
[155] ./src/turms-client.ts 2.6 KiB {0} {1} [built]
    + 228 hidden modules

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/turms-driver.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/turms-driver.ts(316,28)
      TS2349: This expression is not callable.
  Type 'typeof import("/Users/jz/Workspace/public/turms/turms-client-js/node_modules/unfetch/dist/unfetch.module")' has no call signatures.

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/turms-driver.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/turms-driver.ts(337,24)
      TS2349: This expression is not callable.
  Type 'typeof import("/Users/jz/Workspace/public/turms/turms-client-js/node_modules/unfetch/dist/unfetch.module")' has no call signatures.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! turms-client-js@0.9.0-dev.20200212 webpack: `webpack --mode=production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the turms-client-js@0.9.0-dev.20200212 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jz/.npm/_logs/2020-12-02T06_38_43_745Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! turms-client-js@0.9.0-dev.20200212 build: `npm run protoc && npm run webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the turms-client-js@0.9.0-dev.20200212 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jz/.npm/_logs/2020-12-02T06_38_43_786Z-debug.log

**Comment by JamesChenX** [comment]
Please build by "yarn build" or "npm run build" again under the latest "develop" branch.
I have tested it and it should work fine.

BTW: The master hasn't updated for a long time and it will be updated months later when v0.10.0 is ready.

**Comment by yjz1004** [comment]
I download the latest delelop branch and use command as follows:

> npm install
> npm run build

but,it is also report errors:

> turms-client-js@0.10.0-SNAPSHOT build /Users/jz/Workspace/public/turms/turms-client-js
> npm run protoc && npm run webpack


> turms-client-js@0.10.0-SNAPSHOT protoc /Users/jz/Workspace/public/turms/turms-client-js
> pbjs --no-create --no-verify --no-convert --no-delimited -t static-module -w commonjs -o ./src/model/proto-bundle.js ./src/proto/**/*.proto & pbts -o ./src/model/proto-bundle.d.ts ./src/model/proto-bundle.js


> turms-client-js@0.10.0-SNAPSHOT webpack /Users/jz/Workspace/public/turms/turms-client-js
> webpack --mode=production

[webpack-cli] Compilation finished
assets by status 585 KiB [cached] 32 assets
orphan modules 115 KiB [orphan] 24 modules
runtime modules 442 bytes 2 modules
modules by path ./node_modules/core-js/ 174 KiB
  modules by path ./node_modules/core-js/internals/*.js 105 KiB 122 modules
  modules by path ./node_modules/core-js/modules/*.js 68.4 KiB 44 modules
modules by path ./node_modules/protobufjs/ 44.5 KiB
  modules by path ./node_modules/protobufjs/src/*.js 27.6 KiB 6 modules
  modules by path ./node_modules/protobufjs/src/util/*.js 16.8 KiB 2 modules
  ./node_modules/protobufjs/minimal.js 96 bytes [built] [code generated]
modules by path ./node_modules/@protobufjs/ 21.6 KiB 6 modules
modules by path ./src/ 119 KiB
  ./src/turms-client.ts + 24 modules 119 KiB [built] [code generated]
  ./src/model/proto-bundle.js 445 bytes [built] [code generated]
./node_modules/long/src/long.js 39.2 KiB [built] [code generated]

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/state-store.ts
./src/driver/state-store.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/state-store.ts(19,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/driver/turms-driver.ts 54:0-39 72:27-37
 @ ./src/turms-client.ts 11:0-48 24:25-36

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/turms-driver.ts
./src/driver/turms-driver.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/turms-driver.ts(20,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/turms-client.ts 11:0-48 24:25-36

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/service/connection-service.ts
./src/driver/service/connection-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/service/connection-service.ts(21,9)
      TS2305: Module '"../../model/proto-bundle"' has no exported member 'im'.
 @ ./src/driver/turms-driver.ts 52:0-61 83:32-49
 @ ./src/turms-client.ts 11:0-48 24:25-36

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/service/message-service.ts
./src/driver/service/message-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/service/message-service.ts(18,9)
      TS2305: Module '"../../model/proto-bundle"' has no exported member 'im'.
 @ ./src/driver/turms-driver.ts 50:0-55 75:31-45
 @ ./src/turms-client.ts 11:0-48 24:25-36

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/service/reason-service.ts
./src/driver/service/reason-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/driver/service/reason-service.ts(24,9)
      TS2305: Module '"../../model/proto-bundle"' has no exported member 'im'.
 @ ./src/driver/turms-driver.ts 49:0-53 76:30-43
 @ ./src/turms-client.ts 11:0-48 24:25-36

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/model/parsed-model.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/model/parsed-model.ts(1,9)
      TS2305: Module '"./proto-bundle"' has no exported member 'im'.

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/model/turms-business-error.ts
./src/model/turms-business-error.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/model/turms-business-error.ts(1,9)
      TS2305: Module '"./proto-bundle"' has no exported member 'im'.
 @ ./src/service/message-service.ts 36:0-63 85:13-40 89:13-44 112:13-40 126:13-40 130:13-40 148:13-40 175:15-42 211:13-40 229:13-40 248:13-40 267:13-40
 @ ./src/turms-client.ts 14:0-55 27:33-47

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/group-service.ts
./src/service/group-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/group-service.ts(2,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/turms-client.ts 13:0-51 26:31-43

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/message-service.ts
./src/service/message-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/message-service.ts(2,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/turms-client.ts 14:0-55 27:33-47

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/storage-service.ts
./src/service/storage-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/storage-service.ts(3,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/turms-client.ts 17:0-55 28:33-47

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/user-service.ts
./src/service/user-service.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/service/user-service.ts(2,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/turms-client.ts 12:0-49 25:30-41

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/util/notification-util.ts
./src/util/notification-util.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/util/notification-util.ts(1,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'google'.
 @ ./src/service/message-service.ts 34:0-57 106:13-41 142:13-41 191:13-48 205:13-48 219:13-48
 @ ./src/turms-client.ts 14:0-55 27:33-47

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/util/notification-util.ts
./src/util/notification-util.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/util/notification-util.ts(1,17)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/service/message-service.ts 34:0-57 106:13-41 142:13-41 191:13-48 205:13-48 219:13-48
 @ ./src/turms-client.ts 14:0-55 27:33-47

ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/util/system-util.ts
./src/util/system-util.ts
[tsl] ERROR in /Users/jz/Workspace/public/turms/turms-client-js/src/util/system-util.ts(1,9)
      TS2305: Module '"../model/proto-bundle"' has no exported member 'im'.
 @ ./src/service/user-service.ts 7:0-45 97:25-49
 @ ./src/turms-client.ts 12:0-49 25:30-41

webpack 5.9.0 compiled with 14 errors in 14335 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! turms-client-js@0.10.0-SNAPSHOT webpack: `webpack --mode=production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the turms-client-js@0.10.0-SNAPSHOT webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jz/.npm/_logs/2020-12-03T01_24_15_562Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! turms-client-js@0.10.0-SNAPSHOT build: `npm run protoc && npm run webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the turms-client-js@0.10.0-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jz/.npm/_logs/2020-12-03T01_24_15_611Z-debug.log

**Comment by JamesChenX** [comment]
OK, it seems that I need to update the "Quick Start".
The reason for the error is the submodule "proto" hasn't been fetched.
And you can get the proto module in two ways:

1. Input the following commands to clone the whole repo:
```
git submodule update --init --recursive
git submodule foreach git pull origin master
```

2. Download the files in https://github.com/turms-im/proto and put it in the "turms-client-js/src/proto" folder.

As a result, you should get the directory structure (Note that the "proto" folder should exist):
```
C:\TURMS-PUB\TURMS-CLIENT-JS\SRC
├─driver
│  └─service
├─model
├─proto
│  ├─constant
│  ├─model
│  │  ├─common
│  │  ├─file
│  │  ├─group
│  │  ├─message
│  │  ├─signal
│  │  └─user
│  ├─notification
│  └─request
│      ├─group
│      │  ├─blacklist
│      │  ├─enrollment
│      │  └─member
│      ├─message
│      ├─signal
│      ├─storage
│      └─user
│          └─relationship
├─service
└─util
```

**Comment by yjz1004** [comment]
Thanks,it's worked fo me!
