### ISSUE TITLE
Throw an exception "_turmsClient2.default is not a constructor" when importing turms-iclient-js@0.9.0-dev.20200212

### ISSUE THREAD

**Issue by yjz1004** [turms-im/turms#555]
I use taro develop rn app.I copy dist>turms-iclient.js to my project，the code as follows:
`
import Taro, { Component, Config } from '@tarojs/taro'
import TurmsClient from '../public/turms-client/turms-client.js'
import Index from './pages/index'

class App extends Component {

  componentDidMount () {
    const client = new TurmsClient();
    console.log(client);
  }

  ...

  render () {
    return (
      <Index />
    )
  }
}

Taro.render(<App />, document.getElementById('app'))
`

the error as follows:

TypeError: _turmsClient2.default is not a constructor

This error is located at:
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at react-native-root-siblings/index.js:32)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

App.componentDidMount
    app.js:7725:19
commitLifeCycles
    ReactNativeRenderer-dev.js:15036:19
commitAllLifeCycles
    ReactNativeRenderer-dev.js:16635:6
Object.invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:93:9
invokeGuardedCallback
    ReactNativeRenderer-dev.js:318:30
commitRoot
    ReactNativeRenderer-dev.js:16875:6
<unknown>
    ReactNativeRenderer-dev.js:18501:6
Object.unstable_runWithPriority
    scheduler.development.js:653:11
completeRoot
    ReactNativeRenderer-dev.js:18498:12
performWorkOnRoot
    ReactNativeRenderer-dev.js:18427:8

**Comment by JamesChenX** [comment]
Please build turms-client-js on your own and it should work (What you did in https://github.com/turms-im/turms/issues/554 is correct. So just go head).

The v0.9.0 is a legacy implementation and I have updated a lot of features and fix a lot of bugs on the "develop" branch.
Keep working on the "develop" branch until v0.10.0 is released. (It needs to take several months)
