### ISSUE TITLE
你好，现阶段有release版本吗

### ISSUE THREAD

**Issue by yarnping** [turms-im/turms#574]

**Comment by JamesChenX** [comment]
不好意思，没有。

这也是我一直惭愧的地方。项目太大，长路漫漫。精力有限，分身乏术。
由于最开始没打算把Turms做成大项目，因为项目小，各种功能实现都非常灵活且高效，一般都是尽可能多开发点features，因此上半年连发了好几个v0.9.0的版本，当时就是奔着发正式release去的。
但后来做了体量的调整（往成熟的大项目方向做），很多workflow都要重新设计，因此很多上述的features都变成了非常低效的实现，还需要花些时日重构完这部分功能（部分要移除，部分要重写）。这也是大半年一直更新，但就是没发新版本（0.10.0）的主要原因。

下次发布的v0.10.0版本（预计在明年3~6月份发）基本就是正式发布的alpha版，随之而来会有大量的设计文档帮开发者做training（如即时通讯经典场景的实现对比）。对即时通讯有兴趣的同学，可以先试试往Turms提PR。

额外提一点。瘦死的骆驼比马大，虽然先阶段Turms还有很多不足之处，但对比其他即时通讯开源项目在中大体量用户规模的场景应用，依旧是碾压局。

**Comment by yarnping** [comment]
打算基于turms做一个公司内部的im，如果可行的话，可以参与PR
可以出一个build instruction吗

**Comment by JamesChenX** [comment]
对于国内企业内部IM，其实放眼全球的开源圈子，该类应用很尴尬，因为没有一个适合国内的成熟开源项目。

对比几类产品：
1. Turms。如果是做公司内部IM的话，其实不是很推荐Turms，因为这项目主要是给互联网应用做的。跟企业IM相比，二者功能需求、质量需求、领域模型、架构设计千差万别。如果想基于Turms做企业IM开发，那就南辕北辙，舍近求远了。

2. 国内的IM开源项目。国内的开源IM项目，我应该都看过源码。逃不出下面这几条：1. 代码质量过低，一看就知道是民科爱好者，或是十几年前的学院派代码，或是写的一手其他语言风格的代码；2. 无架构设计意识，也没有做一个完整项目的意识；3. KPI项目，这类项目对比其他开源IM质量最高，但最后都是结局都是中道崩殂。总之，都不推荐。

3. 国外有几个不错的IM开源项目。比如在README推荐的Rocket Chat，但其缺点就在于可能不是很适合国内领导审美。另外，特别一提的是，国内还有很多用Openfire这类开源做XMPP企业内部IM的，但个人不是很推荐，都是考古项目了，最好还是先调研下Rocket Chat这类符合现代项目需求的项目。

综合以上，如果你要做企业IM的话，我觉得有两条相对靠谱的路：一是调研下Rocket Chat开源项目符不符合你们的需求。如果可以的话，基于它做二次开发；二是用国内IM服务商的服务。


最后：关于Turms的Quick Start，你可以看：https://github.com/turms-im/turms/blob/develop/turms-docs/src/zh/for-developers/quick-start.md
或者https://turms-im.github.io/for-developers/quick-start

**Comment by yarnping** [comment]
好的，非常感谢您的建议 😄
是这样的，一是我们的产品需求不急，二是看了部分源码，对您的项目感兴趣，想学习研究一下
另外受限于团队需求及技术栈，国内IM & Rocket Chat都不太适合 😄
