### ISSUE TITLE
rpc loadbalance和服务注册是怎么考虑的呢

### ISSUE THREAD

**Issue by yarnping** [turms-im/turms#576]
看到rpc的LB通过时间戳取模，加上服务注册用的ttl，那么在node down掉的情况下，可能会出现服务不可用的情况，不知道我理解对不？

**Comment by JamesChenX** [comment]
先纠个错，RpcService和DiscoveryService是两个独立的Services，而TTL属于DiscoveryService里的概念，因此RPC不是用TTL来定义requests超时时间，仅仅是RpcService维护一个自己的“timeoutDuration”。

关于提到的“在node down掉的情况下，可能会出现服务不可用的情况”，我理解为“在某个node down掉的情况下，其他节点的RPC操作会不会有异常行为”作答（因为node down了，这个node自然是不可用的）。

这一块Turms目前做了相对周全的考虑：
1. 如果Node是正常关闭（即graceful shutdown，而非force shutdown），这种case最简单，这个Node会主动unregister它的信息，不会发生“意外”。

2. 如果Node是被force shutdown，这时注册中心仍有该节点信息。但Turms集群仍会正常运转，因为：1. turms的master节点会根据心跳超时时间（默认10秒）来判断其他节点是否还存活，如果超时，DiscoveryService就会剔除该节点信息，给RpcService提供最新的members信息。2. 如果在这个心跳超时时间内，DiscoveryService提供给RpcService这个已失效的Node信息，此时通常会返回ClosedChannelException异常，如果RpcService检测到这个异常，RpcService会“识趣”地去找其他节点，再次进行requests。因此也没有“意料之外”的事情会发生。

3. 如果Node节点没有挂，但网络被隔离了。兜底策略同2，也不会发生“意外”。

**Comment by yarnping** [comment]
> 1. turms的master节点会根据心跳超时时间（默认10秒）来判断其他节点是否还存活，如果超时，DiscoveryService就会剔除该节点信息，给RpcService提供最新的members信息
代码还没看太多，问一下有master election吗
