### ISSUE TITLE
请教Leader节点的作用

### ISSUE THREAD

**Issue by chinamcafee** [turms-im/turms#861]
在阅读源码的过程中，只发现了Leader在”集群节点管理“API中有被使用到，没有发现成为Leader的节点有什么比普通Member节点而言更为特殊的作用，不知是否是我阅读源码有相关疏漏，文档中也没有提及Leader节点的作用，还请不吝赐教。

**Comment by JamesChenX** [comment]
总体而言，需要保证只有一个节点触发或执行的动作，通常就由Leader节点执行。（背景知识：该类动作估计也有好几个。传统实现方法一般通过节点抢占分布式锁，但其可靠性、可控性与性能都远不如使用统一Leader的方案）

具体动作而言
1. Leader最重要的动作之一就是根据其他节点在服务注册中心（MongoDB）的心跳刷新时间，来更新各节点的最新状态（具体代码在：`im.turms.server.common.cluster.service.discovery.LocalNodeStatusManager#updateMembersStatus`）
2. “定期cron向Redis发送清除过期黑名单记录的指令”这一动作，这样的动作就只需一个节点，即Leader定期执行。
3. “定期cron删除过期数据库数据操作，如用户消息”，也有且仅会被Leader执行（PS：这类操作的代码其实是“历史遗留问题”，顺便保留的。毕竟极少应用会真得删除用户数据，因此默认disabled状态，可以忽略）

另外，关于“集群”概念的实现（如RPC/服务注册与发现）我是打算写篇文档的。最近比较忙，可能在最近1/2个月再发出来。

**Comment by chinamcafee** [comment]
了解，非常感谢
