### ISSUE TITLE
关于Turms项目的个人向问题

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#862]
## 关于名利问题

人生而自由，却无往不在枷锁之中。多读历史（如新中国后的历史）、感受宇宙的无尽、时代的变迁与生命的轮回（“简单”体验下生个病躺床上难受到不能动，就明白了），思考人死后的无尽虚无，自然会放下很多很多东西。当看近代之事时，这种感觉更甚。有如蒋友柏“旧时王谢堂前燕，飞入寻常百姓家”，小时候经历过大名大利，现在只是像普通人一样生活。又如我个人尤其喜爱挖掘二十世纪末的优秀音乐与歌手（如森田童子、Nina Simone），偶尔还会在youtube看到一些音乐人（很多演唱人都是40~70岁）数年如一日地投放播放量寥寥的[优秀艺术视频](https://www.youtube.com/watch?v=3q7TEJiK4eA&ab_channel=JuuIchi)。偶尔也会听点戏曲，想想当年戏曲是多么地火爆，而现在还有多少年轻人听。但另一方面，也有一些年轻人依旧坚守与发展“落寞”了的传统艺术，而在“利”上，这些行业的普通人比起被资本堆起来的技术圈里的普通人的工资相比，还是有些距离的。这种切身感受到的“名”与“美”的不相关性更让人感概“名利”之虚无。

另外，很多“名”也是虚伪的。有时看到一些接受过“高等教育”的人甚至也完全活在社会主流价值之下，也是感慨万千。阿多诺曾在《文化批判与社会》写道“奥斯维辛之后，写诗是残忍的”来批判在犹太人被“科学地论证”为劣等种族后，即便上百万的犹太人在奥斯维辛里被屠杀，竟然还有诗歌为该泯灭人性的恶魔行径站台，称赞其行为的正当性。种族屠杀尚可被颠倒黑白，何况是我们现在文明社会的种种行为。什么是真善美，什么是假恶丑，自己心中有数就好，何必追求这些虚名（就比如很多一些厂喜欢以“黑客马拉松”的名义，以极廉价的费用招一批大学生免费帮忙干活，集结其他们的创意）。

当然，做开源能得名得利自然也是好事，虽然我个人对技术圈的名本身没有丝毫兴趣（一是现在国内技术圈几乎只有资本，没有黑客精神与人文精神，个人已经快将其当成“娱乐圈”看待了；二是最近我在读技术哲学与社会加速批判理论，我目前对部分技术的发展持怀疑态度），但由名带来的利还是感兴趣的，因为利能切切实实地促成其他理想的实现与兴趣爱好的发展。但犹如爱情一样，命里有时终须有，命里无时莫强求。穷则独善其身，达则兼济天，穷富各有各的活法。万物皆备于我矣，反身而诚，乐莫大焉。

而我个人写Turms项目的目的很简单：一是个人从小就非常喜欢创造性活动，二是兴趣爱好写有技术含量的项目（如同一些人喜欢打篮球、爬山、摄影），三是锻炼逻辑思维。因此Turms有多少人用，能否从中得利这样的Bonus，我是随缘的。有挺好，没有也行。跟那些专心拯救传统艺术的艺术、投入支教的教师、救人命的医生等等岗位的人相比，Turms这样的项目真不算什么。我开源Turms就似给你表演一段评弹，大伙有兴趣就坐下来听听，没兴趣就匆匆离开，大家都开心就好。无论能否从Turms项目中得名得利，Turms这项目都能一直做下去，除非我有朝一日出家了，或者人没了。

另外，虽然Turms本质上而言，目前确实只是个人项目，写Turms项目也只是我众多爱好之一。但如果您有兴趣看其源码与文档，看其各种技术实现的细节，相信您会感受到Turms比大部分的公司项目“有原则”且“专业”地多，毕竟绝大部分公司项目只是为了“混口饭吃”，秉着“代码能跑，别人看不出烂就行”的态度而写的，这点上过班的都懂。而跟其他开源IM项目相比，正如我在README反复强调的，Turms这方面是碾压局（如果您怀疑这点，您可以自己一条条对比Turms的特性与其他开源IM的特性），主要还是同行开源IM项目太蒙混了，一个系统做了10%，A能往B发消息了，就以为可以糊弄外行人了，就开始专注搞外宣，但同行之间互相用心看代码/文档的话，都能看出大家真实水平的。（PS：当然Turms也有小部分没写好的Legacy代码）

## 关于开源项目的热度问题

如何一方面活在资本社会，另一方面又抵御资本对人的异化，真是门大学问。但可惜，很多人压根没意识到资本对人的异化问题（多亏了国内的应试教育与几乎为零的美学教育，中国只有党文化教育。以及你点开你手机上的任意一个资讯App，看看有多少咨询与艺术人文相关），这样的无意识导致开源圈子同其他行业一样，也涌入了大量的“戏子”，生产出一堆水文水项目来炒流量以谋求利益，导致劣币驱逐良币，让一批又一批新人不分美丑，让善恶颠倒，让整个圈子恶性循环。犹如国内的“偶像”圈一样，一切流量至上，啥妖魔鬼怪都能被资本神化成“偶像”与“演员”，真有演技的演员反而拿不到角色。社会的众生相真是印证了陈丹青说的“中国最要紧就是混饭吃，管它什么文化”。

人生追求的本质不外乎追求“真善美”，通过知识欲来求“真”，通过道德欲来求“善”，通过美欲来求“美”，而其他途径都只是歪门邪道，诸如纵欲。而资本的异化与消费主义的审美庸化让人逐渐丧失“审美”的能力，这是极其险恶与可怕的，可谓杀人诛心，在世俗化的社会，人连“审美”能力都没有了，何来追求“美”的事物？口口声声对其他行业评头论足，到了自己的行业就干偷鸡摸狗，蝇营狗苟之事。明明是身体健康的人却活成了行尸走肉。如同一些人学了PUA，搞性泛滥，就逐渐丧失了“爱”的能力，舍本逐末，得不偿失。人若是没了对“真善美”的追求只会被资本拿来当枪使，“努力奋斗，再给老板再买一套房！”。但也得亏是在和平国度，不然可能就成为政治斗争下的“卒”了。

好似鲁迅说的“学医救不了中国人”，这话至少同样适用于中国开源圈，国人的平均人文素养与思辨能力不提高，开源圈诞生不了“黑客精神”这样的无私精神。今天开源圈内的成员的人文素养水平仍停留在“最要紧就是混饭吃，管它什么文化”，国内开源的发展举步维艰：贡献者缺乏专业态度，做项目糊弄了事，一切流量优先（看Github上的国人开源IM项目就是个好例子）；你敢开源，旁边一堆竞品等着套皮与抄袭；打着“黑客精神”的旗号，却干着资本剥削之事（国内的Hackathon）。你说中国程序真大佬（假的大佬更多）多吗？多。但可惜整个圈子根本的人文素养更不上，开啥源呢。

而刷热度就是我们这圈子上述堕化行为的表现。要刷热度很简单，尤其以程序员的工资来看，真不缺那点钱。但刷热度就是放任自己接受资本的异化，放纵自我表层欲望的行为，结合上述个人对名利的看法与开源的原因。夏虫不可以语冰，我和这类人不是一类人，甚至很可能不是一个世界的人。Turms未来可能会找人推广（虽然目前完全没计划），但不会炒不应该属于Turms的热度。

## 关于被抄袭问题

国内的一个现实情况是：套皮与抄袭成风。甚至不少厂以套皮与抄袭不被人知为荣，并耻笑与污名化其他人的利他行为，滑天下之大稽。当然，我也能理解，毕竟奥斯维辛屠杀上百万人都能被“科学地逻辑论证”洗白。

具体到Turms这个项目而言，Turms的“非原创性”让我个人不会有“这么精妙的设计怎么能被人白白拿去”的想法，与其体系的全面性与定制化让我觉得“要是有人能学完Turms设计的后，还能开源一个新IM项目全面超过Turms，那真是本事，令人敬佩”，再结合个人对名利随缘的态度，大家可以放心抄袭。现世的我只会在之后建个“耻辱柱”描述其抄袭的行为，并发几个帖子谴责顺便推广下Turms，然后回到自己的世界，大家继续各自安好。

* Turms的“非原创性”主要指的是其思想：诸如基于双数组Trie的AC自动机算法的敏感词过滤体系、IM消息处理流程、数据库的横向/垂直拆分、集群功能实现等等，这些思想没啥原创性，早有人提出了与普及了，都是靠多读书、多读优秀项目源码（诸如Elasticsearch/Ignite的漂亮代码）、多实践，融会贯通各类思想，集百家之长自然而然整理出来的，然后为Turms所用。反倒是别人免费分享那么精妙的设计（如基于双数组Trie的AC自动机算法），这些设计让我从零开始想的话，可能到死我都想不出，让我心怀感激，Turms那点“原创性”真不算什么，被人抄了也没什么大事。

* Turms的全面性指的是系统组件的全面，诸如一整套集群功能环环相扣的设计、数据库水平与垂直拆分的设计（背后有很多细节）、可观测体系的设计、黑名单体系设计、敏感词体系设计、运维体系设计等等，不是说实现了A用户能给B用户发消息就能叫“IM体系”，这也是敢把Turms叫做“The world's most advanced open source instant messaging engine”的原因，事实如此，多靠同行的衬托。
  要是真有开源IM项目能全面超过Turms项目的高度，诸如开源一整套商用级别的敏感词过滤体系实现（当然，这是不可能发生的事情），并整合到自己的IM系统中。那也确实值得令我敬佩，我会感叹开源IM领域终于其他人能举大旗前行了，终于能让我也能心怀感激地学习同行写的代码了。但目前还远远没看到能打的开源IM项目，几年观察下来的其他开源IM都还是走哗众取宠炒热度那条路线（实话说，国内大小厂开源的大部分项目，其代码质量令人咋舌。当然，考虑到一部分老油条，为了提升自身的不可替代性，故意设计出看似没问题，但实际很绕圈的逻辑，这种能力也令人佩服），希望开源的同行们再接再厉有朝一日成为参天大树。

  （国内也有做得好的IM服务，可惜都是闭源的，他们现在也不可能把有商业价值的服务免费开源）

* Turms的定制化让抄袭的成本比自己写的成本高。诸如为什么这块功能采用反范式设计，是没设计好，还是另有隐情？为什么这个数据库字段使用A索引，而不采用常见的B索引？为什么黑名单采用Redis做分布式内存实现，而不采用Gossip算法实现等等诸如问题，这些设计的背景与动机是，要是全写出来直接就能出本几百页的书了，但一口气写完又不现实。而如果没有对应的文档，那其他人只能猜其设计的场景与意图，猜对了还是错了也没有反馈，那还不如自己写一套，何必抄袭呢。或者换种说法，如果Turms是别人写的项目，以我现在的水平来探索Turms各种背后的设计意图，对于没文档的部分，我也只能靠猜。

  并且对于高级工程师而言，学设计的思想然后自己写代码，会比直接抄代码简单与高效。这也是为什么很多调包也能做的事情，Turms要自己写（补充：还有其他很多原因，具体见[关于依赖库的使用](https://turms-im.github.io/docs/intro/redevelopment.html#%E5%85%B3%E4%BA%8E%E4%BE%9D%E8%B5%96%E5%BA%93%E7%9A%84%E4%BD%BF%E7%94%A8)）。绝大部分开源依赖一来没什么技术含量，都是给人写烂了的思想或技术，花几分钟浏览下技术依赖的源码，理清下思路，再花点时间定制化代码实现即可。这其中以Turms效仿Replicated Map数据结构，定制Turms的全局黑名单体系实现最为突出。

鉴于上述各种原因，就算我个人知道一些人是怀着“抄袭”目的而来，只要这些人能问出有意义的问题，我个人也会细心回答。我个人对Turms相关的名利没什么兴趣，对其他人能否通过抄袭Turms得名得利也没兴趣，大家所在的世界可能不一样，我只会感觉和这些深知资本异化的+无自我意识的人沟通感到无聊。

PS：另外推荐“有志于”抄袭Turms项目的人用Java或类Java语言来抄（尤其考虑现在很多IM项目喜欢用Go语言写服务端），具体原因以Turms基于双数组的AC自动机实现敏感词过滤体系为例。如果想用“Go”抄一遍Turms，那真挺费劲的，且截至目前（2021年11月5日）全网除了Turms以外，你也找不到其他靠谱实现。但如果你用类Java语言来写，就能实现“直接Copy代码，稍微改改就能跑”，何乐不为。

## 关于热情
**这是一个魔幻的技术圈，“做大型开源项目就是为了玩，追名逐利/吹牛逼/自由精神都是次要目标，没有也没所谓”这样的目标不少人不相信，竟然还成了需要向其他人解释的事情。**

一些人做大型开源项目，真得就是玩（当然，项目质量始终是专业水平，Turms吊打其他开源IM项目还是没问题的）。只要能明白这一点，就能理解一些人为什么做开源真是“无欲无求”：

* 不求名、不求利。如果我想求名求利，立高大的技术精英人设，我就没必要主动在开源项目上，写个“战书”，搞个这么不专业的行为，并在帖子里diss互联网大公司的无耻行为。看一些程序员刻意立精英人设，一辈子带着面具生活，我首先是感觉这些人的心智没成熟，只是世俗知识变多了；第二是感觉这些人很可怜，好像是那一直跑圈的仓鼠，一直跑着也不知道为啥。

* 不求团体合作，不求有人能帮我把开源项目做得更好。有些老哥发邮件说他们想参加我的开源项目，我一般都回类似：感谢你对Turms项目的认可，你能参与进来我当然是欢迎且感谢的。但我不希望有人给Turms“白打工”，希望在你给Turms项目做贡献的同时，你也确实能从Turms中获益。但老实说，有没有人参与进来，我是无所谓的，因为“我开源单纯就是玩”。

  然后别人就“？？？”了，估计大家都没见过这么奇葩且佛系养生的大型开源项目维护者。

* 行业会不会因此变得更好或更卷（知识贬值），我不关心。

* 不伟大，也不圣人。没有多少人会觉得，自己天天煲剧/打游戏很伟大吧？开心就完事了。

* 也不是理想主义。有人喜欢打篮球，并且水平很专业，但不开班收钱，没人会说ta是理想主义吧？

* 什么“为了回馈社会、传承自由精神”就更离谱。我目前极其浅薄的哲学功底，还不足以让我到达“为了回馈社会，为了传承自由精神”这境界。另外，如果我看到一些国内开源项目写着类似的话，那我一般会首先想到：

> 我翻开历史一查，这历史没有年代，歪歪斜斜的每页上都写着“仁义道德”几个字。我横竖睡不着，仔细看了半夜，才从字缝里看出字来，满本都写着两个字是“吃人”！

虽然这些项目没“吃人”这么夸张，但我确实很难相信一个没有哲学/文学训练或社会阅历，且被资本主义+消费主义+国家宣传洗过脑的人，会达到“为了回馈社会，为了传承自由精神”这种境界，尤其是见过太多满嘴空话的伪开源项目。

我相信很多最开始做真开源的人，心里也真没想过什么赚钱或出名。黑客精神/自由精神？不好意思，我完全没听过，哥们我就是玩。只是后来看太多“流量演员”赚钱了，再看到身边朋友都买房、结婚、生子了，自己心态绷不住了。这其中就涉及到世俗话语权的问题，部分国人被世俗的话语权与话语框架束缚太久，忘了如果脱离这套话语体系该如何思考与说话。

至于什么是脱离这个话语体系的世界？如果想快速见识下“其他世界”的样子，那我就推荐[尾崎豊 僕が僕であるために](https://www.youtube.com/watch?v=UvHjYtmOSXk&ab_channel=1102Hill)，看呐，这是多么**纯粹又热情**的人。又或者是给人推荐[彼女は革命家（女朋友是革命家）](https://www.youtube.com/watch?v=PUL_5OQUthQ&ab_channel=MonkeyD.Sound)，估计很多人是第一见“女朋友”能和“革命家”扯上关系，艺术永远能带我们发现原来还有那么多不一样的世界，这也是为什么我一直强调人必须要接受美学教育，否则只能无脑接受“资本嗓门大，资本说啥是美的，那它就是美的，值得追求的”，那是多么机械的人，多么充满塑料味的人生。

我看来一个人有没有意思，有没有自我意识。关键就看ta在某领域能不能做到“纯粹而又热情”。相反，如果一个人搞啥都想到搞钱（除非这人确实急需用钱，或家庭确实很困难），除了搞钱，对啥都没热情。这类人我一般把ta默认为只具备“动物本能”的人，尽量不要和这些人有什么交际（这也是为什么一些老哥给我发邮件，我回“Turms这项目有没有技术大牛参与进来，我真无所谓。我只看能不能发现有意思的人”。其实我心里更真实想法是“有没有大佬进来关我P事”）。一些老哥活着活着就把生活中纯粹与能感觉热情的事情丢光了，眼里只剩钱了，却还得带着“精英”人设，真是让人哭笑不得。把具备内在价值的事物全给丢了，这些被异化的人当然可以炫耀ta的工具价值，但他们还是“人”吗？为什么这些人的所思所想那么模板化，真得好像一个流水线上的产品，说着重复的话，重复，重复，重复，毫无生气，灵魂没了。可能只有当这些人经历人生的重大变故（比如得个癌症、亲人逝世），才发现功名利禄真不过如此、带着不属于自己的“精英”人设，为陌生人活着真的是很幼稚的行为。

> 洛阳城东桃李花，飞来飞去落谁家？
> 洛阳女儿惜颜色，坐见落花长叹息。
> 今年花落颜色改，明年花开复谁在？
> 已见松柏摧为薪，更闻桑田变成海。
> 古人无复洛城东，今人还对落花风。
> 年年岁岁花相似，岁岁年年人不同。
> 寄言全盛红颜子，应怜半死白头翁。
> 此翁白头真可怜，伊昔红颜美少年。
> 公子王孙芳树下，清歌妙舞落花前。
> 光禄池台文锦绣，将军楼阁画神仙。
> 一朝卧病无相识，三春行乐在谁边？
> 宛转蛾眉能几时？须臾鹤发乱如丝。
> 但看古来歌舞地，唯有黄昏鸟雀悲。

**Comment by chinamcafee** [comment]
👍大佬的开源精神令人敬佩，我辈编程界的小学生希望有朝一日可以追随上大佬开源精神的脚步，躬体力行，改善国内的开源环境

**Comment by seantso** [comment]
膜拜大佬！

**Comment by 598572** [comment]
令人敬佩的开源精神，我也在开源一个IM项目  和Turms比  简直是小巫见大巫了哈哈，作者厉害！很有情怀！
