### ISSUE TITLE
Cannot access the demo site (Playground)

### ISSUE THREAD

**Issue by jun1st** [turms-im/turms#887]
如果您是网站普通访客：

请等待网站备案后尝试访问。

如果您是网站所有者，网站无法访问常见原因如下：

1. 网站未完成备案、未在接入商完成备案接入。

2. 网站内容与备案信息不符、备案信息不准确、网站存在不适宜传播的内容等。

**Comment by JamesChenX** [comment]
Thanks for the reminder, and it will work again once I migrate the demo site to AWS next week.
And you can track the progress in #869

**Comment by JamesChenX** [comment]
Done. The demo site cannot be accessed now.
