### ISSUE TITLE
无法启动turms-gateway

### ISSUE THREAD

**Issue by LinkZhang** [turms-im/turms#890]
按照文档没做任何改动，用docker-compose方式单机部署，发现turms-gateway起不来，是因为turms-service 一直是unhealth，看下报错日志是
```
 500 Server Error for HTTP GET "/actuator/health"
java.lang.ClassCastException: class org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$WebFluxEndpointHandlerMethod cannot be cast to class org.springframework.web.reactive.result.method.TurmsHandlerMethod (org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$WebFluxEndpointHandlerMethod and org.springframework.web.reactive.result.method.TurmsHandlerMethod are in unnamed module of loader 'app')
	at org.springframework.web.reactive.result.method.annotation.TurmsControllerMethodResolver.getRequestMappingMethod(TurmsControllerMethodResolver.java:54)
```

**Comment by JamesChenX** [comment]
@LinkZhang Please rerun `docker-compose -f docker-compose.standalone.yml up --force-recreate`, and it should work this time.

**Comment by LinkZhang** [comment]
可以了

**Comment by zhangyc** [comment]
> 可以了

ERROR: for turms-gateway  Container "ddce122271cd" is unhealthy.
ERROR: Encountered errors while bringing up the project.
您后来怎么解决的。我也遇到了这个问题

**Comment by JamesChenX** [comment]
@zhangyc You can try the following commands to check if it can work currently:
```bash
sudo git pull
sudo git reset --hard
docker pull ghcr.io/turms-im/turms-admin
docker pull ghcr.io/turms-im/turms-gateway
docker pull ghcr.io/turms-im/turms-service
sudo ENV=dev,demo docker-compose -f docker-compose.standalone.yml --profile monitoring up --force-recreate -d

```

If any container still fails to run, you can `sudo docker logs <FAILED_CONTAINER_ID>` and copy the logs here so that I can help you to figure out why it failed.

**Comment by zhangyc** [comment]
> @zhangyc You can try the following commands to check if it can work currently:
> 
> ```shell
> cd <the root folder of Turms git project>
> sudo git pull
> sudo git reset --hard
> docker pull ghcr.io/turms-im/turms-admin
> docker pull ghcr.io/turms-im/turms-gateway
> docker pull ghcr.io/turms-im/turms-service
> sudo ENV=dev,demo docker-compose -f docker-compose.standalone.yml --profile monitoring up --force-recreate -d
> ```
> 
> If any container still fails to run, you can `sudo docker logs <FAILED_CONTAINER_ID>` and copy the logs here so that I can help you to figure out why it failed.

![image](https://user-images.githubusercontent.com/10071342/153543852-5fb0debc-49cb-44a9-9f8b-d2757e8204a0.png)

**Comment by zhangyc** [comment]
您能看懂中文太好了，已经安装好了，但是按照您的文档描述，默认密码turms，一直提示missing。

**Comment by zhangyc** [comment]
> @zhangyc You can try the following commands to check if it can work currently:
> 
> ```shell
> cd <the root folder of Turms git project>
> sudo git pull
> sudo git reset --hard
> docker pull ghcr.io/turms-im/turms-admin
> docker pull ghcr.io/turms-im/turms-gateway
> docker pull ghcr.io/turms-im/turms-service
> sudo ENV=dev,demo docker-compose -f docker-compose.standalone.yml --profile monitoring up --force-recreate -d
> ```
> 
> If any container still fails to run, you can `sudo docker logs <FAILED_CONTAINER_ID>` and copy the logs here so that I can help you to figure out why it failed.

多谢，发现是别的问题，已经解决。打扰您了
