### ISSUE TITLE
create user error

### ISSUE THREAD

**Issue by LinkZhang** [turms-im/turms#892]
in UserService addUser method

![image](https://user-images.githubusercontent.com/10371414/147717399-5af1c9de-e2a5-47b5-9edc-dac2d7fb9118.png)

upsert() should change to insert() , Otherwise you cannot create a new user, but overwrite the information of the first user

**Comment by JamesChenX** [comment]
@LinkZhang Thanks. It's not a problem between upsert() or insert(), but a problem of filter. I will fix it in 1 hour.

```java
  @Override
    public <T> Mono<Void> upsert(ClientSession session, T o) {
        Class<T> clazz = (Class<T>) o.getClass();
        MongoEntity<T> entity = (MongoEntity<T>) context.getEntity(o.getClass());
        MongoCollection<T> collection = context.getCollection(clazz);
        Bson filter = entity.shardKey(); // where the bug comes
        if (filter == null) {
            filter = EMPTY_FILTER;
        }
        Bson update = encodeEntityForUpdateOps(o);
        Publisher<UpdateResult> result = session == null
                ? collection.updateOne(filter, update, DEFAULT_UPSERT_OPTIONS)
                : collection.updateOne(session, filter, update, DEFAULT_UPSERT_OPTIONS);
        return Mono.from(result)
                .onErrorMap(translator::translate)
                .then();
    }
```

**Comment by JamesChenX** [comment]
The bug has been fixed but I don't plan to publish the new release right now because I just found another trivial bug and I will publish the new release once it is also fixed.

**Comment by JamesChenX** [comment]
@LinkZhang Please rerun `docker-compose -f docker-compose.standalone.yml up --force-recreate`, and it should work this time.

**Comment by LinkZhang** [comment]
it works
