### ISSUE TITLE
parseInt bug

### ISSUE THREAD

**Issue by LinkZhang** [turms-im/turms#911]
![image](https://user-images.githubusercontent.com/10371414/148715604-a2c99459-af25-49bc-84fb-5c99fa7f4b3e.png)
 
the user id is long type, but in js parse a string to long will cause somes bugs
![image](https://user-images.githubusercontent.com/10371414/148715883-5f189ac0-3873-404d-baae-041d6e8c18b8.png)

**Comment by JamesChenX** [comment]
I will fix the bug later because I found that the page for `Online Users` was written 2 years ago, and it used an old API schema that doesn't exist anymore, and I will redesign the page later.

**Comment by JamesChenX** [comment]
Fixed.
