### ISSUE TITLE
给各国产半开源IM项目的战书

### ISSUE THREAD

**Issue by JamesChenX** [turms-im/turms#912]
# 给各国产半开源IM项目的战书

本文基调：《影子》——P.O.E

本文非常地“不正式”、“不专业”，因此没贴到项目文档里，算是半闲聊，单开Ticket来Diss下国产半开源IM项目，也借着这机会diss下一些国内这伪开源风气（至于为什么不关注国外，一是我看过的国外IM开源项目，质量都有保证，不像国内这么离谱；二是太“远“，没什么兴趣关注他们的圈子）。

另外，很多明眼人不敢开贴diss国内开源项目，主要是大家都一个圈子的，一是怕得罪人，自己不好混；二是当心自己哪天也变成他们那样。我个人就不怕了，如我在[关于Turms项目的个人向问题](https://github.com/turms-im/turms/issues/862)，个人对这个圈子的名利没什么兴趣，也不需要设什么高大的人设，我混文艺圈的，因此不怕得罪技术圈的任何人，CTO/CEO犯错了，我照样diss。

**国内确实有很多真大牛，尤其是很多默默无闻的大牛，但更多的是一群到处混流量，混吃混喝的神棍。本人对前者表示尊敬，对后者表示：滚出这个圈子，别拿娱乐圈的手段混技术圈。**

## 本文的目的

* 看到一堆水货吹牛逼，还敢做成商业项目，污染开源环境。我很早就想开帖子来diss了，不吐不快。我学了好多年的日语+乐器，我的技能水平仍处于“不敢见人”的水平，毕竟自己有多菜，自己是清楚的。如果只是因为单纯我菜，那其他人没啥好diss的，毕竟大家都是从新手过来的。但如果我自己菜，还敢自称自己“专家”，并且向人收费做培训，那被人diss就是活该了。
* 写给Turms用户看的，我相信很多人会把Turms跟其他国产开源IM项目比。但我觉得没必要，因为这就好比拿一个小学生画的画，拿去跟职业画家的作品比。Turms项目确实还有很多缺点，也因此没敢发v1.0，但还不至于惨到要跟其他国产开源IM项目比的地步。
* 好玩。我做开源和Diss这些项目的根本目的一样，我不怕得罪任何人，也不怕Turms这项目死了，跟说唱1V1 Battle一样，就是玩儿。[《中国新说唱2019》PM小丑 VS 守卫](https://www.youtube.com/watch?v=4hv8uHpRZwk&ab_channel=iQIYI%E7%88%B1%E5%A5%87%E8%89%BA)

## 本文Diss的对象

本贴Diss的也不是这些半开源IM项目的商业模式，这些商业模式很正常，无可厚非。本文diss的是：自称自己是专业团队，且团队内都是高级工程师、专家，然后一看代码：哥，心里没数吗？你是流量演员，没人关心，但不要自称自己是演技派，很恶心人（当然，这些老哥也是倒霉，本来混吃混喝，混得好好的，遇到我这种敢怼天怼地，敢揭他们底裤的人）。我甚至很纳闷这些码农，工作3~10年，代码质量怎么连优秀点的大学生都搞不过，甚至怎么有脸自称高级工程师或专家。这些老哥的开源项目给我一看就不需要面试了，都工作这么多年了，代码还能写得这么烂也是“高难度”，我也很建议他们写篇文章谈一谈是怎么做到数十年如一日的原地踏步的，并且还有脸皮吹嘘自己技术水平的，我想学习一下。联想到最近有个技术圈还算火的新闻，就是西安一码通讲它们“高技术含量”的技术优化，“将一张图片从1MB压缩到500KB，再从500KB优化到100K”，我刚开这一新闻的时候，以为是“高级黑”，后来才发现竟然是官方写的文章。这优化不就是传说中的：

```
// 不要去掉该函数。老板让你做优化时，你就改成9秒，给后来的人多些活路
Thread.sleep(10 * 1000);
```

没想到这水平的“优化”也敢厚着脸皮写文章谈“炫技”。

## 开Battle

**先总结，我建议各位“专家”在本贴下Battle之前，先报个黑马程序员培训班，把编程的门给入了。**

**以下Diss的对象，不仅仅是国内开源IM圈。国内的开源风气大家有目共睹，如果还有新人不清楚，那就请持续关注Github Trending上的中文开源项目（当然，很多项目因为KPI已经死完了，Trending上看不到了），屎壳郎们越来越多，以至于大家都不以为奇了，谁都可以来拉泡屎，反正”跟大家一起闯红灯，我怕啥“，而这篇文章也是写给这些伪开源项目的战书。**

### 这些开源IM项目哪块文档或代码能体现这个团体里有高级工程师，或是专家？

把自觉有自信的代码贴一贴，我过去帮你review下代码。是不是水货，代码一看便知。

### Commit都不会写

用一句话中文/英文描述这一个Commit做了啥是很难的事情吗？工作了这么多年，离谱到连Commit都不会写吗，老板是你亲戚朋友吗？甚至一整个专业团队都不会写Commit吗？这叫专业团队？还是你们的专业团队外包项目给大学生做的？被层层吃回扣了？还是就怕别人看懂，耽误你们赚咨询费？

### 作为商业团队月更，不回Issue

一个团队，那么多“专家”，但很多commits都只是更新下版本号、更新下配置。Turms这项目我目前倒贴钱做，都能保持日更（最次一周也更2次），每1~4周还有发新Features，具体看Turms这3年的Commits历史记录。我建议你们把项目外包，那效率可能更高。
另外，自己的开源仓库也没几个Issues，一个团队那么多人，为什么从来不给人回复呢？怕耽误贵团队赚咨询费？

### 作为KPI项目，刷完绩效闪人

README说的巨牛逼，干劲满满，准备做大做强，再创辉煌。结果一看最后的Commit记录还在N年前，屎壳郎般的存在。

### 代码质量非常低

这个问题其实是我纳闷了很久的一个问题。很多稍微靠谱些大学生，他们的代码质量其实就已经不错了，工作几年就成真大牛了。怎么这些开源IM项目的“专业”团队都工作这么多年，还能写出这么业余的代码，自己代码是什么水平都没意识到？尤其是一些还是互联网大厂，真得离谱。另外注意，我用的是“业余”一词，还没入门的水平。还是大家都赶着下班去吃饭/带娃，无心写好代码？

### 作为商业项目，连可观察性与防刷限流机制都没有，直接裸奔？

自称自己是专业团队，自称是IM系统，但基本就支持用户A往用户/群组B发消息，一个系统连最基本的可观测性体系、防刷限流都不支持。我建议贵团队回到大学校园，找几位大学生，向他们请教下微服务的基本设计。还是开源版本啥功能没有？只有商业版有？那为什么用户不去用成熟的即时通讯云呢？

### 作为商业项目，只能单机部署，集群不懂如何实现？

还自称自己是专业团队？建议招几个优秀点的大学实习生，给贵团队辅导下如何实现集群。如果不舍得花这钱，也不怕，B站有很多培训班课程，让贵“专业”团队先把大学知识补了。还是说，社区版不支持集群，商业版支持？那问题又来了，那为什么用户不去用成熟的即时通讯云呢？

### 作为商业项目，连敏感词过滤都不做吗？

甚至某半开源IM项目，敏感词实现竟然用全量扫描，贵专业团队没一个人会写/抄AC自动机算法？建议过来Turms项目把`turms-plugin-antispam`的代码Copy过去，还有啥功能不会写在Turms项目下提Issue，我免费给你做，不用谢。

### 作为专家了，数据库连数据分片功能都不做吗

Turms项目默认就提供了数据分片功能，我相信一部分用户甚至都没意识到Turms有这功能，因为Turms只需要一条指令就把所有环境自动搭建好了：`ENV=dev,demo docker-compose -f docker-compose.standalone.yml --profile monitoring up --force-recreate -d`

### 项目过度设计

需求与架构有点脱节，甚至我有点怀疑是不是在“面向简历编程”。明明中大型IM的基本关键功能都没实现，如数据分片，只能往小规模IM场景做，但却还搞引入一堆服务端、又是Kafka、又是MySQL/MongoDB混用。如果需求本来就不复杂，那为什么还把架构搞这么复杂？如果需求本来就很复杂，那不得从数据库建模开始向上重构整个项目？我建议贵团队再上个K8S，并且把数据库也丢K8S，最好还跨云混用云服务，以增加贵团队的不可替代性。

当然，我知道一些老哥的良苦用心，毕竟要靠咨询费/定制服务费赚奶粉钱，我帮你说出来了而已。

### 刷Star、Fork
这和你们最鄙视的简历造假有什么区别？只许州官放火，不许百姓点灯？

**不要一口一个我们团队都是专家、高级工程师，一边软件工程水平+代码水平连大学生都搞不过的代码，太魔幻现实了。身边没人diss，那是大家有利害关系，碍于情面。平时在家里说自己长得像彭于晏，没事，但去到大街上，没那颜值还这么说，那路人可就“呵呵”了。其实更离谱的是，为什么一些程序员工作那么多年，连“职业”水平都达不到？弹钢琴4、5年的人都不好意思说自己是专业弹钢琴的，除非天赋异禀，不然会被人喷得很惨，而一些老哥学4、5个月编程，就开始自称自己是“专业”的。还好程序员这行业，看同领域内的程序员水平还算比较简单，Talk is cheap. Show me the code，是不是妖魔鬼怪一看便知。**

啥时候想到了再补充，欢迎各国产开源IM项目过来Battle

补充内容：
### 伪开源项目特征
1. 套皮、抄袭，然后发文说是自研项目。如：
字节跳动的：https://github.com/DouyinFE/semi-design/issues/70;
（这个不是开源项目，但是套皮）https://zhuanlan.zhihu.com/p/447977025
京东的：https://zhuanlan.zhihu.com/p/45653912、https://zhuanlan.zhihu.com/p/45745354
2. 花钱或互相刷Star、Fork、刷榜
阿里巴巴的：https://www.zhihu.com/question/494108102
3. 前期声势浩大，发各种推文，尤其是年底要刷KPI，刷完之后项目就直接暴毙，对开源社区毫无尊重。如：
腾讯的：https://github.com/Tencent/Tendis
阿里巴巴的：https://github.com/alibaba/tengine/issues/921
https://github.com/alibaba/ApsaraCache
PS：阿里巴巴KPI项目虽多，但靠谱+有价值的项目也挺多
4. 故意增加入门门槛（如文档要收费、长期不回复Issues，甚至故意把代码写得混乱），以赚取咨询费/服务费等，对开源社区毫无尊重
5. 以开源为噱头，结果开个残缺的社区版，开发团队月更，且每次更新就更新下几行文档+配置+版本号
6. 自称专业团队，结果代码质量、架构设计、文档、接口/协议定义水平是入门水平

国内真开源：OpenRestry、ShardingSphere、ant-design、TiDB、现在的dubbo等等

**Comment by JamesChenX** [comment]
我这边也承诺，**免费**给所有用户做所有能做的功能，没有什么双授权，没有什么商业服务。至于为什么一些功能没法做，可以参考该文档：http://localhost:8080/docs/for-developers/schema.html#%E5%8A%9F%E8%83%BD%E4%B8%B0%E5%AF%8C%E7%9A%84%E8%87%B4%E5%91%BD%E4%BB%A3%E4%BB%B7。
另外，这里的“用户”也包括“外包用户”、“竞争对手用户”、“抄袭用户”等等。比如说，就算我知道你是来抄袭我项目的，没关系的，只要大家正常提Issue，我也**免费**给你做Feature，我不关心各位用户的动机是什么。我做开源，就图个好玩、开心。这就好比，我直播弹钢琴，你点了一首你喜欢的歌，如果我正好有空弹，那就给你弹了。

很多人说做开源要么求名，要么求利。我两个其实都不大所谓，我如果要求名求利，我就没必要置顶战书，diss这个行业的一些人，断别人的财路了。我diss伪开源项目，就好像我初中刚学日语的时候，我们的QQ群主开语音帮我们diss那些冒充日语老师，想骗我们钱的“日语老师”。虽然隔着网线，但我那时就觉得她浑身宛如散发着光芒，太帅气了。

我做开源就是好玩、开心，我“充钱”买服务器的感觉，就跟一些老哥充钱买游戏装备的感觉一样，我充钱“打游戏”为什么还要想着怎么出名+赚钱呢？部分国人被世俗的话语权与话语框架束缚太久，忘了如果脱离这套话语体系该如何思考与说话（这点，可以向低年级的小学生学习，很多小学生的思想还没有被污染）。一些人可能听过`古筝悦人，古琴悦己`，这话虽然非常离谱，但开源对我而言，就是`悦己`，从整个行业发展来看`悦人`这是“顺便”的事情。

一些老哥没见过真开源，Turms这就叫真开源。

**Comment by zhjphp** [comment]
刚开始了解IM，确实如上所说，乌烟瘴气

**Comment by nchair** [comment]
> 刚开始了解IM，确实如上所说，乌烟瘴气，99%的都是伪开源，打着开源的幌子，顶一下

不是99%，国产的99.999999%，那0.000001%还没出现，恶心的很！

**Comment by bungder** [comment]
> 

老哥，虽然我也同意国内开源氛围不好，但是这个99.999999%太夸张了，基数已经去到千万级了......

**Comment by bungder** [comment]
> > 刚开始了解IM，确实如上所说，乌烟瘴气，99%的都是伪开源，打着开源的幌子，顶一下
> 
> 不是99%，国产的99.999999%，这0.000001%不知道是不是这个项目

老哥，虽然我也同意国内开源氛围不好，但是这个99.999999%太夸张了，基数已经去到千万级了......

**Comment by Mihoks** [comment]
大赞啊，阿婆主霸气，真心话，不单单是im项目，很多项目说是开源，开放1%的功能 给你看，要用就收费，部署文档要看就收费，乌烟瘴气，不过这也跟国内开源环境有关，拿来即用，白嫖党 拿来就改，不会关注开源协议

**Comment by CyJaySong** [comment]
这是把野火也骂了一顿吗

**Comment by JamesChenX** [comment]
@CyJaySong 借题发挥，统一写一下对这类问题的回复。

每次遇到感兴趣的开源项目类型，我都会去读它们的源码，有时候我会为作者的精妙设计拍案叫绝，竟然能把如此复杂的需求与系统 设计得如此清晰，让我来设计的话，我还真达不到这样的高度。
想试着我有没有可能再优化下它的设计，但思来想去，我基于它去做所谓的“优化”也只是画蛇添足。庆幸自己又淘到了这么优秀的项目，挺开心。

而看到屎山代码，我都是避之不及。如果被迫需要给这些代码“添砖加瓦”，我都是遍敲代码，遍痛骂原作者水平怎么如此之低。其中的痛苦滋味，我想大部分有工作经验的人都有所体会。

因此，我十分佩服哪些放弃优秀开源项目不学不用，转而盯着屎山看的工程师，这种技术品味我确实是无法理解。

---

不仅如此，如果一个“工程师”工作多年之后，其设计与代码水平都还很低，那也反应出一个更重要的问题，就是：工作态度与开源态度（如果是开源项目的话）。
我在工作中设计的项目与编写的代码，我有自信说是实战级的“教科书级水平”，我工作中从来不写所谓的“防御性代码”，也不会为刷简历而引入技术栈，反而是为了帮助同事或用户更好地理解我的项目，我的文档会写得非常全。这就像我对待我负责的开源项目一样，有使用文档，有内部原理设计文档，就怕自己没说清，就用户看不明白。
我认为，对自己负责的项目，抱有责任心的人才配得上高级工程师，而一个有责任心的、工作多年的工程师，ta的工作态度、开源态度与代码水平是不可能差的（有责任心的人如果写出屎山，只会觉得羞愧+丢人）。而工作态度的重要性，对于上班族来说，那就不言而喻了，一个话总结：跟有责任心的人合作，真得很舒服和安心。

---

对自己负责的项目都没责任心的人，用户又怎敢指望ta们会对用户上心呢？这让我想到当今开源圈很流行一种玩法。以一个我觉得非常有意思，且形象的图为例（懒得找图了，我就文字描述下）：有人在草原上放了一些诱饵来吸引其他动物，等引来一大群动物都在专心吃诱饵的时候，就砰地一声猛地把搭在诱饵上方的笼子落下，然后里面的动物就会惊慌失措，到处逃窜，但怎么也逃不出笼子。每每想到“开源圈”中的这类场景，我还是觉得非常滑稽，哈哈哈哈哈哈。
很多人是不懂得尊重别人的（不仅是一些开源作者，也包括一些开源有用户）。

中国有一句俗话，叫“淡泊明志，宁静致远”，对用户不尊重的人，其实是不适合做开源项目的。加上当今人心普遍比较浮躁，如果一个人心不静（得摆脱“我执”，不要太把自己的存在当回事，才容易心静），自己做了开源又总觉得自己怀才不遇，或者赚不到钱，干脆又把开源项目archive，让一群用户凌乱在风中。或者干脆玩双开源协议，卖文档来赚钱，让之前的用户如同刚刚所述的草原动物。

这类项目，怎么会有用户敢去用？开源用户也得提升技术审美，与识别作者责任心的能力，远离没有责任心的工程师与ta们维护的项目。

**Comment by RiseInRose** [comment]
老哥，顶你！！！我刚开始写代码时，同事关系紧张，也搞过“防御性编程”，拼命的复杂化，直到，不停的读到大佬的开源代码，真的是太优雅了！自己写的，简直就是垃圾中的垃圾。后来也就是释然了。现在只关注需求本身，达到需求的情况下用最简单的方式去实现。文档也非常清晰。在我的推广下整个组的效率提升非常多。谁写防御性代码，我就让他读优秀的开源项目！

**Comment by tony91988** [comment]
兄弟，看了你的文章刷了几个小时，深深的佩服，虽然我是个菜鸡，可是从事im行业7年，各种代码买了无数坑踩了无数。你的文章让我热血沸腾，我想骂你的人也肯定很多应该都是同行，不过我还是敬佩，不知道是否可以联系交个朋友。
