### ISSUE TITLE
How to import `turms-client-kotlin` for Android projects in Gradle

### ISSUE THREAD

**Issue by zhangyc** [turms-im/turms#934]
I tried to package turms-client-kotlin into a jar package for use in android, but the jar content after packaging became like this. I don't know what's going on?

**Comment by zhangyc** [comment]
![image](https://user-images.githubusercontent.com/10071342/154012249-bf82246a-48e4-4482-a4a5-8521e477a8db.png)

**Comment by JamesChenX** [comment]
Though you have closed the issue, I think this is a good question so I comment (btw, I will post an article to introduce how to install them recently).
1. `cd <the_root_path_of_turms_project`
e.g. `C:\projects\turms`
2. run `mvn install -pl turms-client-kotlin -am`
e.g. `C:\projects\turms>mvn install -pl turms-client-kotlin -am`
And the command will install the jar of `turms-client-kotlin` in e.g. `C:\Users\James Chen\.m2\repository\`
3. Now you can import `turms-client-kotlin` in your Android application project.
Remember to add the local maven repo in `build.gradle`:
```
repositories {
    mavenLocal()
}
```

**Comment by zhangyc** [comment]
You are really great, I didn't solve the packaging problem, our application is developed with flutter. Because I plan to port the sdk to the dart platform, I closed this iss.

We are a small startup company. Currently looking for a suitable im solution to replace Rongyun, our business model is more similar to Discord. Currently looking at the documentation and code of turms.

Since our business is quite different from traditional IM, it takes a lot of effort to transform the third-party SDK.

Finally, thank you for your reply, if your turms plan is adopted, we are also willing to pay for consultation.


| |
zhangyc
Android
|
|
***@***.***
|
签名由网易邮箱大师定制
On 2/15/2022 ***@***.***> wrote：

Though you have closed the issue, I think this is a good question so I comment (btw, I will post an article to introduce how to install them recently).

cd <the_root_path_of_turms_project
e.g. C:\projects\turms
run mvn install -pl turms-client-kotlin -am
e.g. C:\projects\turms>mvn install -pl turms-client-kotlin -am
And the command will install the jar of turms-client-kotlin in e.g. C:\Users\James Chen\.m2\repository\
Now you can import turms-client-kotlin in your Android application project.
Remember to add the local maven repo in build.gradle:
repositories {
    mavenLocal()
}


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyc** [comment]
![image](https://user-images.githubusercontent.com/10071342/154188338-477fc814-b8ef-43a6-aecb-24bbc5aadc08.png)

**Comment by zhangyc** [comment]
![image](https://user-images.githubusercontent.com/10071342/154188423-c4490d80-2202-4ab0-9ec1-648c4b56012b.png)

**Comment by zhangyc** [comment]
it can't work

**Comment by JamesChenX** [comment]
I think you are using the wrong cache in your local maven, and I have tested the config I have commented above and it works fine:
![image](https://user-images.githubusercontent.com/44962329/154193716-08a81636-267d-4df9-973e-0e370b85ced1.png).

To clean your local cache, you can delete the folder of `turms-client-kotlin` in your local maven repo, e.g.`C:\Users\James Chen\.m2\repository\im`.
And just build and install the jar again, and it should work.

**Comment by zhangyc** [comment]
I don't know what the difference is between our local environment, after I cleaned the cache, or only the common module is normal, and there is still no valid content in the kotlin-client's jar package。

**Comment by zhangyc** [comment]
The jar package generated in the local maven repository after I execute mvn install -pl turms-client-kotlin -am is like this 
![image](https://user-images.githubusercontent.com/10071342/154942782-ba840816-56d6-456d-b6de-4daef6f2bb66.png)

**Comment by JamesChenX** [comment]
@zhangyc please pull the code from `develop` branch again and run `mvn install -pl turms-client-kotlin -am`.

**Comment by zhangyc** [comment]
Our project really wants to use your turms. After solving the dependency problem, I spent 1-2 days trying to run a demo on the android platform. I want to try every interface of the client, but I failed. Not familiar with kotlin is a reason. On the other hand, I think your sample is too simple, which makes it extremely difficult to get started. Hope you think about it. Hope the turms are better.

--------------------------------------------
Below is the error I get when I create a TurmsClient object.
2022-02-23 18:07:54.639 2586-2586/?E/PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
2022-02-23 18:07:54.672 26581-26581/? E/studio.deploy: Could not remove dir '/data/data/com.lsj.turms/code_cache/.ll/': No such file or directory
2022-02-23 18:07:54.735 2586-2586/?E/PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
2022-02-23 18:07:55.388 30155-30155/com.lsj.turms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lsj.turms, PID: 30155
    java.lang.ExceptionInInitializerError
        at client.TurmsClient.<init>(TurmsClient.kt:53)
        at com.lsj.turms.MainActivity.onCreate(MainActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3612)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3796)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 10
    @\{(\d+?)}
              ^
        at com.android.icu.util.regex.PatternNative.compileImpl(Native Method)
        at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:53)
        at com.android.icu.util.regex.PatternNative.create(PatternNative.java:49)
        at java.util.regex.Pattern.compile(Pattern.java:1429)
        at java.util.regex.Pattern.<init>(Pattern.java:1404)
        at java.util.regex.Pattern.compile(Pattern.java:962)
        at im.turms.client.service.MessageService.<clinit>(MessageService.kt:236)
        ... 18 more


---------------------------------------------
this is my code

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

         client = TurmsClient("39.103.139.114",11510,100,100,100,100,"",scope.coroutineContext) // TurmsClient("127.0.0.1", 11510)

    }

**Comment by JamesChenX** [comment]
@zhangyc The exception you commented on seems to have nothing to do with `turms-client-kotlin`. The exception is caused by:
```
2022-02-23 18:07:54.639 2586-2586/?E/PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
2022-02-23 18:07:54.672 26581-26581/? E/studio.deploy: Could not remove dir '/data/data/com.lsj.turms/code_cache/.ll/': No such file or directory
```
You can try to comment out and check if the exception is thrown again. If not, it means the exception isn't thrown by `turms-client-kotlin`.:
```kotlin
// client = TurmsClient("39.103.139.114",11510,100,100,100,100,"",scope.coroutineContext) // TurmsClient("127.0.0.1", 11510)
```

btw: I think you can just try `client = TurmsClient("39.103.139.114",11510)` if you are not sure what you are coding.

**Comment by JamesChenX** [comment]
About the examples on docs, I think the problem isn't the APIs of turms-client-x are difficult to use because they are really easy to use indeed, but the docs don't stress how to use the APIs in an easy way. So I will and some docs to stress how to use it later. 

Thanks for the feedback.

**Comment by zhangyc** [comment]
If there is no reply from you, I may be about to give up. I have been learning kotlin for a while (I have seen it before, but I haven't really used it), because during this period of time, in addition to deploying the server. I'm not making any progress in the client's direction. I'm trying to port a flutter client sdk, hope you can give me some advice.


| |
zhangyc
Android
|
|
***@***.***
|
签名由网易邮箱大师定制
On 2/23/2022 ***@***.***> wrote：

About the examples on docs, I think the problem isn't the APIs of turms-client-x are difficult to use because they are really easy to use indeed, but the docs don't stress how to use the APIs in an easy way. So I will and some docs to stress how to use it later.

Thanks for the feedback.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JamesChenX** [comment]
@zhangyc For dart clients, in fact, I have planned to develop a new project `turms-client-dart` so that Flutter users can just use it without porting both `turms-client-kotlin` and `turms-client-swift` to dart in a hard way.
And if you really need `dart` version, I can just develop one in 2/28~3/2, so you can just wait for it.

Or, you may also try `turms-client-js` in WebView if WebView is acceptable for your projects.

**Comment by zhangyc** [comment]
This is really good, my project is using flutter, so webview is not suitable.Looking forward to the dart version.Of course I can also offer some help if you need it.



| |
zhangyc
Android
|
|
***@***.***
|
签名由网易邮箱大师定制
On 2/24/2022 ***@***.***> wrote：

@zhangyc For dart clients, in fact, I have planned to develop a new project turms-client-dart so that Flutter users can just use it without porting both turms-client-kotlin and turms-client-swift to dart in a hard way.
And if you really need dart version, I can just develop one in 2/28~3/2, so you can just wait for it.

Or, you may also try turms-client-js in WebView if WebView is acceptable for your projects.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JamesChenX** [comment]
@zhangyc I have published `turms-client-dart` and done some simple tests on it.
You can try it currently.

btw, `turms-client-dart` cannot work in browsers.

**Comment by JamesChenX** [comment]
Done. Feel free to open a new ticket.
