### ISSUE TITLE
multi device simultaneous login, send message not as expected

### ISSUE THREAD

**Issue by chinamcafee** [turms-im/turms#975]
I fork turms and modified turms demo as follows:
https://github.com/chinamcafee/turms/tree/develop/turms-client-js/demo

I added demo2.html and js/business2.js

About business2.js, I set login deviceType as "DESKTOP" at line 42:
` client.userService.login(userId, password,"DESKTOP")`

Then I opened two client page, and click "发送消息给用户1" button as follows:
<img width="3005" alt="image" src="https://user-images.githubusercontent.com/3439961/173815383-b617be6a-d994-4cdc-8521-f71e40600c56.png">

demo2.html page shows that both user1 and user2 which login as "DESKTOP" are received message.

But user1 at demo.html  which login as default "BROWSER" didn't receive any message.

I think User1 and User2 which login as "DESKTOP" are received message is correct, but User1 login as "BROWSER" didn't receive message is not as expected.

Is there any bugs in my modified business2.js?  Or  is  there some bug at server side ?

Any help is appreciated，thanks.

**Comment by JamesChenX** [comment]
Thanks for reporting. I will try to reproduce it on my local computer tomorrow, and fix it within 48 hours if it's a bug.

**Comment by JamesChenX** [comment]
Fixed. Please pull the latest code from the branch `develop`.

**Comment by chinamcafee** [comment]
I have tested the latest code and find that the problem above is indeed fixed. Thanks a lot. 

But I found another problem. When I click the button "发送消息给用户1" from the  User2 "DESKTOP" window on the right side，user2 can also receive the message  which sent by itself.

Since user2 login as "DESKTOP" is the message sender, does it need to receive message sent by itself again?

The screenshot as follows:
<img width="2906" alt="image" src="https://user-images.githubusercontent.com/3439961/175514848-f8e064bc-7959-482c-bc36-90c4280e91ec.png">

Thanks again for your help.

**Comment by JamesChenX** [comment]
Thanks for reporting.
I noticed it when I tested it last time, but I thought it was a feature so I didn't fix it (it's a bug in fact), haha.
I have fixed and tested it, and please pull the latest code from the branch `develop` to have a try.

**Comment by JamesChenX** [comment]
@chinamcafee I have fixed and tested it, and please pull the latest code from the `branch` develop to have a try.
And you don't need to say "Sorry for bothering you" when reporting a potential bug, and any reporting is welcome.
