### ISSUE TITLE
The data persistence problem

### ISSUE THREAD

**Issue by zhjphp** [turms-im/turms#997]
I use turms-admin to add group data, when i restart turms-service, turms-gateway, redis-server , the group data, user data,  was disappeared, and the peer-to-peer messaging was disappeared too.

I see the data in mongodb, bug i don't understant the data how to disappeared when i restart the server and redis.

**Comment by JamesChenX** [comment]
What do you mean when you said `disappeared`?
* Does you get an empty result when querying the data via admin APIs while it should not be empty? If so, you need to check your query conditions/filters first, and then check whether you get data from the cache via debugging.

* Or is the data just removed from MongoDB? If so, `turms-service` only drops collections at startup if it's running in non-production environments and `turms.service.fake.clear-all-collections-before-faking=true` (false by default).

**Comment by zhjphp** [comment]
> 



> What do you mean when you said `disappeared`?
> 
> * Does you get an empty result when querying the data via admin APIs while it should not be empty? If so, you need to check your query conditions/filters first, and then check whether you get data from the cache via debugging.
> * Or is the data just removed from MongoDB? If so, `turms-service` only drops collections at startup if it's running in non-production environments and `turms.service.fake.clear-all-collections-before-faking=true` (false by default).

Thank you , the problem is `turms.service.fake.clear-all-collections-before-faking=true`,  i use dev config.
